[TS] LPP-48048 -> LPS-176371 Default language specified in a structure is not used when creating a new web content
liferay-echo/liferay-portal pull request #11312
Opened 2023-03-02 09:22 UTC by TaiPhamLR

Hi team,
This PR is for the ticket https://issues.liferay.com/browse/LPS-176371 , It resolves the issue [LPP-48048](https://issues.liferay.com/browse/LPP-48048). Please help me review it.
Thanks a lot.

2023-03-02 09:22 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-03-02 09:23 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-03 13:48 UTC, lfbesada requested changes
Hi @TaiPhamLR
Thanks for the PR ❤️ 
I have added a few commits, please see: https://github.com/liferay-echo/liferay-portal/pull/11323
Regards

2023-03-03 13:48 UTC, closed without merging

2023-03-03 13:49 UTC, lfbesada commented
See: https://github.com/liferay-echo/liferay-portal/pull/11323