LPS-178946 AUI module liferay-portlet-segments-simulation into a js component
liferay-echo/liferay-portal pull request #11885
Opened 2023-04-26 06:51 UTC by Stephy6

Motivation
=======
The motivation behind this ticket is to migrate from the usage of AUI scripts to use a js component.
https://issues.liferay.com/browse/LPS-178946

Proposed Solution
========
What we did to solve this problem to use a Liferay-frontend component in the view.jsp and change the structure of the js so it is a function component.

Steps to Verify
========
1. Create some segments and some experiences.
2. Open the simulation panel
3. Check that the segments are correctly displayed

2023-04-26 06:51 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-04-26 06:51 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-26 09:14 UTC, p2kmgcl requested changes
Hey @Stephy6! I added some comments to the PR. Please have a look at them :smile:

2023-04-26 09:14 UTC, p2kmgcl commented on modules/apps/segments/segments-simulation-web/src/main/resources/META-INF/resources/js/main.js
> +				'#' + form.id + ' input'
I think we can use a string literal here like you did above :cat:, something like `#${form.id} input`.

2023-04-26 09:14 UTC, p2kmgcl commented on modules/apps/segments/segments-simulation-web/src/main/resources/META-INF/resources/js/main.js
> +			const simulationElement = document.querySelectorAll(
I think we should name it `simulationElements`, with an 's', because querySelectorAll always returns an array.

2023-04-26 09:14 UTC, p2kmgcl commented on modules/apps/segments/segments-simulation-web/src/main/resources/META-INF/resources/js/main.js
> +			simulationElement.setAttribute('checked', false);
:thinking: this should not work. `simulationElement` is an array and does not have the `setAttribute` method. We should loop through the array and call `setAttribute` for each element.

2023-04-26 09:14 UTC, p2kmgcl commented on modules/apps/segments/segments-simulation-web/src/main/resources/META-INF/resources/js/main.js
> +			const iframe = document.querySelector('#simulationDeviceIframe');
We prefer using `document.getElementById('someId')` instead of `document.querySelectorAll('#someId')`. It is more clear that you are looking for a single element with an id, and also the browser does not need to analyze your selector :3

2023-04-26 09:14 UTC, p2kmgcl commented on modules/apps/segments/segments-simulation-web/src/main/resources/META-INF/resources/js/main.js
> +					iframeWindow.location.reload();
I think we can simplify this and just write `iframe.contentWindow`, it should give you the same object: https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentWindow

2023-04-26 09:14 UTC, p2kmgcl commented on modules/apps/segments/segments-simulation-web/src/main/resources/META-INF/resources/js/main.js
> +			fetchDeactivateSimulation.dispose();
Do these methods exist? I think those are just regular functions, so there is no `.dispose()` method.

2023-04-26 09:14 UTC, p2kmgcl commented on modules/apps/segments/segments-simulation-web/src/main/resources/META-INF/resources/js/main.js
> +	Liferay.on('SimulationMenu:openSimulationPanel', simulateSegmentsEntries);
Wow, I didn't know about `Liferay.detach`, I thought you needed to use the returned object of `Liferay.on`, but it looks like we have both options. Nice! :smile: 

- https://github.com/search?q=repo%3Aliferay%2Fliferay-portal+%3D+Liferay.on%28+language%3AJavaScript&type=code&l=JavaScript
- https://github.com/search?q=repo%3Aliferay%2Fliferay-portal+%3D+Liferay.detach%28+language%3AJavaScript&type=code&l=JavaScript

2023-04-26 18:35 UTC, Stephy6 commented on modules/apps/segments/segments-simulation-web/src/main/resources/META-INF/resources/js/main.js
> +			const iframe = document.querySelector('#simulationDeviceIframe');
I keep using querySelector because the iframe doesn't got any id

2023-04-26 18:35 UTC, Stephy6 commented on modules/apps/segments/segments-simulation-web/src/main/resources/META-INF/resources/js/main.js
> +					iframeWindow.location.reload();
Understood, thank u

2023-04-27 06:48 UTC, p2kmgcl commented
@Stephy6 I am going to have a look :smile:

2023-04-27 07:43 UTC, p2kmgcl commented
Uploaded here: https://github.com/liferay-echo/liferay-portal/pull/11901

2023-04-27 07:43 UTC, closed without merging