LPS-174431 + LPS-174434 Display warnings for site template page friendly URL conflicts
liferay-echo/liferay-portal pull request #11948
Opened 2023-05-03 20:03 UTC by vendeltoreki

Dear Echo Team,

I merged the stories of [LPS-174431](https://issues.liferay.com/browse/LPS-174431) and [LPS-174434](https://issues.liferay.com/browse/LPS-174434) together into one PR, as they modify mostly the same code.

### Motivation

Show more user friendly warnings when pages in the site templates and the sites have the same friendly URLs. With this, users will be able to detect these conflicts early and the site template propagation can be executed correctly.

These stories show 3 different warnings:
* A detailed warning message under the Friendly URL field of the page configuration form.
* A confirm popup when saving a page with a conflicting friendly URL
* A toast popup when a page was saved with a conflicting friendly URL

These warnings are shown when creating or editing a page either on the site template itself ([LPS-174431](https://issues.liferay.com/browse/LPS-174431)), or on the site that was created from it ([LPS-174434](https://issues.liferay.com/browse/LPS-174434)).

### Previous PR

My previous PR, https://github.com/liferay-echo/liferay-portal/pull/11559 was approved from Echo's side, but the QA team has found that some parts of the stories are missing: [LPS-181010](https://issues.liferay.com/browse/LPS-181010), [LPS-181658](https://issues.liferay.com/browse/LPS-181658), [LPS-181011](https://issues.liferay.com/browse/LPS-181011), [LPS-181664](https://issues.liferay.com/browse/LPS-181664). Since fixing these required some extra code and I also had to resolve some code conflicts, I assumed these changes should be reviewed as well.

### The most important changes compared to previous PR

* https://github.com/liferay-echo/liferay-portal/commit/ea2ddc2d59ebdcaefb4c8bb67a78b43c0ad86c30 - Confirm popup added for page creation
* https://github.com/liferay-echo/liferay-portal/commit/bee8961c3801948c6f90b92ac1f01818d28c9ba8 - URL field related code was separated to `url.jsp` by [LPS-179487](https://issues.liferay.com/browse/LPS-179487). Link pointing to the conflicting page's configuration was added in the warning message.

### Feature flags for testing
```
feature.flag.LPS-174431=true
feature.flag.LPS-174434=true
```

Thanks,
Vendel

2023-05-03 20:03 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-05-03 20:03 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-08 07:24 UTC, vendeltoreki commented
**Note:** assigned the PR to technical tasks [LPS-176244](https://issues.liferay.com/browse/LPS-176244) and [LPS-176245](https://issues.liferay.com/browse/LPS-176245) as requested [here](https://issues.liferay.com/browse/LPS-174431?focusedCommentId=2902212&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2902212)

2023-05-09 23:45 UTC, ruben-pulido requested changes
Hi @vendeltoreki

Thanks for the PR. I have reviewed the backend changes and added some comments.

I have also asked for clarification on whether the UI changes should be reviewed by our Design team.

2023-05-09 23:45 UTC, ruben-pulido commented on modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/layout/screen/navigation/entries/general.jsp
> +				var count = response.conflictsCount;
Here we are triggering a call that computes all the layouts that conflict, but since we don't list the conflicting layouts, it would be sufficient to know that one single layout conflicts, which would be a less expensive operation (especially if the number of sites connected to the site template is large).
It probably makes sense to have a hasConflicts method that returns true or false, for improving the performance of the call.

2023-05-09 23:45 UTC, ruben-pulido commented on portal-impl/src/com/liferay/portlet/sites/util/SitesImpl.java
> +		for (LayoutSet layoutSet : layoutSets) {
Here the number of service calls will depend on the number of sites connected to the site template. If this number grows big, the response may slow down. 

An alternative would be to use a DSLQuery following a similar pattern as done here: https://github.com/liferay/liferay-portal/blob/f6d10ea9c662b8d5408636c2805681d249dd0a1a/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L3205-L3223 

Thanks to @lfbesada for pointing this out!

2023-05-10 08:53 UTC, vendeltoreki commented on modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/display/context/LayoutsAdminDisplayContext.java
> +		if (_showConflictLayout != null) {
Hi @ruben-pulido , Thanks for the detailed review!
In this case, I added `_showConflictLayout` to avoid querying this one single layout multiple times in the DisplayContext. If I've only added `_conflictLayout` then this variable being null does not carry the information that it's null because we haven't queried it yet or because we found no conflict (which would be the case like 99% of the time).
However, now looking at the code I could probably simplify it by using only the `_conflictLayouts` list for this as well (template pages can conflict with site pages in multiple sites, but site pages can conflict with only one in the template).
Do you think this would make the code better?

2023-05-10 23:25 UTC, melodywu commented
ci:test:bundle

2023-05-11 12:04 UTC, closed without merging