LPS 183306
liferay-echo/liferay-portal pull request #12288
Opened 2023-06-02 15:23 UTC by Stephy6

- LPS-183306 Remove unused code in ManageCollaborators.scss and use clay guidelines in tsx
- LPS-183306 Remove unused code from _VocabulariesSelection.scss
- LPS-183306 Clean main.scss
- LPS-183306 Clean TreeFilter.scss and use clay guidelines for in js component
- LPS-183306 Remove position property from scss and add it from js or jsp
- LPS-183306 Add position-sticky from js and use clay-guidelines
- LPS-183306 Use clay guidelines

2023-06-02 15:23 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-06-02 15:24 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-05 09:29 UTC, sandrodw3 reviewed
Hey @Stephy6! I left some comments and suggestions 😄 could you please take a look?

And by the way, when I deployed the module, some typescript types were updated, please take a look just in case we have to commit that, thanks!

2023-06-05 09:29 UTC, sandrodw3 commented on modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/css/_ManageCollaborators.scss
>  		box-shadow: 0 0 0 1px $cadmin-gray-300;
Are the classes `collaborator-btn`, `collaborators-owner` and `collaborators-collaborator` actually being used? In that case, maybe we can move the padding and margin rules to utility classes

2023-06-05 09:29 UTC, sandrodw3 commented on modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/css/main.scss
>  html#{$cadmin-selector} {
Could we move the import of `ManageCollaborators` to top in this file?

I also think some rules can be moved to utility classes as well:
- `loading-indicator-wrapper` height
- `content-dashboard-sidebar` bottom and position
- `autofit-col` paddings
- `sidebar-header` top

2023-06-05 09:29 UTC, sandrodw3 commented on modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/css/TreeFilter.scss
>  		align-items: center;
This can be removed by adding `align-items-center` class 😄

2023-06-05 09:29 UTC, sandrodw3 commented on modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/js/components/AuditGraphApp/AuditBarChart.js
>  		<>
Just in case, this commit says "Remove position from scss" but I think you didn't remove it from any file 😛

2023-06-05 09:29 UTC, sandrodw3 commented on modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/js/components/Sidebar.js
>  	const {onClose} = useContext(SidebarContext);
Smae here, should we remove something from scss files?

2023-06-08 13:24 UTC, sandrodw3 commented on modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/css/_VocabulariesSelection.scss
> -	.cadmin {
Yeah as I could see, it has been unapplied for some weeks because of another PR from last month 😂 I removed the file and added the spacing as a class to the loading indicator. I think it was the only relevant style.

2023-06-08 13:25 UTC, sandrodw3 commented on modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/css/main.scss
> -		.content-dashboard-management-toolbar {
🔥

2023-06-08 13:25 UTC, sandrodw3 commented on modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/css/main.scss
> -		.is-sticky {
I restored the previous behavior 😄

2023-06-08 16:25 UTC, claraizquierdo requested changes
Hi @sandrodw3 ,

The sticky part is working again 🎉 

But, I'm afraid that the vocabularies selection modal is broken, or at least is not working in my local:

<img width="1743" alt="Captura de pantalla 2023-06-08 a las 18 21 49" src="https://github.com/liferay-echo/liferay-portal/assets/3276218/9fbb12bf-5e48-46ce-a60f-a0c12b69d70f">

Also, the vocabularies selection styles are needed. I left another comment explaining why :)

2023-06-08 16:25 UTC, claraizquierdo commented on modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/css/_VocabulariesSelection.scss
> -	.cadmin {
Hi @sandrodw3 , I'm afraid that this styles are necessary 😢 . The min-height is to avoid box resizing when there are no elements and the disabled styles are to indicate the user that they can not select two vocabularies from different sites (apart from the Global site).

2023-06-08 17:00 UTC, sandrodw3 commented on modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/css/_VocabulariesSelection.scss
> -	.cadmin {
@claraizquierdo I restored the styles, and left the `cadmin` selector in that CSS file, since it seems that the modal is wrapped in a `cadmin` div (that doesn't depend on us)

2023-06-08 20:25 UTC, claraizquierdo requested changes
Hi again!

Just two details:
- I still see styles being deleted from the VocabulariesSelection.scss that I think might be necessary.
- The Content Performance Panel looks a little bit different. This is the one in master:

![Captura de pantalla 2023-06-08 a las 22 18 25](https://github.com/liferay-echo/liferay-portal/assets/3276218/e5cdc852-da76-46c7-b51c-fa877efd49b3)

And this is your branch:
![Captura de pantalla 2023-06-08 a las 22 21 22](https://github.com/liferay-echo/liferay-portal/assets/3276218/0c63b4a5-c4f3-4c7e-99d5-28e65787b8a5)

2023-06-09 14:22 UTC, sandrodw3 commented
Hey guys @Stephy6 @claraizquierdo I finally decided not to remove cadmin as it seems it has some other implications, and for example the Content Performance panel needs it, as it's displayed also in public pages, so it's better we don't take any risk. Everything should be working fine now, could you please test if I missed something?

Thanks!

2023-06-12 15:00 UTC, claraizquierdo approved these changes
Ei! LGTM!!! 🎉

2023-06-12 15:01 UTC, claraizquierdo commented
ci:forward

2023-06-12 15:01 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-06-12 15:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5142/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5142/jenkins-report.html">here</a>.</b></p>

2023-06-12 15:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f3d45d92df2ec969b7722ba6bf9063873051870">7f3d45d92df2ec969b7722ba6bf9063873051870</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Stephy6/liferay-portal/tree/LPS-183306">LPS-183306</a><br/>Branch GIT ID: <a href="https://github.com/Stephy6/liferay-portal/commit/5148df62bc5b034242084f5e766bccada2da7c91">5148df62bc5b034242084f5e766bccada2da7c91</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5142/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5142/jenkins-report.html">here</a>.</h5><pre>     [exec] Generating types (24 of 34): item-selector-taglib
     [exec] Generating types (25 of 34): journal-web
     [exec] Generating types (26 of 34): layout-admin-web
     [exec] Generating types (27 of 34): @liferay/object-js-components-web
     [exec] Generating types (28 of 34): @liferay/notification-web
     [exec] Generating types (29 of 34): @liferay/oauth2-provider-web
     [exec] Generating types (30 of 34): @liferay/object-dynamic-data-mapping-form-field-type
     [exec] Generating types (31 of 34): @liferay/object-web
     [exec] Generating types (32 of 34): product-navigation-simulation-device
     [exec] Generating types (33 of 34): segments-web
     [exec] Generating types (34 of 34): analytics-reports-web
     [exec] Preflight check failed:
     [exec] checkTypeScriptTypeArtifacts() failed: Error: Type generation was successful but 1 project was out of date. Please commit updated versions of the artifacts in the projects listed above.
     [exec] 
     [exec] Prettier checked 13 files
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2023-06-12 15:09:45.416.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2023-06-12 15:37 UTC, sandrodw3 commented
ci:forward

2023-06-12 15:37 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-06-12 15:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f3d45d92df2ec969b7722ba6bf9063873051870">7f3d45d92df2ec969b7722ba6bf9063873051870</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Stephy6/liferay-portal/tree/LPS-183306">LPS-183306</a><br/>Branch GIT ID: <a href="https://github.com/Stephy6/liferay-portal/commit/6a7eede053579a6475aed5891473e1906531b434">6a7eede053579a6475aed5891473e1906531b434</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1680/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1680/jenkins-report.html">here</a>.</h5></details></html>

2023-06-12 15:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1680/">test-portal-source-format#1680</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1680/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/12288">liferay-echo#12288</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2348072653">[master] ci:test:sf - Stephy6 &gt; liferay-echo - PR#12288 - 2023-06-12[08:37:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/5925/">publish-testray-report#5925</a><br/></div></div>

2023-06-12 16:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/8374/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8374/jenkins-report.html">here</a>.</b></p>

2023-06-12 16:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f3d45d92df2ec969b7722ba6bf9063873051870">7f3d45d92df2ec969b7722ba6bf9063873051870</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f3d4a0ca4e47c4bd7df0c3078e066be69b59d985">f3d4a0ca4e47c4bd7df0c3078e066be69b59d985</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2348035295">EE Development Acceptance (master) - 4604 - 2023-06-12[04:38:43]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/8374/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8374/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/8374/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The sender branch SHA could not be found on <strong><a href="https://github.com/liferay-echo/liferay-portal/pull/12288">Stephy6/LPS-183306</a></strong>. The sender branch may have been force pushed or deleted after the pull request test was initiated.</p><pre>fatal: Not a valid branch point: '5148df62bc5b034242084f5e766bccada2da7c91'.</pre></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-06-12 16:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6698/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6698/jenkins-report.html">here</a>.</b></p>

2023-06-12 21:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 30 out of 30 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 61 out of 62 jobs passed in 5 hours 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f3d45d92df2ec969b7722ba6bf9063873051870">7f3d45d92df2ec969b7722ba6bf9063873051870</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f3d45d92df2ec969b7722ba6bf9063873051870">7f3d45d92df2ec969b7722ba6bf9063873051870</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2348145731">EE Development Acceptance (master) - 4605 - 2023-06-12[08:36:51]</a></p><details><summary><strong>ci:test:stable - 30 out of 30 jobs PASSED</strong></summary><details><summary><strong>30 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 60 out of 62 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6698/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209514/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/424500/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/230589/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/582133/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207749/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/582131/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/230485/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/424501/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/219472/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/219473/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/580806/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/178532/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/432584/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209518/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221079/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/675031/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/648679/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/424499/">functional-upgrade-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/556011/">functional-upgrade-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147860/">functional-upgrade-tomcat90-mysql57-jdk8/0/6</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218689/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/212629/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147859/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/210756/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li></ul></li><li>functional-upgrade-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/529760/">functional-upgrade-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519896/">js-unit-jdk8/0/0</a></li></ul></li><li>lpkg-controller-mysql57-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221078/">lpkg-controller-mysql57-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209873/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/529756/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/556007/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/230484/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205661/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/178533/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/424497/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/648677/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/219474/">modules-compile-jdk8/0/8</a></ [...]

2023-06-12 22:01 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6698//consoleFull)

2023-06-12 22:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6698/">test-portal-acceptance-pullrequest(master)#6698</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6698/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/12288">liferay-echo#12288</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2348367051">[master] ci:test:relevant - Stephy6 &gt; liferay-echo - PR#12288 - 2023-06-12[09:52:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/15311/">publish-testray-report#15311</a><br/></div></div>

2023-06-12 22:04 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6698//consoleFull)

2023-06-12 22:07 UTC, liferay-continuous-integration commented
Error has occurred while forwarding pull request to `brianchandotcom`.
Please try again later or contact the CI team for assistance.
See console log for details: [Full Console](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6698//consoleFullconsoleText)

2023-06-13 02:23 UTC, liulukiwi commented
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/136220

2023-06-13 02:23 UTC, liulukiwi commented
ci:close

2023-06-13 02:23 UTC, closed without merging