LPS-174431 Site template friendly URL conflict warning front-end
liferay-echo/liferay-portal pull request #12503
Opened 2023-06-19 13:51 UTC by vendeltoreki

Dear @liferay-echo ,

As discussed on https://github.com/vendeltoreki/liferay-portal/pull/253 , I'm sending the rebased front-end related changes.

Please review the changes.

Thanks,
Vendel

cc: @ealonso

2023-06-19 13:51 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-06-19 13:51 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-20 06:49 UTC, p2kmgcl requested changes
Hey @vendeltoreki! I just reviewed the frontend part and add some comments. We need to ways for Lourdes to review the backend, but you can start applying some changes to the front if you want to :smile:

2023-06-20 06:49 UTC, p2kmgcl commented on modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/js/AddLayout.js
> +	Liferay.Util.fetch(url.toString())
No need to use `Liferay.Util.fetch` here, we can use the `fetch` dependency imported from frontend-js-web :smile: 

Also, I think we do not need to convert the URL object to string, fetch should accept URL objects too: https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters

2023-06-20 06:49 UTC, p2kmgcl commented on modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/js/AddLayout.js
> +			Liferay.Util.openConfirmModal({
I think we can import this function from `frontend-js-web`.

As a rule of thumb, we tend to prefer imports over global dependencies, so we can track which modules are using which functions more easily, and potentially cleaning up the global namespace in the future :crossed_fingers:

2023-06-20 06:49 UTC, p2kmgcl commented on modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/js/AddLayout.js
> +			submitForm(addButton, form);
To make this easier to follow, I think we should wait for this to be completed and re-enable the `addButton` here instead of passing it to other functions. That way we have all "disabled" updates in the same scope, and we do not have to dive through the code to check where the button is enabled or disabled. What do you think about that?

2023-06-20 06:49 UTC, p2kmgcl commented on modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/layout/screen/navigation/entries/general.jsp
> +	function <portlet:namespace />checkApplyLayoutPrototype() {
I think we should move this to a JS file too, we are trying to have no JS in JSP files.

2023-06-20 06:49 UTC, p2kmgcl commented on modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/layout/url.jsp
> +		<aui:script>
Same here, I am not sure if we want to inject these small scripts inside the JSP instead of having a single JS with all the code.

2023-06-20 08:27 UTC, p2kmgcl commented
I am going to apply the changes I suggested! :smile:

2023-06-20 10:46 UTC, vendeltoreki commented
Thanks, @p2kmgcl

My front-end knowledge is quite limited, but I did my best to copy-paste random codes from other parts of the portal😅

2023-06-21 08:05 UTC, lfbesada commented
Hi @vendeltoreki 
Thanks for the PR!
Please, can you clarify the functionality that is intended with this PR?
From the requirements, I understand that the warning is intended to appear only in the site templates. But this PR also puts warnings on the child sites. Is it intentional?
Thank you very much!
Regards

2023-06-21 08:26 UTC, vendeltoreki commented
Hi @lfbesada ,

Yes, since [LPS-174431](https://liferay.atlassian.net/browse/LPS-174431) and [LPS-174434](https://liferay.atlassian.net/browse/LPS-174434) modify almost exactly the same code, I merged them into one PR. Otherwise, there would have been way more code conflicts to resolve.
[LPS-174431](https://liferay.atlassian.net/browse/LPS-174431) shows warnings on the template's side, while [LPS-174434](https://liferay.atlassian.net/browse/LPS-174434) is supposed to do almost the same on the site's pages.
It was done the same way for [LPS-174471](https://liferay.atlassian.net/browse/LPS-174471) and [LPS-174465](https://liferay.atlassian.net/browse/LPS-174465). Those display warnings on the page tree.

> Hi @vendeltoreki Thanks for the PR! Please, can you clarify the functionality that is intended with this PR? From the requirements, I understand that the warning is intended to appear only in the site templates. But this PR also puts warnings on the child sites. Is it intentional? Thank you very much! Regards

2023-06-21 09:32 UTC, lfbesada commented
Hi @vendeltoreki 
Thanks for the explanation, it has been very useful.
The weird behavior that I see seems to me to correspond to the AC-2 case of https://liferay.atlassian.net/browse/LPS-174434. From my point of view, this warning does not make sense because that page can never be saved, that if that URL exists in the site template, it must necessarily also exist in the site, since it is linked, and therefore it will always be a duplicate URL in the own site.
I am adding some changes to your PR, should I revert the warning in this case? Please, watch the video with my steps, maybe I am doing something wrong.

https://github.com/liferay-echo/liferay-portal/assets/84471361/26002090-1989-4efb-a5ee-63bdbc77d6c6

On the other hand, could you please solve the rebase conflict?

Thanks in advance!

2023-06-21 09:46 UTC, lfbesada commented
@vendeltoreki Analyzing the other cases in https://liferay.atlassian.net/browse/LPS-174434 I think that the warnings in the child sites only make sense if they are **not connected** to their site template since, if they are connected, those cases would be duplicate URLs on the site. But according to the requirements, they must appear on sites connected to their templates.
Please, could you tell me who I should contact to clarify the desired functionality?
Thank you very much

2023-06-21 10:49 UTC, vendeltoreki commented
Hi @lfbesada ,

I think the reason is that there are some ways to stop the propagation from happening:
* Site Template's menu ==> Configuration ==> Site Template Settings ==> turn off "Ready for Propagation"
* Site's menu ==> Configuration ==> Site Settings ==> Pages ==> Pages ==> turn off "Enable propagation of changes from the site template temp1."
* The portal also can be overloaded with propagations, so even if the connection between the template and the page is active, it does not happen possibly even for hours.

My guess is that AC-2 specifically prepares for these scenarios, preventing conflicts even if the site not completely up to date with the template.

@laszlopap , can you please confirm?

2023-06-21 11:03 UTC, lfbesada commented
Hi @vendeltoreki Thanks for the explanation, I understand then that these cases can occur if the propagation is manual.
But I still don't see the point of showing a warning about a field to the user and then showing an error when saving on the same field.
Have you considered checking if the URL is duplicated in the site before checking if it will be duplicated in the site template?
Perhaps we could do that validation first and display a different message in that case.
What do you think?

2023-06-21 11:31 UTC, vendeltoreki commented
Well, yeah.. I agree that the toast pop-up message is a bit excessive. However, that was in the AC that was accepted by the product owners ( @zsigmondrab and @laszlopap ).
About checking the page friendly conflicts inside a site: this one is currently solved by automatically appending a number to the friendly URL. E.g.: if you create two pages called "TestPage", the first URL will be "/testpage" and the other "/testpage1". This is a bit out of the scope of the current stories, but it's possible to solve it that way. Although, it would change the current behavior, so that would be completely new feature.

2023-06-21 11:50 UTC, lfbesada commented
@vendeltoreki The automatically appending a number to the friendly URL only occurs when creating a new layout. In this case, the friendly URL is built from its name. But when editing the configuration a duplicate URL prevents from saving the configuration. You can see that happening in the lastest seconds of the upper comment video.

2023-06-21 12:07 UTC, vendeltoreki commented
@lfbesada Yes, that makes sense. We could check the conflict inside the site first and then with the template. However, the validation only fails after the form is submitted, while the site template conflict should be a dismissible warning message, so it's called right before the submit.
I don't know what would be technically the better solution, because when we call the site template conflict check, we don't know yet whether the intra-site check will fail. We could possibly detect it beforehand and let the site template check pass if we know that the intra-site validation will fail for sure. That way, the order of errors would change: first show the intra-site validation failure and then show the site template check warning.

2023-06-21 13:21 UTC, vendeltoreki commented
Hi @p2kmgcl ,

I see there's a conflict on `modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/layout/url.jsp`. Should I still resolve it or have you already started working on the changes?

2023-06-21 13:32 UTC, lfbesada commented
Hi @vendeltoreki Don't worry we are going to send another pull request, so there is not necessary to update this one. I will keep this open until we send it. Regards

2023-06-21 14:16 UTC, lfbesada commented
Hi @vendeltoreki 
I am sorry to bother you again but another question has arisen with the functionality 😅 and I think that history does not define anything about it.
I see that in your PR only the default friendly URL of the layout is validated, never its translations. Is it intentional? Do we ignore the duplication of URLs in locations?
Thanks in advance!

2023-06-21 15:24 UTC, vendeltoreki commented
@lfbesada We don't check for translations intentionally, only the default URL. Since this is what causes the propagation to fail. When there's a conflict in a translation, then the URL is suffixed with a number.

2023-06-26 06:44 UTC, lfbesada commented
Hi @vendeltoreki 
Thanks for your patience!
@p2kmgcl and I made a different development.
I am sorry not to pick your commits but we made so different development that we couldn't take them.
Please see: https://github.com/liferay-echo/liferay-portal/pull/12580
Regards

2023-06-26 06:44 UTC, closed without merging