LPS-180014, LPS-180015, LPS-189148 Add test to get structured content inside moved folder from asset library on structured contents versions page
liferay-echo/liferay-portal pull request #12678
Opened 2023-07-03 12:00 UTC by Tim-Cao

https://liferay.atlassian.net/browse/LPS-180014
https://liferay.atlassian.net/browse/LPS-180015
https://liferay.atlassian.net/browse/LPS-189148

2023-07-03 12:00 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-07-03 12:00 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-07-03 12:00 UTC, Tim-Cao commented
ci:test:sf

2023-07-03 12:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/6323/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6323/jenkins-report.html">here</a>.</b></p>

2023-07-03 12:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fa3c03c82c4ebcf7651b409fc03d947619ad9743">fa3c03c82c4ebcf7651b409fc03d947619ad9743</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Tim-Cao/liferay-portal/tree/master-qa-180014">master-qa-180014</a><br/>Branch GIT ID: <a href="https://github.com/Tim-Cao/liferay-portal/commit/4947698f1b77181319199ee028bbcdda8650a844">4947698f1b77181319199ee028bbcdda8650a844</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6323/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6323/jenkins-report.html">here</a>.</h5></details></html>

2023-07-03 12:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6323/">test-portal-source-format#6323</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6323/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/12678">liferay-echo#12678</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2369402391">[master] ci:test:sf - Tim-Cao &gt; liferay-echo - PR#12678 - 2023-07-03[05:05:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/3537/">publish-testray-report#3537</a><br/></div></div>

2023-07-05 07:23 UTC, lfbesada requested changes
Hi @Tim-Cao 
Great job 👏 You will be very welcome to the backend side 🤩 
I have added just minor suggestions.
Thank you for working on it ❤️

2023-07-05 07:23 UTC, lfbesada commented on modules/apps/headless/headless-admin-content/headless-admin-content-test/src/testIntegration/java/com/liferay/headless/admin/content/resource/v1_0/test/StructuredContentResourceTest.java
> +		_testDepotEntry = DepotEntryLocalServiceUtil.addDepotEntry(
I think that here we could use an injected service reference instead of the Util, what do you think?

2023-07-05 07:23 UTC, lfbesada commented on modules/apps/headless/headless-admin-content/headless-admin-content-test/src/testIntegration/java/com/liferay/headless/admin/content/resource/v1_0/test/StructuredContentResourceTest.java
> +		assertValid(structuredContentsVersionsPage);
I think that here you should define a variable for structuredContentsVersionsPage.fetchFirstItem() and sort this asserts to something like this:

`

		Assert.assertEquals(1L, structuredContentsVersionsPage.getTotalCount());
		assertValid(structuredContentsVersionsPage);

		StructuredContent structuredContent =
			structuredContentsVersionsPage.fetchFirstItem();

		Assert.assertEquals(
			journalFolder3.getFolderId(),
			GetterUtil.getLong(
				structuredContent.getStructuredContentFolderId()));
`

2023-07-05 07:23 UTC, lfbesada commented on modules/apps/headless/headless-admin-content/headless-admin-content-test/src/testIntegration/java/com/liferay/headless/admin/content/resource/v1_0/test/StructuredContentResourceTest.java
> +		assertValid(structuredContentsVersionsPage);
Same as the previous comment

2023-07-05 07:55 UTC, Tim-Cao commented
ci:test:sf

2023-07-05 07:57 UTC, lfbesada approved these changes
LGTM 🎉

2023-07-05 07:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/3348/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3348/jenkins-report.html">here</a>.</b></p>

2023-07-05 08:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b284fab03762bc817e5cf76e8a94f4589278e593">b284fab03762bc817e5cf76e8a94f4589278e593</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Tim-Cao/liferay-portal/tree/master-qa-180014">master-qa-180014</a><br/>Branch GIT ID: <a href="https://github.com/Tim-Cao/liferay-portal/commit/d26b5fd5a4a727121287b720d866446196f55176">d26b5fd5a4a727121287b720d866446196f55176</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3348/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3348/jenkins-report.html">here</a>.</h5></details></html>

2023-07-05 08:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3348/">test-portal-source-format#3348</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3348/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/12678">liferay-echo#12678</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2371329121">[master] ci:test:sf - Tim-Cao &gt; liferay-echo - PR#12678 - 2023-07-05[00:55:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/12131/">publish-testray-report#12131</a><br/></div></div>

2023-07-05 08:07 UTC, lfbesada commented
ci:forward

2023-07-05 08:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-07-05 08:07 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2023-07-05 08:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/12952/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12952/jenkins-report.html">here</a>.</b></p>

2023-07-05 12:15 UTC, lfbesada commented
ci:stable

2023-07-05 12:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/12952/">test-portal-acceptance-pullrequest(master)#12952</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12952/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/12678">liferay-echo#12678</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2371489375">[master] ci:test:relevant - Tim-Cao &gt; liferay-echo - PR#12678 - 2023-07-05[01:21:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/28123/">publish-testray-report#28123</a><br/></div></div>

2023-07-05 13:04 UTC, Tim-Cao commented
See https://github.com/brianchandotcom/liferay-portal/pull/137402

2023-07-05 13:04 UTC, closed without merging