LPS-166461 - Automation guest view permission
liferay-echo/liferay-portal pull request #12901
Opened 2023-07-18 15:01 UTC by marcosvictor22

@david-gutierrez-mesa

2023-07-18 15:01 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-07-18 15:01 UTC, marcosvictor22 commented
ci:test:sf

2023-07-18 15:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/6285/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6285/jenkins-report.html">here</a>.</b></p>

2023-07-18 15:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e14870250c24bcbdb5f04c1d22050822e984dbc2">e14870250c24bcbdb5f04c1d22050822e984dbc2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marcosvictor22/liferay-portal/tree/LPS-166461">LPS-166461</a><br/>Branch GIT ID: <a href="https://github.com/marcosvictor22/liferay-portal/commit/28fc985d69b2a29946be3963ee91a5eaaf1c6e6f">28fc985d69b2a29946be3963ee91a5eaaf1c6e6f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6285/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6285/jenkins-report.html">here</a>.</h5></details></html>

2023-07-18 15:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6285/">test-portal-source-format#6285</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6285/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/12901">liferay-echo#12901</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2386071246">[master] ci:test:sf - marcosvictor22 &gt; liferay-echo - PR#12901 - 2023-07-18[08:02:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/24113/">publish-testray-report#24113</a><br/></div></div>

2023-07-19 21:53 UTC, Tim-Cao requested changes
Hi @marcosvictor22, could you refactor according to comments? Thanks

2023-07-19 21:53 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagestree/PagesTree.testcase
> +	test ViewForTheUserToFindThePage {
Rename to ViewContentPageShownInSearchResultsAfterRemoveViewPermissionForGuest
Move the case to ContentPagesWithSearch.testcase

2023-07-19 21:53 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagestree/PagesTree.testcase
> +	@description = "This is a test for LPS-166461. There is view permission for the guest"
Use bug ticket number LPS-163785

2023-07-19 21:53 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagestree/PagesTree.testcase
> +				layoutName = "Test Page Name");
Use PageEditor.publish();

2023-07-19 21:53 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagestree/PagesTree.testcase
> +		}
No need

2023-07-19 21:53 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagestree/PagesTree.testcase
> +			PagesAdmin.openPagesAdmin(siteURLKey = ${siteURLKey});
Navigate to the Search page

2023-07-20 13:12 UTC, marcosvictor22 commented
@Tim-Cao echo repository needs to be updated

2023-07-20 23:04 UTC, Tim-Cao commented
Hi @marcosvictor22, could you double check if the changes you made are pushed?

2023-07-21 07:58 UTC, marcosvictor22 commented
I made the changes, but it didn't send, how strange... @Tim-Cao I'll do it again

2023-07-24 09:07 UTC, Tim-Cao commented
See changes @marcosvictor22 https://github.com/liferay-echo/liferay-portal/pull/12981

2023-07-24 09:07 UTC, Tim-Cao commented
ci:close

2023-07-24 09:07 UTC, closed without merging