LPS-175478
liferay-echo/liferay-portal pull request #13088
Opened 2023-07-31 13:14 UTC by marcosvictor22

2023-07-31 13:14 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-07-31 13:14 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-07-31 13:15 UTC, marcosvictor22 commented
ci:test:sf

2023-07-31 13:15 UTC, marcosvictor22 commented
@david-gutierrez-mesa @Tim-Cao

2023-07-31 13:23 UTC, marcosvictor22 commented
ci:test:sf

2023-07-31 13:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6407/">test-portal-source-format#6407</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6407/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13088">liferay-echo#13088</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2397285308">[master] ci:test:sf - marcosvictor22 &gt; liferay-echo - PR#13088 - 2023-07-31[06:16:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/24618/">publish-testray-report#24618</a><br/></div></div>

2023-07-31 13:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/7103/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7103/jenkins-report.html">here</a>.</b></p>

2023-07-31 13:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e3f2d6fab9527fd6b7ed250d3ca110930e49fa00">e3f2d6fab9527fd6b7ed250d3ca110930e49fa00</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marcosvictor22/liferay-portal/tree/LPS-175478">LPS-175478</a><br/>Branch GIT ID: <a href="https://github.com/marcosvictor22/liferay-portal/commit/26c4d367c0d1baae11145a26fb620c17dbf46184">26c4d367c0d1baae11145a26fb620c17dbf46184</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/7103/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7103/jenkins-report.html">here</a>.</h5></details></html>

2023-07-31 13:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/7103/">test-portal-source-format#7103</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7103/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13088">liferay-echo#13088</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2397285692">[master] ci:test:sf - marcosvictor22 &gt; liferay-echo - PR#13088 - 2023-07-31[06:23:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/3300/">publish-testray-report#3300</a><br/></div></div>

2023-08-02 08:54 UTC, Tim-Cao requested changes
Hi @marcosvictor22, there are some suggestions when you write automation.

1. Manual Testing follows the steps in bug ticket.
2. Make sure you fully understand the testing point.
3. Run test after write the automation.

2023-08-02 08:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +			Staging.activateStagingCP(siteName = "Test Site Name");
No need

2023-08-02 08:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +				title = "Web Content Title 1");
No need

2023-08-02 08:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +				siteName = "Test Site Name");
```
			JSONLayout.addPublicLayout(
				groupName = "${randomSiteName} (Staging)",
				layoutName = "Test Page Name",
				site = "false",
				type = "content");
				

			ContentPagesNavigator.openEditContentPage(
				pageName = "Test Page Name",
				siteName = "${randomSiteName} Staging");

			PageEditor.addWidget(portletName = "Web Content Display");

		PageEditor.addWidget(
			portletName = "Web Content Display",
			targetFragmentName = "Asset Publisher");
				
```

2023-08-02 08:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +				scope = "Global");
Should be these steps

8. Configure the Web Content Display widget to have the Global Scope (under the "Scope" tab), then configure it to display the "Global Article" from step 2. Click Save.
9. Beneath the Web Content Display widget, add an Asset Publisher widget.
10. Configure the Asset Publisher widget as follows:

Asset Selection: Manual

Scope: Click "Select", then "Global". The Scope should now be showing as "Current Site (Test Site)" + "Global"

Asset Entries: Basic Web Content > Site Article.

Save

2023-08-02 08:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +	}
Miss steps please check the ticket https://liferay.atlassian.net/browse/LPS-153676

2023-08-03 21:23 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +				scope = "Global");
Hi @marcosvictor22, could you have a look at this comment?

2023-08-03 21:24 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +	}
Also this one @marcosvictor22

2023-08-15 12:18 UTC, Tim-Cao commented
See changes @marcosvictor22
https://github.com/liferay-echo/liferay-portal/pull/13283

2023-08-15 12:18 UTC, Tim-Cao commented
ci:close

2023-08-15 12:18 UTC, closed without merging