LPS-189023
liferay-echo/liferay-portal pull request #13110
Opened 2023-08-01 19:05 UTC by rafaellajordao

2023-08-01 19:05 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-08-01 19:05 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-08-01 19:05 UTC, rafaellajordao commented
ci:test:sf

2023-08-01 19:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/4575/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4575/jenkins-report.html">here</a>.</b></p>

2023-08-01 19:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f63af3907491f652f2c1eed4216b63825f26b1fc">f63af3907491f652f2c1eed4216b63825f26b1fc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-189023">LPS-189023</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/e9c2a17a51a014dee53161c1c5f9208da6315c32">e9c2a17a51a014dee53161c1c5f9208da6315c32</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4575/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4575/jenkins-report.html">here</a>.</h5></details></html>

2023-08-02 09:25 UTC, Tim-Cao requested changes
Hi @rafaellajordao, would you mind modifing according to comments? Thanks

2023-08-02 09:25 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/fragment/FragmentsConfiguration.testcase
> +		}
Should be Menu Display widget on header

2023-08-02 09:25 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/fragment/FragmentsConfiguration.testcase
> +	test CanConfigureSerachAndMenuDisplayWidgets {
ConfigureMenuDisplayWidget

2023-08-02 09:25 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/fragment/FragmentsConfiguration.testcase
> +	@description = "This is a test for LPS-188364. Unable to configure header search bar or menu display on content pages."
The user is able to configure Menu Display on content page. Migrate to the NavigationMenuWidgets.testcase

2023-08-02 09:25 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/fragment/FragmentsConfiguration.testcase
> +				siteName = "Test Site Name");
Add a site based on Welcome then navigate to the Home page

2023-08-02 09:25 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/fragment/FragmentsConfiguration.testcase
> +		}
Should be search bar widget on header but Menu Display is already enough

2023-08-02 09:25 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/fragment/FragmentsConfiguration.testcase
> +	}
Then add steps like
NavigationMenusWidget.gotoNavigationMenuWidgetConfig();
Make some changes

2023-08-03 15:39 UTC, rafaellajordao commented
Hi @Tim-Cao !
I couldn't add the Menu Display directly to the predefined Home Page, if it's incorrect can you show me how I can do it? :)

2023-08-03 15:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5586/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5586/jenkins-report.html">here</a>.</b></p>

2023-08-03 15:48 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/954090a52a6957a290f2ca59aa0964af4282ba88">954090a52a6957a290f2ca59aa0964af4282ba88</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-189023">LPS-189023</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/2ba4a7c26e6ce50feb5ce01c22049abfee9b383e">2ba4a7c26e6ce50feb5ce01c22049abfee9b383e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5586/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5586/jenkins-report.html">here</a>.</h5></details></html>

2023-08-03 15:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5586/">test-portal-source-format#5586</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5586/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13110">liferay-echo#13110</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2399562015">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#13110 - 2023-08-03[08:39:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/21026/">publish-testray-report#21026</a><br/></div></div>

2023-08-03 20:46 UTC, Tim-Cao commented
Hi @rafaellajordao, Yes, we don't need to add it. Just use the OOTB one on page.

2023-08-03 20:48 UTC, Tim-Cao requested changes

2023-08-03 20:48 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/sitenavigation/navigationmenu/NavigationMenuWidget.testcase
> +			MastersPageTemplatesAdmin.gotoMasters(masterLayoutName = "Masters Page Template");
Add a site based on Welcome

2023-08-03 20:48 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/sitenavigation/navigationmenu/NavigationMenuWidget.testcase
> +				scope = "Master");
When the user accesses to the Home page

2023-08-07 15:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1228/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1228/jenkins-report.html">here</a>.</b></p>

2023-08-07 15:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/43a8fc59fac7ddba761602493e22d04eec7b94d4">43a8fc59fac7ddba761602493e22d04eec7b94d4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-189023">LPS-189023</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/f90dfcd2c7318031674d1feb11884ad3501e9dbe">f90dfcd2c7318031674d1feb11884ad3501e9dbe</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1228/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1228/jenkins-report.html">here</a>.</h5></details></html>

2023-08-08 22:08 UTC, Tim-Cao commented
See changes @rafaellajordao
https://github.com/liferay-echo/liferay-portal/pull/13203

2023-08-08 22:08 UTC, Tim-Cao commented
cI:close

2023-08-08 22:08 UTC, Tim-Cao commented
ci:close

2023-08-08 22:08 UTC, closed without merging