LPS-187449
liferay-echo/liferay-portal pull request #13306
Opened 2023-08-16 16:00 UTC by marcosvictor22

2023-08-16 16:01 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-08-16 16:02 UTC, marcosvictor22 commented
@david-gutierrez-mesa

2023-08-16 16:02 UTC, marcosvictor22 commented
ci:test:sf

2023-08-16 16:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/1734/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1734/jenkins-report.html">here</a>.</b></p>

2023-08-22 08:13 UTC, Tim-Cao requested changes
Hi @marcosvictor22 , Could you refactor according to comments? Thanks

2023-08-22 08:13 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/portalconfiguration/systemmanagement/VirtualInstances.testcase
> +		}
Missing the assertion step
Canonical URL is http://www.able.com:8080

2023-08-22 08:13 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/portalconfiguration/systemmanagement/VirtualInstances.testcase
> +			PagesAdmin.addPage(pageName = "Web Content Page");
Create a content page then publish

2023-08-28 07:30 UTC, Tim-Cao requested changes
Hi @marcosvictor22, please refactor according to comments. Thanks!

2023-08-28 07:30 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentperformance/ContentPerformance.testcase
> +                webId = "www.able.com");
Use headless macro to create virtual instance
```
	HeadlessPortalInstanceAPI.addPortalInstance(
		domain = "www.able.com",
		portalInstanceId = "www.able.com",
		virtualHost = "www.able.com");
```

2023-09-06 10:48 UTC, ealonso commented
Hey @marcosvictor22,

Please add the feedback added by @Tim-Cao and resend

2023-09-06 10:48 UTC, closed without merging