LPS-175477| Automation - ViewWebContentDisplayedOnThePage test
liferay-echo/liferay-portal pull request #13335
Opened 2023-08-18 14:09 UTC by pedroamarall

cc:@manoelcyreno
Issues: [LPS-175477](https://liferay.atlassian.net/browse/LPS-175477)

2023-08-18 14:09 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-08-18 14:09 UTC, pedroamarall commented
ci:test:sf

2023-08-18 14:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/836f264e236073ac2de28d5d3632884f21f4dca9">836f264e236073ac2de28d5d3632884f21f4dca9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedroamarall/liferay-portal/tree/LPS-175477">LPS-175477</a><br/>Branch GIT ID: <a href="https://github.com/pedroamarall/liferay-portal/commit/a90ca1885d07c0fcb96eeee3a512248f076ef22e">a90ca1885d07c0fcb96eeee3a512248f076ef22e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6497/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6497/jenkins-report.html">here</a>.</h5></details></html>

2023-08-18 14:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6497/">test-portal-source-format#6497</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6497/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13335">liferay-echo#13335</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2408771443">[master] ci:test:sf - pedroamarall &gt; liferay-echo - PR#13335 - 2023-08-18[07:10:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/3727/">publish-testray-report#3727</a><br/></div></div>

2023-08-22 08:05 UTC, Tim-Cao requested changes
Hi @pedroamarall, could you double check the test points and steps on https://liferay.atlassian.net/browse/LPS-159512
Then refactor case? Thanks

2023-08-22 08:05 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +	@description = "This is a test for LPS-175477. The user could view associated display page from of web content related."
Use bug ticket number LPS-159512

2023-08-22 08:05 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +		task ("Given: Add two Public Pages and Add an Asset Publisher to each page") {
Given the user displays a web content on a widget page

2023-08-22 08:05 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +			for (var i : list "1,2") {
Add a site based on Welcome site initializer

2023-08-22 08:05 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +		}
No need

2023-08-22 08:05 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +		}
No need

2023-08-22 08:05 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +		}
No need

2023-08-22 09:28 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +		}
Hey @Tim-Cao, thanks for feedback, but I think is necessary because we need to do some steps before to reproduce this automation, Can you check this ticket please and see the description below. I believe it was not being reproduced before because it was too old, and now it needs some necessary and expected steps before finalizing, you know

2023-08-22 09:29 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +		}
[LPS-190308](https://liferay.atlassian.net/browse/LPS-190308)

2023-08-22 09:33 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +		}
Set as the Default Asset Publisher for This Page is designed as expected. I will need to add steps in automation 
Sorry about that, I will edit the steps of this automation

2023-08-22 10:10 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +		}
Steps Updated in Here : [LPS-159512](https://liferay.atlassian.net/browse/LPS-159512)

2023-08-23 14:38 UTC, Tim-Cao requested changes
Comments Updated

2023-08-30 11:33 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +	@description = "This is a test for LPS-175477. The user could view associated display page from of web content related."
Done!

2023-08-30 11:35 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +					widgetName = "Asset Publisher");
Follow in [here](https://github.com/liferay-echo/liferay-portal/pull/13335#discussion_r1301344080) please

2023-08-30 11:37 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +		}
I needed to add two pages so that at the end of the test, I could verify that it will be selected when searching for the assert Published

2023-08-30 11:37 UTC, pedroamarall commented
ci:test:sf

2023-08-30 11:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/6235/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6235/jenkins-report.html">here</a>.</b></p>

2023-08-30 11:43 UTC, pedroamarall commented
ci:test:echo

2023-08-30 11:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6235/">test-portal-source-format#6235</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6235/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13335">liferay-echo#13335</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2415454711">[master] ci:test:sf - pedroamarall &gt; liferay-echo - PR#13335 - 2023-08-30[04:38:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/3865/">publish-testray-report#3865</a><br/></div></div>

2023-08-30 13:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>echo</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/7500/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7500/jenkins-report.html">here</a>.</b></p>

2023-08-30 20:45 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:echo - 698 out of 881 jobs passed in 6 hours 46 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a9d3e38b2954b84dbd558085fce644ba149cd635">a9d3e38b2954b84dbd558085fce644ba149cd635</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a9d3e38b2954b84dbd558085fce644ba149cd635">a9d3e38b2954b84dbd558085fce644ba149cd635</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2415433322">EE Development Acceptance (master) - 4783 - 2023-08-30[00:42:04]</a></p><details><summary><strong>ci:test:echo - 698 out of 881 jobs PASSED</strong></summary><div><h4>183 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/7500/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/262427/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/740956/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/716237/"><strike>functional-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694959/"><strike>functional-tomcat90-mysql57-jdk8/1/1</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/716240/"><strike>functional-tomcat90-mysql57-jdk8/1/2</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629645/"><strike>functional-tomcat90-mysql57-jdk8/1/3</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/716238/"><strike>functional-tomcat90-mysql57-jdk8/1/4</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694961/"><strike>functional-tomcat90-mysql57-jdk8/1/5</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694963/"><strike>functional-tomcat90-mysql57-jdk8/1/6</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/716241/"><strike>functional-tomcat90-mysql57-jdk8/1/7</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629646/"><strike>functional-tomcat90-mysql57-jdk8/1/8</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694962/"><strike>functional-tomcat90-mysql57-jdk8/1/9</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694980/"><strike>functional-tomcat90-mysql57-jdk8/1/10</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629663/"><strike>functional-tomcat90-mysql57-jdk8/1/11</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/709393/"><strike>functional-tomcat90-mysql57-jdk8/1/12</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/716264/"><strike>functional-tomcat90-mysql57-jdk8/1/13</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694983/"><strike>functional-tomcat90-mysql57-jdk8/1/14</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629666/"><strike>functional-tomcat90-mysql57-jdk8/1/15</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629667/"><strike>functional-tomcat90-mysql57-jdk8/1/16</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694205/"><strike>functional-tomcat90-mysql57-jdk8/1/17</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314635/"><strike>functional-tomcat90-mysql57-jdk8/1/18</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/298592/"><strike>functional-tomcat90-mysql57-jdk8/1/19</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694976/"><strike>functional-tomcat90-mysql57-jdk8/1/20</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629661/"><strike>functional-tomcat90-mysql57-jdk8/1/21</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/716261/"><strike>functional-tomcat90-mysql57-jdk8/1/22</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618957/"><strike>functional-tomcat90-mysql57-jdk8/1/23</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694979/"><strike>functional-tomcat90-mysql57-jdk8/1/24</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788902/"><strike>functional-tomcat90-mysql57-jdk8/2/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/740969/"><strike>functional-tomcat90-mysql57-jdk8/2/1</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/816143/"><strike>functional-tomcat90-mysql57-jdk8/2/2</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788905/"><strike>functional-tomcat90-mysql57-jdk8/2/3</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/816142/"><strike>functional-tomcat90-mysql57-jdk8/2/4</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/567891/"><strike>functional-tomcat90-mysql57-jdk8/2/5</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/298597/"><strike>functional-tomcat90-mysql57-jdk8/2/6</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788906/"><strike>functional-tomcat90-mysql57-jdk8/2/7</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/709400/"><strike>functional-tomcat90-mysql57-jdk8/2/8</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/647401/"><strike>functional-tomcat90-mysql57-jdk8/2/9</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/716253/"><strike>functional-tomcat90-mysql57-jdk8/2/10</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/693878/"><strike>functional-tomcat90-mysql57-jdk8/2/11</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/556563/"><strike>functional-tomcat90-mysql57-jdk8/2/12</str [...]

2023-08-30 21:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/7500/">test-portal-acceptance-pullrequest(master)#7500</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7500/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>echo<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13335">liferay-echo#13335</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2415859359">[master] ci:test:echo - pedroamarall &gt; liferay-echo - PR#13335 - 2023-08-30[06:55:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/16635/">publish-testray-report#16635</a><br/></div></div>

2023-08-31 06:04 UTC, Tim-Cao commented
See changes @pedroamarall
https://github.com/liferay-echo/liferay-portal/pull/13492

2023-08-31 06:04 UTC, Tim-Cao commented
ci:close

2023-08-31 06:04 UTC, closed without merging