LPS-193186 | Test Automation | Master
liferay-echo/liferay-portal pull request #13514
Opened 2023-08-31 17:16 UTC by rafaellajordao

# LPS-193186 -  Test Automation Creation

Hi! :)
This pr is corresponding to this ticket: [LPS-149468](https://liferay.atlassian.net/browse/LPS-149468) → [LPS-193186](https://liferay.atlassian.net/browse/LPS-193186)

2023-08-31 17:16 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-08-31 17:16 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-08-31 17:16 UTC, rafaellajordao commented
ci:test:sf

2023-08-31 17:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/6443/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6443/jenkins-report.html">here</a>.</b></p>

2023-08-31 17:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d4a43bda21e4fc787d24c7525bc00793fefb3540">d4a43bda21e4fc787d24c7525bc00793fefb3540</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-193186">LPS-193186</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/141e8da87e81706301e923c1442e11d4f1b40400">141e8da87e81706301e923c1442e11d4f1b40400</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6443/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6443/jenkins-report.html">here</a>.</h5></details></html>

2023-08-31 17:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6443/">test-portal-source-format#6443</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6443/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13514">liferay-echo#13514</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2416606465">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#13514 - 2023-08-31[10:19:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/3419/">publish-testray-report#3419</a><br/></div></div>

2023-09-01 00:10 UTC, Tim-Cao requested changes
Hi @rafaellajordao, just small changes, Could you made them?

2023-09-01 00:10 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/SegmentationEditSegment.testcase
> +	test CheckIconsInMenuItems {
ViewIconsOfSegmentsActions

2023-09-01 00:10 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/SegmentationEditSegment.testcase
> +		task ("Given the kebab menu next to a segment") {
When the user opens the dropdown menu of a segment

2023-09-04 16:35 UTC, rafaellajordao commented
ci:test:sf

2023-09-04 16:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5613/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5613/jenkins-report.html">here</a>.</b></p>

2023-09-04 16:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f81dc316e4f3f1dcfe5e0865f8c92e365e67b9c5">f81dc316e4f3f1dcfe5e0865f8c92e365e67b9c5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-193186">LPS-193186</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/90caf3c5c29ad8f00d2dd9743b455165efbb9344">90caf3c5c29ad8f00d2dd9743b455165efbb9344</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5613/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5613/jenkins-report.html">here</a>.</h5></details></html>

2023-09-04 16:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5613/">test-portal-source-format#5613</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5613/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13514">liferay-echo#13514</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2418390619">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#13514 - 2023-09-04[09:36:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/21500/">publish-testray-report#21500</a><br/></div></div>

2023-09-04 21:38 UTC, Tim-Cao commented
LGTM!

2023-09-04 21:38 UTC, Tim-Cao commented
ci:forward

2023-09-04 21:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-09-04 21:38 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-09-04 21:38 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-33.liferay.com/job/forward-pullrequest/473//consoleFull)

2023-09-04 21:39 UTC, closed without merging

2023-09-04 21:39 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/140192
[Console](https://test-1-33.liferay.com/job/forward-pullrequest/473//consoleFull)