LRQA-57223 | master
liferay-echo/liferay-portal pull request #13573
Opened 2023-09-06 05:15 UTC by SylviaLuan

https://liferay.atlassian.net/browse/LRQA-57223

2023-09-06 05:15 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-09-06 05:15 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-13 05:34 UTC, Tim-Cao requested changes
Hi @SylviaLuan, could you modify according to comments? Thanks

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +			Button.clickSave();
Use json macro
For example
```
			JSONSegmentsentry.addSegment(
				conditionType = "Organization",
				fieldName = "Region",
				groupName = "Test Site Name",
				operator = "equals",
				segmentName = "Org with Region",
				text = "utah");
```

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +			AssetListsAdmin.openAssetListsAdmin(siteURLKey = "testsite-staging");
No need

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +				assetListName = "DEMO",
Remove this parameter

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +			Portlet.addPG(portletName = "Asset Publisher");
Use json macro

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +			Navigator._gotoPage(pageName = "admin");
Navigator.gotoStagedSitePage(
				pageName = "home",
				siteName = "testsite");

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +			Portlet.addPG(portletName = "Asset Publisher");
Use json macro

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +				title = "Content C");
Use for loop

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +				layoutName = "admin");
Use for loop

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +				siteName = "testsite");
No need

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +			Navigator.openWithAppendToBaseURL(urlAppend = "web/testsite-staging");
Navigator.openStagingSiteURL

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +			Navigator.openWithAppendToBaseURL(urlAppend = "web/testsite ");
Navigator.openSiteURL

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +			Navigator.openWithAppendToBaseURL(urlAppend = "web/testsite/home");
Navigator.openSitePage

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +			Navigator.openWithAppendToBaseURL(urlAppend = "web/testsite/admin");
Navigator.openSitePage

2023-09-13 05:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/collections/CollectionsWithStaging.testcase
> +	@description = "This is a use case for LPS-109102."
Missing description

2023-09-13 19:35 UTC, Tim-Cao commented
ci:close

2023-09-13 19:35 UTC, closed without merging