LPS-195619 Convert old AUI in staging-version using JS
liferay-echo/liferay-portal pull request #13668
Opened 2023-09-13 16:37 UTC by BarbaraCabrera

2023-09-13 16:37 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-09-13 16:37 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-13 16:47 UTC, BarbaraCabrera commented
ci:test:sf

2023-09-13 16:57 UTC, BarbaraCabrera commented
ci:test:sf

2023-09-13 17:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/5396/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5396/jenkins-report.html">here</a>.</b></p>

2023-09-13 17:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5396/">test-portal-source-format#5396</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5396/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13668">liferay-echo#13668</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2423621218">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#13668 - 2023-09-13[10:00:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/4072/">publish-testray-report#4072</a><br/></div></div>

2023-09-18 12:20 UTC, claraizquierdo requested changes
Hi @BarbaraCabrera ,

I left some comments on the PR. Let me know if I can help in any way :)

2023-09-18 12:20 UTC, claraizquierdo commented on modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/js/PublishProcess.js
> +		toggle.addEventListener('change', onToggleDisabled);
Now when we click on the toggle we just disable it and we don't fire the submit event. Is it not necessary?

2023-09-18 12:20 UTC, claraizquierdo commented on modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/js/PublishProcess.js
> +			submit.removeEventListener('click', onSubmit);
I think this code fails if submit or toggle do not exist.

2023-09-18 12:20 UTC, claraizquierdo commented on modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/js/StagingVersionPropsTransformer.js
> +	pagesVariation: ({pagesVariationURL}) => {
The Page Variations modal does not let me select any variation.

2023-09-18 12:20 UTC, claraizquierdo commented on modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/js/StagingVersionPropsTransformer.js
> +	redo: ({layoutRevisionId, layoutSetBranchId}) => {
I would create an auxiliary function for the undo/redo code because it is very similar, and call it here like this: `myAuxFunction('redo', layoutRevisionId, layoutSetBranchId)` . What do you think?

2023-09-18 13:41 UTC, BarbaraCabrera commented on modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/js/StagingVersionPropsTransformer.js
> +	pagesVariation: ({pagesVariationURL}) => {
In the case of page variations, the behaviour of the modal is just to let you create new page variations but not to select them.

2023-09-18 13:49 UTC, BarbaraCabrera commented on modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/js/StagingVersionPropsTransformer.js
> +	redo: ({layoutRevisionId, layoutSetBranchId}) => {
Maybe this is not really necessary because I think that we normally use the `rule of three` which says that two instances of similar code do not require refactoring, but when similar code is used three times, it should be extracted into a new procedure. What do you think of it? 🤔

2023-09-18 13:50 UTC, BarbaraCabrera commented on modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/js/PublishProcess.js
> +			submit.removeEventListener('click', onSubmit);
Yes! Already fixed, thanks 😄

2023-09-19 09:06 UTC, BarbaraCabrera commented
ci:test:sf

2023-09-19 09:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/5920/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5920/jenkins-report.html">here</a>.</b></p>

2023-09-19 09:13 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dad0084bcf063f26a9585cb352c3b656e95a19b7">dad0084bcf063f26a9585cb352c3b656e95a19b7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-195619">LPS-195619</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/363eb72f78c523642767631b7b922e5f70a0f41e">363eb72f78c523642767631b7b922e5f70a0f41e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5920/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5920/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: Property value 'commons-collections:commons-collections-&gt;modules/apps/portal-template/portal-template-velocity/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 2: Property value 'commons-collections:commons-collections-&gt;modules/dxp/apps/saml/saml-opensaml-integration/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 1:39.274 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-5/job/test-portal-source-format/5920//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230918120255124.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230918120255124.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1021146042.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null2143114932
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 178ms
[junitreport] Deleting: /tmp/null2143114932
     [echo] A report with all the test results can be found at test-results/html/index.html.</pre></details></html>

2023-09-19 09:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5920/">test-portal-source-format#5920</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5920/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13668">liferay-echo#13668</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2427300167">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#13668 - 2023-09-19[02:09:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-5.liferay.com/job/publish-testray-report/2474/">publish-testray-report#2474</a><br/></div></div>

2023-09-19 09:24 UTC, BarbaraCabrera commented
**The SF failures are not related with the pr changes.** 

![the-penguins-of-madagascar-madagascar](https://github.com/liferay-echo/liferay-portal/assets/93203423/658b099e-d673-4d77-b14d-892544bb3344)

2023-09-19 17:19 UTC, BarbaraCabrera commented
ci:test:sf

2023-09-19 17:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/7426/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7426/jenkins-report.html">here</a>.</b></p>

2023-09-19 17:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 10 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4a34c2b87f4834caa8ba0e8db89147fbc9f0c577">4a34c2b87f4834caa8ba0e8db89147fbc9f0c577</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-195619">LPS-195619</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/363eb72f78c523642767631b7b922e5f70a0f41e">363eb72f78c523642767631b7b922e5f70a0f41e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7426/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7426/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: Property value 'commons-collections:commons-collections-&gt;modules/apps/portal-template/portal-template-velocity/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 2: Property value 'commons-collections:commons-collections-&gt;modules/dxp/apps/saml/saml-opensaml-integration/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 1:43.408 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-11/job/test-portal-source-format/7426//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230919102921970.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230919102921970.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2044410413.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1882214521
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 212ms
[junitreport] Deleting: /tmp/null1882214521
     [echo] A report with all the test results can be found at test-results/html/index.html.</pre></details></html>

2023-09-19 17:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7426/">test-portal-source-format#7426</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7426/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13668">liferay-echo#13668</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2427507450">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#13668 - 2023-09-19[10:19:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/4574/">publish-testray-report#4574</a><br/></div></div>

2023-09-19 17:50 UTC, ealonso commented on modules/apps/staging/staging-bar-web/src/main/java/com/liferay/staging/bar/web/internal/display/context/StagingBarDisplayContext.java
> +
@BarbaraCabrera you should remove this empty line

2023-09-19 17:50 UTC, ealonso commented on modules/apps/staging/staging-bar-web/src/main/java/com/liferay/staging/bar/web/internal/display/context/StagingBarDisplayContext.java
> +
@BarbaraCabrera emptyLine

2023-09-19 17:50 UTC, ealonso commented on modules/apps/staging/staging-bar-web/src/main/java/com/liferay/staging/bar/web/internal/display/context/StagingBarDisplayContext.java
> +
@BarbaraCabrera emptyLine

2023-09-20 08:44 UTC, BarbaraCabrera commented
ci:test:sf

2023-09-20 08:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/7435/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7435/jenkins-report.html">here</a>.</b></p>

2023-09-20 08:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4a34c2b87f4834caa8ba0e8db89147fbc9f0c577">4a34c2b87f4834caa8ba0e8db89147fbc9f0c577</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-195619">LPS-195619</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/c92a374703238652d3b780d08d15723fadbf2f43">c92a374703238652d3b780d08d15723fadbf2f43</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7435/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7435/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: Property value 'commons-collections:commons-collections-&gt;modules/apps/portal-template/portal-template-velocity/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 2: Property value 'commons-collections:commons-collections-&gt;modules/dxp/apps/saml/saml-opensaml-integration/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 1:44.604 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-11/job/test-portal-source-format/7435//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230920014805223.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230920014805223.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null288789712.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1851754984
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 253ms
[junitreport] Deleting: /tmp/null1851754984
     [echo] A report with all the test results can be found at test-results/html/index.html.</pre></details></html>

2023-09-20 08:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7435/">test-portal-source-format#7435</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7435/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13668">liferay-echo#13668</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2428050035">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#13668 - 2023-09-20[01:44:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/4584/">publish-testray-report#4584</a><br/></div></div>

2023-09-20 10:56 UTC, claraizquierdo approved these changes
Hi @BarbaraCabrera ,

everything seems to be working fine now :) 🎉 

As a future improvement I would migrate the PubblishProcess js to React.

2023-09-20 11:00 UTC, ealonso commented
Hey @claraizquierdo @BarbaraCabrera,

We are just migrating from AUI, since it is a component from another team, I would prefer if we only focus only in the task not in the improvements.

2023-09-20 11:05 UTC, ealonso commented
ci:forward

2023-09-20 11:05 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-09-20 11:25 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 20 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4a34c2b87f4834caa8ba0e8db89147fbc9f0c577">4a34c2b87f4834caa8ba0e8db89147fbc9f0c577</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-195619">LPS-195619</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/c92a374703238652d3b780d08d15723fadbf2f43">c92a374703238652d3b780d08d15723fadbf2f43</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2942/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2942/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: Property value 'commons-collections:commons-collections-&gt;modules/apps/portal-template/portal-template-velocity/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 2: Property value 'commons-collections:commons-collections-&gt;modules/dxp/apps/saml/saml-opensaml-integration/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 1:18.722 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-40/job/test-portal-source-format/2942//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230920042520368.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230920042520368.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1196172339.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1271846592
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 168ms
[junitreport] Deleting: /tmp/null1271846592
     [echo] A report with all the test results can be found at test-results/html/index.html.</pre></details></html>

2023-09-20 11:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2942/">test-portal-source-format#2942</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2942/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13668">liferay-echo#13668</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2428074018">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#13668 - 2023-09-20[04:05:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/11353/">publish-testray-report#11353</a><br/></div></div>

2023-09-20 11:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/6189/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6189/jenkins-report.html">here</a>.</b></p>

2023-09-20 13:15 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 29 out of 30 jobs passed</h3><h3>:x: ci:test:relevant - 80 out of 87 jobs passed in 1 hour 24 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4a34c2b87f4834caa8ba0e8db89147fbc9f0c577">4a34c2b87f4834caa8ba0e8db89147fbc9f0c577</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4a34c2b87f4834caa8ba0e8db89147fbc9f0c577">4a34c2b87f4834caa8ba0e8db89147fbc9f0c577</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2427753928">EE Development Acceptance (master) - 23 - 2023-09-19[12:44:51]</a></p><details><summary><strong>ci:test:stable - 29 out of 30 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/657923/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/589592/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274865/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269131/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/265940/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/265941/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269130/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/252260/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/646740/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830672/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/854373/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/657925/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305803/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/353160/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/271727/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/657928/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/692338/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/854375/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830675/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/657924/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/606550/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/589593/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/719741/"><strike>modules-integration-mysql57-jdk8_stable/0/1</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/719740/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/273157/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337639/">portal-license-smoke-mysql57-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/290587/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830676/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729961/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/353155/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>29 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 80 out of 87 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/6189/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/657923/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/589592/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/235299/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/260348/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729960/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305805/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274865/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal [...]

2023-09-20 13:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/6189/">test-portal-acceptance-pullrequest(master)#6189</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6189/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/13668">liferay-echo#13668</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2428126572">[master] ci:test:relevant - BarbaraCabrera &gt; liferay-echo - PR#13668 - 2023-09-20[04:51:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/11356/">publish-testray-report#11356</a><br/></div></div>

2023-09-21 06:22 UTC, Tim-Cao commented
Hi @BarbaraCabrera, would you mind sending this PR to staging team?

2023-09-21 07:37 UTC, BarbaraCabrera commented
> Hi @BarbaraCabrera, would you mind sending this PR to staging team?

For sure. Thanks!

2023-09-21 07:38 UTC, closed without merging

2023-09-28 07:14 UTC, BarbaraCabrera commented
ci:reopen

2023-09-28 07:14 UTC, liferay-continuous-integration commented
GitHub error message: state cannot be changed. The LPS-195619 branch was force-pushed or recreated.