LPS-196001
liferay-echo/liferay-portal pull request #13819
Opened 2023-09-26 12:09 UTC by rafaellajordao

2023-09-26 12:09 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-09-26 12:09 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-26 12:12 UTC, rafaellajordao commented
ci:test:sf

2023-09-26 12:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3013/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3013/jenkins-report.html">here</a>.</b></p>

2023-09-26 19:34 UTC, Tim-Cao requested changes

2023-09-26 19:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/abtest/ABTest.path
> +	<td>//tbody//*[contains(@aria-label,"Show Actions")][${key_index}]</td>
This one is already fixed by https://liferay.atlassian.net/browse/LPS-195990

2023-09-27 10:12 UTC, Tim-Cao commented
@rafaellajordao, would you mind refactoring? Thanks

2023-09-28 08:18 UTC, Tim-Cao commented
See https://github.com/liferay-echo/liferay-portal/pull/13850 @rafaellajordao

2023-09-28 08:18 UTC, Tim-Cao commented
ci:close

2023-09-28 08:18 UTC, closed without merging