LPS-199557
liferay-echo/liferay-portal pull request #14115
Opened 2023-10-25 20:06 UTC by alessandromalves

2023-10-25 20:06 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-10-25 20:06 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-10-25 20:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2334/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2334/jenkins-report.html">here</a>.</b></p>

2023-10-25 20:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1206124b6f7b7d569ceaf75a45f8dffac6ab062f">1206124b6f7b7d569ceaf75a45f8dffac6ab062f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LPS-199557">LPS-199557</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/2a3061c8e3b8aa3284580f9564248a2af33ca48c">2a3061c8e3b8aa3284580f9564248a2af33ca48c</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2334/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2334/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
     [java] SLF4J: Defaulting to no-operation (NOP) logger implementation
     [java] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[stopwatch] [run.batch.test.action: 1:57.349 sec]
     [echo] 
      [get] Getting: http://test-1-33/job/test-portal-source-format/2334//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20231025131051569.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20231025131051569.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null37839687.properties</pre></details></html>

2023-10-25 20:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2334/">test-portal-source-format#2334</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2334/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14115">liferay-echo#14115</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2446725136">[master] ci:test:sf - alessandromalves &gt; liferay-echo - PR#14115 - 2023-10-25[13:06:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/9948/">publish-testray-report#9948</a><br/></div></div>

2023-10-25 21:14 UTC, alessandromalves commented
ci:test:sf

2023-10-25 21:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/6864/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6864/jenkins-report.html">here</a>.</b></p>

2023-10-25 21:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1206124b6f7b7d569ceaf75a45f8dffac6ab062f">1206124b6f7b7d569ceaf75a45f8dffac6ab062f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LPS-199557">LPS-199557</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/b45bacae57c1185526e8c425fe8ac374170a7fb5">b45bacae57c1185526e8c425fe8ac374170a7fb5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6864/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6864/jenkins-report.html">here</a>.</h5></details></html>

2023-10-25 21:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6864/">test-portal-source-format#6864</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6864/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14115">liferay-echo#14115</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2446725924">[master] ci:test:sf - alessandromalves &gt; liferay-echo - PR#14115 - 2023-10-25[14:31:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/26956/">publish-testray-report#26956</a><br/></div></div>

2023-10-26 07:31 UTC, Tim-Cao requested changes
Hi @alessandromalves, would you mind refactoring according to comments? Thanks

2023-10-26 07:31 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/asset/categories/Categories.testcase
> +	test viewCategoriesRemainingInTheOrderAddedOnWebContent {
Move to WebContent.testcase file Then renamed to AddWebContentWithCategoryHiearchy

2023-10-26 07:31 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/asset/categories/Categories.testcase
> +		task ("Given that some categories are added to the vocabulary") {
Given the user has a category hiearchy

2023-10-26 07:31 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/asset/categories/Categories.testcase
> +		task ("When a new web content is added and the categories are selected") {
When the user adds a web content with the category hiearchy

2023-10-26 07:31 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/macros/journal/WebContent.macro
> +	macro viewCategorizationCategoryByIndex {
viewCategorizationCategoriesOrderCP

2023-10-26 07:31 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/macros/journal/WebContent.macro
> +		var categoryIndex = 1;
var index = 1;

2023-10-26 07:31 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/macros/journal/WebContent.macro
> +			var categoryIndex = ${categoryIndex} + 1;
var index = ${index} + 1;

2023-10-26 07:31 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uisections/AssetCategorization.path
> +	<td>//div[contains(@id,'assetCategoriesSelector') or contains(@class,'field-content')]//span[contains(@class,'label')][${key_index}]//span[contains(.,'${key_categoryName}')]/parent::span</td>
`xpath=(//label[normalize-space()='${key_vocabularyName}']//following-sibling::div//span[contains(@class,'label') and contains(@role,'row')])[${index}][normalize-space()='${key_categoryName}']`

2023-10-26 07:31 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/asset/categories/Categories.testcase
> +		task ("Then the categories must remain in the order them were added to the web content") {
Then the added categories should keep the same order with hiearchy

2023-10-26 14:12 UTC, alessandromalves commented
ci:test:sf

2023-10-26 14:13 UTC, Tim-Cao commented
LGTM!

2023-10-26 14:13 UTC, Tim-Cao commented
ci:forward

2023-10-26 14:14 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-10-26 14:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/7221/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7221/jenkins-report.html">here</a>.</b></p>

2023-10-26 14:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5933/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5933/jenkins-report.html">here</a>.</b></p>

2023-10-26 14:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 12 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/259e93090188cbf1a0ddca3d8d63a4b2d116212e">259e93090188cbf1a0ddca3d8d63a4b2d116212e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LPS-199557">LPS-199557</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/a727853e15597451fd2969aa9b815be1e21153ab">a727853e15597451fd2969aa9b815be1e21153ab</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7221/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7221/jenkins-report.html">here</a>.</h5></details></html>

2023-10-26 14:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 14 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/259e93090188cbf1a0ddca3d8d63a4b2d116212e">259e93090188cbf1a0ddca3d8d63a4b2d116212e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LPS-199557">LPS-199557</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/a727853e15597451fd2969aa9b815be1e21153ab">a727853e15597451fd2969aa9b815be1e21153ab</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5933/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5933/jenkins-report.html">here</a>.</h5></details></html>

2023-10-26 14:26 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-18.liferay.com/job/test-portal-source-format/7221//consoleFull)

2023-10-26 14:27 UTC, closed without merging

2023-10-26 14:27 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/142756
[Console](https://test-1-18.liferay.com/job/test-portal-source-format/7221//consoleFull)

2023-10-26 14:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7221/">test-portal-source-format#7221</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7221/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14115">liferay-echo#14115</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2447037485">[master] ci:test:sf - alessandromalves &gt; liferay-echo - PR#14115 - 2023-10-26[07:14:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/4472/">publish-testray-report#4472</a><br/></div></div>

2023-10-26 14:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5933/">test-portal-source-format#5933</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5933/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14115">liferay-echo#14115</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2447048060">[master] ci:test:sf - alessandromalves &gt; liferay-echo - PR#14115 - 2023-10-26[07:12:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/22730/">publish-testray-report#22730</a><br/></div></div>

2023-10-26 15:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4013/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4013/jenkins-report.html">here</a>.</b></p>

2023-10-26 15:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4013/">test-portal-acceptance-pullrequest(master)#4013</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4013/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14115">liferay-echo#14115</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2447093324">[master] ci:test:relevant - alessandromalves &gt; liferay-echo - PR#14115 - 2023-10-26[08:39:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8033/">publish-testray-report#8033</a><br/></div></div>