LPS-199890 New Web Content Admin Configuration View
liferay-echo/liferay-portal pull request #14120
Opened 2023-10-26 13:29 UTC by jkappler

https://liferay.atlassian.net/browse/LPS-199890

2023-10-26 13:29 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-10-26 13:29 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-10-26 13:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/5973/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5973/jenkins-report.html">here</a>.</b></p>

2023-10-26 13:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5d4ce1ff8a61769f109947c97f6187dbb35cfc28">5d4ce1ff8a61769f109947c97f6187dbb35cfc28</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jkappler/liferay-portal/tree/LPS-199890_configuration_view_wc">LPS-199890_configuration_view_wc</a><br/>Branch GIT ID: <a href="https://github.com/jkappler/liferay-portal/commit/d98dab502dd279cffcaba2306684bec405188898">d98dab502dd279cffcaba2306684bec405188898</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5973/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5973/jenkins-report.html">here</a>.</h5></details></html>

2023-10-26 13:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5973/">test-portal-source-format#5973</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5973/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14120">liferay-echo#14120</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2447008592">[master] ci:test:sf - jkappler &gt; liferay-echo - PR#14120 - 2023-10-26[06:30:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-5.liferay.com/job/publish-testray-report/2551/">publish-testray-report#2551</a><br/></div></div>

2023-10-30 23:15 UTC, ruben-pulido requested changes

2023-10-31 06:50 UTC, jkappler commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/configuration_browse.jsp
> +									emailSubjectLocalizedValuesMap="<%= journalGroupServiceConfiguration.emailArticleApprovalGrantedSubject() %>"
Thanks for pointing it out @ruben-pulido, fixed

2023-11-03 11:10 UTC, closed without merging