LPS-199736 Move invitation-invite-members-web - main.js to react
liferay-echo/liferay-portal pull request #14168
Opened 2023-10-31 16:31 UTC by DiegoHu97

2023-10-31 16:31 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-10-31 16:31 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-10-31 16:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3435/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3435/jenkins-report.html">here</a>.</b></p>

2023-10-31 16:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4f33caca1b181bc1a1a7968773ce7447f79449e7">4f33caca1b181bc1a1a7968773ce7447f79449e7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/DiegoHu97/liferay-portal/tree/LPS-199736">LPS-199736</a><br/>Branch GIT ID: <a href="https://github.com/DiegoHu97/liferay-portal/commit/46a7c4f617bcec333064c3a44d8a1764fbea6706">46a7c4f617bcec333064c3a44d8a1764fbea6706</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3435/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3435/jenkins-report.html">here</a>.</h5></details></html>

2023-10-31 16:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3435/">test-portal-source-format#3435</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3435/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14168">liferay-echo#14168</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2450011528">[master] ci:test:sf - DiegoHu97 &gt; liferay-echo - PR#14168 - 2023-10-31[09:31:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/13275/">publish-testray-report#13275</a><br/></div></div>

2023-10-31 16:45 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +		Group group = GroupLocalServiceUtil.getGroup(
@DiegoHu97 you can use directly _themeDisplay.getScopeGroupId() instead of getting the group and then the groupId

2023-10-31 16:45 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +			_themeDisplay.getScopeGroupId());
@DiegoHu97 same here

2023-10-31 16:47 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/resources/META-INF/resources/invite_members/view.jsp
> +			<portlet:param name="mvcPath" value="/invite_members/js/view.jsp" />
@DiegoHu97 why do you add /js to the view.jsp path?

2023-10-31 16:47 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/resources/META-INF/resources/invite_members/view.jsp
> +					"groupId", themeDisplay.getScopeGroupId()
@DiegoHu97 it can be scopeGroupId

2023-10-31 16:49 UTC, ealonso commented on modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties
> +user-already-invited=User already invited
@DiegoHu97 the key should follow liferay pattern, if it is a label it should be User Already Invited, if it is a phrase it should end with a "."

2023-10-31 17:04 UTC, DiegoHu97 commented on modules/apps/invitation/invitation-invite-members-web/src/main/resources/META-INF/resources/invite_members/view.jsp
> +			<portlet:param name="mvcPath" value="/invite_members/js/view.jsp" />
@ealonso this is not used, I forgot to delete it

2023-10-31 17:22 UTC, DiegoHu97 commented
@ealonso I just made the changes 😄

2023-11-02 07:32 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +	private final RenderRequest _renderRequest;
RenderRequest and RenderResponse are not used, so it is not necessary to define vars

2023-11-02 07:33 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +		for (Team team : teams) {
Here you should use TransformUtil.transform(

2023-11-02 07:33 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +		List<Map<String, Object>> rolesItem = new ArrayList<>();
Here you should use TransformUtil.transform(

2023-11-02 07:34 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +	public List<Map<String, Object>> getRolesItem() throws PortalException {
You should call it getRoles and the same for teams, getTeams

2023-11-02 07:34 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/resources/META-INF/resources/invite_members/view.jsp
> +				HashMapBuilder.<String, Object>put(
You can move it to DisplayContext class

2023-11-02 10:10 UTC, DiegoHu97 commented
@ealonso Updated! 😄

2023-11-02 10:33 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +		List<Team> teams = TeamLocalServiceUtil.getGroupTeams(
You can inline it, it is not necessary to check if it is empty

2023-11-02 10:33 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +		roles = UsersAdminUtil.filterGroupRoles(
You can inline it, it is not necessary to check if it is empty

2023-11-02 10:33 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +			layout.getCompanyId(), null, null,
You can use themeDisplay to get the company id

2023-11-02 10:34 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +				PermissionThreadLocal.getPermissionChecker(),
You can use themeDisplay to get the permission checker

2023-11-02 10:34 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +				PermissionThreadLocal.getPermissionChecker(),
You can use themeDisplay to get the permission checker

2023-11-02 11:45 UTC, DiegoHu97 commented
@ealonso Done! 😄

2023-11-02 11:57 UTC, ealonso commented on modules/apps/invitation/invitation-invite-members-web/src/main/java/com/liferay/invitation/invite/members/web/internal/display/context/InviteMembersDisplayContext.java
> +	public List<Map<String, Object>> getTeams() {
Here you can inline those methods or make those private

2023-11-02 11:57 UTC, ealonso commented on modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties
> +user-attribute=User AttributeI
AttributeI -> I think you add an extra I

2023-11-08 15:24 UTC, claraizquierdo requested changes
Hi @DiegoHu97 ,

great work here. The code seems to be working fine, I just made some comments to see if we can simplify some parts of the code.  Also, I have found two visual "bugs"  that could be improved:

- The content of the table is not well aligned 
![Captura de pantalla 2023-11-08 a las 13 35 00](https://github.com/liferay-echo/liferay-portal/assets/3276218/cce2b828-0655-4329-bd85-c9c28719960e)

- There could be more space after the button here:
![Captura de pantalla 2023-11-08 a las 13 35 10](https://github.com/liferay-echo/liferay-portal/assets/3276218/ca90fd72-7e08-4f6b-aeb8-620e4b329d05)

2023-11-08 16:49 UTC, DiegoHu97 commented on modules/apps/invitation/invitation-invite-members-web/src/main/resources/META-INF/resources/invite_members/js/InviteMembers.js
> +					className="so-portlet-invite-members"
@claraizquierdo Yes this is necessary for the styles of the users container, for example the border and the height

2023-11-08 16:49 UTC, DiegoHu97 commented on modules/apps/invitation/invitation-invite-members-web/src/main/resources/META-INF/resources/invite_members/js/InviteMembers.js
> +														event.preventDefault();
@claraizquierdo sorry, I forgot to remove it

2023-11-08 16:58 UTC, DiegoHu97 commented
@claraizquierdo Hey! I just made the changes, thank you for the review 😄 
<img width="565" alt="Screenshot 2023-11-08 at 17 47 58" src="https://github.com/liferay-echo/liferay-portal/assets/91208451/4ca51b39-12ea-4491-a2a0-c49245551305">

2023-11-10 10:17 UTC, claraizquierdo requested changes
Hi @DiegoHu97 , just one thing with the translations.

2023-11-10 10:17 UTC, claraizquierdo commented on modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language_ar.properties
> +user-attribute=User AttributeI (Automatic Copy)
Sorry I didn't notice this in the first review, but I think you are changing the user-attribute translation when it shouldn't be changed.

2023-11-10 11:22 UTC, DiegoHu97 commented
@claraizquierdo Updated! 😄

2023-11-10 12:10 UTC, claraizquierdo approved these changes
🎉

2023-11-10 12:11 UTC, claraizquierdo commented
ci:forward

2023-11-10 12:11 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-11-10 12:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7305/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7305/jenkins-report.html">here</a>.</b></p>

2023-11-10 12:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/2791/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2791/jenkins-report.html">here</a>.</b></p>

2023-11-10 12:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee303dbf5d7a3c23dfc86c727bb4c78ed894e749">ee303dbf5d7a3c23dfc86c727bb4c78ed894e749</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/DiegoHu97/liferay-portal/tree/LPS-199736">LPS-199736</a><br/>Branch GIT ID: <a href="https://github.com/DiegoHu97/liferay-portal/commit/f50dbf1af7480a83e7ea0663bd3869b3eceb8b7a">f50dbf1af7480a83e7ea0663bd3869b3eceb8b7a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2791/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2791/jenkins-report.html">here</a>.</h5></details></html>

2023-11-10 12:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2791/">test-portal-source-format#2791</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2791/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14168">liferay-echo#14168</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2456452794">[master] ci:test:sf - DiegoHu97 &gt; liferay-echo - PR#14168 - 2023-11-10[04:11:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/21235/">publish-testray-report#21235</a><br/></div></div>

2023-11-10 12:26 UTC, ealonso commented
ci:stop

2023-11-10 12:27 UTC, ealonso commented
@DiegoHu97 @sandrodw3 @claraizquierdo We need to talk with Lima team about it

2023-11-10 12:28 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 16 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee303dbf5d7a3c23dfc86c727bb4c78ed894e749">ee303dbf5d7a3c23dfc86c727bb4c78ed894e749</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee303dbf5d7a3c23dfc86c727bb4c78ed894e749">ee303dbf5d7a3c23dfc86c727bb4c78ed894e749</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2455800447">EE Development Acceptance (master) - 140 - 2023-11-09[04:40:12]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7305/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7305/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7305/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Build was aborted</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-11-10 12:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7305/">test-portal-acceptance-pullrequest(master)#7305</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7305/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14168">liferay-echo#14168</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2456461198">[master] ci:test:relevant - DiegoHu97 &gt; liferay-echo - PR#14168 - 2023-11-10[04:11:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/13901/">publish-testray-report#13901</a><br/></div></div>

2023-11-10 13:56 UTC, DiegoHu97 commented
Sen to lima here: https://github.com/liferay-lima/liferay-portal/pull/4887

2023-11-10 13:56 UTC, closed without merging