LPS-197895
liferay-echo/liferay-portal pull request #14265
Opened 2023-11-08 18:57 UTC by rafaellajordao

2023-11-08 18:57 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-08 18:57 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-08 19:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/4551/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4551/jenkins-report.html">here</a>.</b></p>

2023-11-08 19:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f511c0d9553cba5a0446d1a63d3f5c128310fb1a">f511c0d9553cba5a0446d1a63d3f5c128310fb1a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-197895">LPS-197895</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/a22e87285a5d79eff0c2d27453cc586343835909">a22e87285a5d79eff0c2d27453cc586343835909</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4551/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4551/jenkins-report.html">here</a>.</h5></details></html>

2023-11-08 19:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4551/">test-portal-source-format#4551</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4551/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14265">liferay-echo#14265</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2455161810">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#14265 - 2023-11-08[11:00:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/16917/">publish-testray-report#16917</a><br/></div></div>

2023-11-09 03:14 UTC, Tim-Cao requested changes
Hi @rafaellajordao, would you mind refactoring according to comments? Thanks

2023-11-09 03:14 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/MenuItem.path
> +	<td>//a[contains(@class, 'dropdown-item active')][contains(text(), '${key_menuItem}')]</td>
`xpath=(//div | //li)[(contains(@class,'open') or contains(@class,'show')) and (contains(@class,'dropdown') or contains(.//*/@class,'dropdown'))]//*[self::a or self::span or self::button][contains(@class,'active')][normalize-space(text())='${key_menuItem}']`

2023-11-09 03:14 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pageeditor/PageEditorWithLockedPages.testcase
> +				userScreenName = "usersn");
Same as above

2023-11-09 03:14 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pageeditor/PageEditorWithLockedPages.testcase
> +				userScreenName = "usersn");
Same as above

2023-11-09 13:30 UTC, rafaellajordao commented
Hey @Tim-Cao , I've already made all the changes just waiting for Bea's response! :)

2023-11-10 03:00 UTC, Tim-Cao commented
Btw, please rebase after https://github.com/liferay-echo/liferay-portal/pull/14282 merged. Thanks @rafaellajordao

2023-11-13 12:18 UTC, rafaellajordao commented
> Btw, please rebase after #14282 merged. Thanks @rafaellajordao

Done!

2023-11-13 13:46 UTC, rafaellajordao commented
ci:test:sf

2023-11-13 13:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/7324/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7324/jenkins-report.html">here</a>.</b></p>

2023-11-13 13:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f5427791c257982794ea6b045d4893a73af1d96">6f5427791c257982794ea6b045d4893a73af1d96</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-197895">LPS-197895</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/ba037d7f5b0cacab22e26926d4407d3cbc74205b">ba037d7f5b0cacab22e26926d4407d3cbc74205b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/7324/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7324/jenkins-report.html">here</a>.</h5></details></html>

2023-11-13 13:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/7324/">test-portal-source-format#7324</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7324/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14265">liferay-echo#14265</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2457707669">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#14265 - 2023-11-13[05:47:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/4026/">publish-testray-report#4026</a><br/></div></div>

2023-11-13 20:42 UTC, Tim-Cao commented
Hi @rafaellajordao, I've splited cases related locked pages here. See changes https://github.com/liferay-echo/liferay-portal/pull/14333

2023-11-13 20:57 UTC, Tim-Cao requested changes
Would you mind modifying according to comments? Thanks! @rafaellajordao

2023-11-13 20:57 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				locator1 = "LexiconList#LIST_ENTRY_X",
Modify value of `LexiconList#LIST_ENTRY_X` to `xpath=(//*[@data-qa-id='row'][contains(@class,'list')])[${key_position}]`

2023-11-13 20:57 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				locator1 = "ManagementBar#ORDER_ICON_GENERIC",
Use the previous element

2023-11-13 20:57 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				locator1 = "ManagementBar#ORDER_ICON_GENERIC",
Use the previous element

2023-11-13 20:57 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +	test ViewOrderButtonNotPresentWithRecentFilter {
ViewOrderButtonDisabledWhenFilterByRecent

2023-11-13 20:57 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +	test ViewAccessibilityInOrderButtonOfWebContentSearch {
RevertSortDirectionOfSearchResultsViaKeyboard

2023-11-13 20:57 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +	test ViewOrderOfWebContentWithFilterAndSearch {
OrderByTitleInSearchResults

2023-11-13 20:57 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +	test ViewOrderOfWebContentWithFilterAndSearchVariation {
OrderByDisplayDateInNewSearchResults

2023-11-13 20:57 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/MenuItem.path
> +</tr>
Keep this change for WebContent cases

2023-11-17 19:28 UTC, closed without merging