LPS-201012
liferay-echo/liferay-portal pull request #14293
Opened 2023-11-10 13:58 UTC by rafaellajordao

2023-11-10 13:58 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-10 13:58 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-10 14:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/6068/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/6068/jenkins-report.html">here</a>.</b></p>

2023-11-10 14:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee303dbf5d7a3c23dfc86c727bb4c78ed894e749">ee303dbf5d7a3c23dfc86c727bb4c78ed894e749</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-201012">LPS-201012</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/6b042eba8d31c0e23e34caf6ee0abf38a9a1641f">6b042eba8d31c0e23e34caf6ee0abf38a9a1641f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/6068/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/6068/jenkins-report.html">here</a>.</h5></details></html>

2023-11-10 14:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-source-format/6068/">test-portal-source-format#6068</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/6068/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14293">liferay-echo#14293</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2456532380">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#14293 - 2023-11-10[05:59:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/4344/">publish-testray-report#4344</a><br/></div></div>

2023-11-10 20:41 UTC, Tim-Cao requested changes
Hi @rafaellajordao, would you mind modifying according to comments? Thanks

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				value1 = "\TAB");
This element should be previous focused one not Home

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				value1 = "WC Folder Name");
```
Breadcrumb.viewActiveEntry

WebContentAdmin.viewEntryTitle
```

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				value1 = "\TAB");
Same as above

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				value1 = "WC Folder Name");
Breadcrumb.viewActiveEntry

WebContentAdmin.viewEntryTitle

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +				locator1 = "Breadcrumb#BREADCRUMB_ENTRY_LINK");
Add a macro named Breadcrumb.gotoEntry

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +				value1 = "WC Folder Name");
Same as above

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +				value1 = "WC Folder Name");
Same as above

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +	test ViewFilePathInteractiveElementViaKeyboard {
Move to WebContentAdminWithKeyboard.testcase then rename to NavigateByBreadcrumbInSearchResultsViaKeyboard

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +	test ViewFilePathInteractiveElement {
Move to WebContentUI.testcase then rename to NavigateByBreadcrumbInSearchResults

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +
Then block

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +		task ("Then it is possible to access the file path using the keyboard") {
When block

2023-11-10 20:41 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +
Then block

2023-11-13 12:21 UTC, rafaellajordao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +	test ViewFilePathInteractiveElement {
done!

2023-11-13 12:23 UTC, rafaellajordao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +				locator1 = "Breadcrumb#BREADCRUMB_ENTRY_LINK");
done!

2023-11-13 12:44 UTC, rafaellajordao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +	test ViewFilePathInteractiveElementViaKeyboard {
done!

2023-11-13 12:48 UTC, rafaellajordao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				value1 = "WC Folder Name");
done

2023-11-13 13:02 UTC, rafaellajordao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				value1 = "\TAB");
I don't understand, could you explain to me what I should do?

2023-11-13 13:03 UTC, rafaellajordao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				value1 = "\TAB");
I don't understand, could you explain to me what I should do?

2023-11-13 18:49 UTC, Tim-Cao commented
@rafaellajordao, see changes https://github.com/liferay-echo/liferay-portal/pull/14330

2023-11-13 18:49 UTC, Tim-Cao commented
ci:close

2023-11-13 18:49 UTC, closed without merging