LPS-199847
liferay-echo/liferay-portal pull request #14296
Opened 2023-11-10 19:27 UTC by rafaellajordao

2023-11-10 19:27 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-10 19:27 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-10 19:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/6358/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6358/jenkins-report.html">here</a>.</b></p>

2023-11-10 19:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee303dbf5d7a3c23dfc86c727bb4c78ed894e749">ee303dbf5d7a3c23dfc86c727bb4c78ed894e749</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-199847">LPS-199847</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/0db94fcca2c3f1f393f21bf0b4f7f02da048e881">0db94fcca2c3f1f393f21bf0b4f7f02da048e881</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6358/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6358/jenkins-report.html">here</a>.</h5></details></html>

2023-11-10 19:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6358/">test-portal-source-format#6358</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6358/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14296">liferay-echo#14296</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2456685607">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#14296 - 2023-11-10[11:29:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/4037/">publish-testray-report#4037</a><br/></div></div>

2023-11-10 20:06 UTC, Tim-Cao requested changes
Hi @rafaellajordao, would you mind updating according to comments? Thanks

2023-11-10 20:06 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/pageaudit/PageAudit.path
> +</tr>
No need

2023-11-10 20:06 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/pageaudit/PageAudit.testcase
> +			Click(locator1 = "PageAudit#PAGE_AUDIT_EXPERIENCE_SELECTOR");
`Button#ANY_WITH_ARIA_LABEL`

2023-11-13 15:14 UTC, Tim-Cao commented
@rafaellajordao see changes https://github.com/liferay-echo/liferay-portal/pull/14327

2023-11-13 15:14 UTC, closed without merging