LPS-196367
liferay-echo/liferay-portal pull request #14329
Opened 2023-11-13 18:15 UTC by rafaellajordao

2023-11-13 18:15 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-13 18:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-13 18:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/6767/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6767/jenkins-report.html">here</a>.</b></p>

2023-11-13 18:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cc7034192fede4a5dee2cad027c7a650e87456fe">cc7034192fede4a5dee2cad027c7a650e87456fe</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-196367">LPS-196367</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/aac30f9af635f34f0bcb328888ba0ef94b9e39a9">aac30f9af635f34f0bcb328888ba0ef94b9e39a9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6767/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6767/jenkins-report.html">here</a>.</h5></details></html>

2023-11-13 18:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6767/">test-portal-source-format#6767</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6767/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14329">liferay-echo#14329</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2457828576">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#14329 - 2023-11-13[10:15:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/3986/">publish-testray-report#3986</a><br/></div></div>

2023-11-13 21:10 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pageeditor/PageEditorWithLockedPages.testcase
> +	test ViewPageNameClickableAndOpensInANewTab {
NavigateToLockedPageTemplatesInList

2023-11-13 21:11 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pageeditor/PageEditorWithLockedPages.testcase
> +				targetFragmentName = "Container");
Move to NavigateToLockedPagesInList case

2023-11-17 13:38 UTC, Tim-Cao requested changes
Hi @rafaellajordao, would you mind updating according to comments? Thanks

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +			PagesAdmin.openPagesAdmin(siteURLKey = ${randomSiteName});
"Test Site Name"

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				tableEntryPartialText = "Seconds Ago");
No need

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				locator1 = "LexiconTable#TABLE_ENTRY_COLUMN_LINK",
Use the previous element

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +			Open.openInTheNewTab(value1 = "${baseURL}/web/${randomSiteName}");
test-site-name

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +		property custom.properties = "feature.flag.LPS-180328=true";
ff is removed

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +				tableEntryPartialText = "Seconds Ago");
No need

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pageeditor/PageEditorWithLockedPages.testcase
> +	test NavigateToLockedPageTemplatesInList {
Move to LockedPages.testcase

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pageeditor/PageEditorWithLockedPages.testcase
> +				targetFragmentName = "Container");
Move collection page to NavigateToLockedPagesInList

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +	test ViewLockedPageNameClickableAndOpensDraftContentPage {
Rename to NavigateToLockedPagesInList

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +		task ("Given a locked utility page") {
Insert 		var siteName = selenium.getText("Home#SITE_NAME");

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +			SelectWindow(value1 = "title=404 Error Utility Page - ${randomSiteName} - Liferay DXP");
SelectWindow(value1 = "title=404 Error Utility Page - Test Site Name - ${siteName}");

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +			SelectWindow.selectPopUp(value1 = "null");
SelectWindow(value1 = "title=404 Error Utility Page - Test Site Name - ${siteName}");

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +
Insert var siteName = selenium.getText("Home#SITE_NAME");

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pageeditor/PageEditorWithLockedPages.testcase
> +		task ("Given locked pages of various types") {
Insert var siteName = selenium.getText("Home#SITE_NAME");

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pageeditor/PageEditorWithLockedPages.testcase
> +				SelectWindow(value1 = "title=${pageName} - Test Site Name - Liferay DXP");
SelectWindow(value1 = "title=${pageName} - Test Site Name - ${siteName}");

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pageeditor/PageEditorWithLockedPages.testcase
> +					tableEntryPartialText = "Seconds Ago");
No need

2023-11-17 13:38 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pageeditor/PageEditorWithLockedPages.testcase
> +				Navigator.closeWindow();
Close.closeAndSelectWindow(value1 = "title=Locked Pages - Test Site Name - ${siteName}");

2023-11-17 18:51 UTC, rafaellajordao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				locator1 = "LexiconTable#TABLE_ENTRY_COLUMN_LINK",
Hey Tim, When I tried use the previous element I receive this error message `org.openqa.selenium.ElementNotInteractableException: element not interactable`
`//tr[@data-qa-id='row'][contains(.,'404 Error Utility Page')]//td[contains(@class,'name-column')]`
Can you help me with this?

2023-11-17 21:32 UTC, Tim-Cao commented
@rafaellajordao, see changes https://github.com/liferay-echo/liferay-portal/pull/14389

2023-11-17 21:33 UTC, Tim-Cao commented
ci:close

2023-11-17 21:33 UTC, closed without merging