LPS-197894
liferay-echo/liferay-portal pull request #14401
Opened 2023-11-20 12:50 UTC by rafaellajordao

2023-11-20 12:50 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-20 12:50 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-20 12:50 UTC, rafaellajordao commented
ci:test:echo

2023-11-20 12:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>echo</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/8706/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8706/jenkins-report.html">here</a>.</b></p>

2023-11-20 12:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3715/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3715/jenkins-report.html">here</a>.</b></p>

2023-11-20 12:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/263958bba46acbeb6e4aa7d0b6281aacf0c70b59">263958bba46acbeb6e4aa7d0b6281aacf0c70b59</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-197894-3">LPS-197894-3</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/639eacfab5c16b59a695c34b7e233364ecae8216">639eacfab5c16b59a695c34b7e233364ecae8216</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3715/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3715/jenkins-report.html">here</a>.</h5></details></html>

2023-11-20 12:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3715/">test-portal-source-format#3715</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3715/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14401">liferay-echo#14401</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462104518">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#14401 - 2023-11-20[04:50:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/14386/">publish-testray-report#14386</a><br/></div></div>

2023-11-20 15:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:echo - 667 out of 836 jobs passed in 2 hours 17 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/174">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1297401_8706</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/263958bba46acbeb6e4aa7d0b6281aacf0c70b59">263958bba46acbeb6e4aa7d0b6281aacf0c70b59</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/df01107b466e56a4c9b85290f102f5e502fe1f1e">df01107b466e56a4c9b85290f102f5e502fe1f1e</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462023779">EE Development Acceptance (master) - 173 - 2023-11-19[20:39:12]</a></p><details><summary><strong>ci:test:echo - 667 out of 836 jobs PASSED</strong></summary><div><h4>169 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/8706/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/320847/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455977/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934116/"><strike>functional-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764744/"><strike>functional-tomcat90-mysql57-jdk8/1/1</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830429/"><strike>functional-tomcat90-mysql57-jdk8/1/2</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934118/"><strike>functional-tomcat90-mysql57-jdk8/1/3</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/862684/"><strike>functional-tomcat90-mysql57-jdk8/1/4</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/728528/"><strike>functional-tomcat90-mysql57-jdk8/1/5</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455954/"><strike>functional-tomcat90-mysql57-jdk8/1/6</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437147/"><strike>functional-tomcat90-mysql57-jdk8/1/7</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764747/"><strike>functional-tomcat90-mysql57-jdk8/1/8</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703225/"><strike>functional-tomcat90-mysql57-jdk8/1/9</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830448/"><strike>functional-tomcat90-mysql57-jdk8/1/10</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455981/"><strike>functional-tomcat90-mysql57-jdk8/1/11</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/781229/"><strike>functional-tomcat90-mysql57-jdk8/1/12</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836123/"><strike>functional-tomcat90-mysql57-jdk8/1/13</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437172/"><strike>functional-tomcat90-mysql57-jdk8/1/14</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455983/"><strike>functional-tomcat90-mysql57-jdk8/1/15</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/728548/"><strike>functional-tomcat90-mysql57-jdk8/1/16</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455980/"><strike>functional-tomcat90-mysql57-jdk8/1/17</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/781227/"><strike>functional-tomcat90-mysql57-jdk8/1/18</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836118/"><strike>functional-tomcat90-mysql57-jdk8/1/19</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836120/"><strike>functional-tomcat90-mysql57-jdk8/1/20</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836121/"><strike>functional-tomcat90-mysql57-jdk8/1/21</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437171/"><strike>functional-tomcat90-mysql57-jdk8/1/22</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830449/"><strike>functional-tomcat90-mysql57-jdk8/1/23</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/728545/"><strike>functional-tomcat90-mysql57-jdk8/1/24</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/862708/"><strike>functional-tomcat90-mysql57-jdk8/2/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/743796/"><strike>functional-tomcat90-mysql57-jdk8/2/1</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437175/"><strike>functional-tomcat90-mysql57-jdk8/2/2</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/946834/"><strike>functional-tomcat90-mysql57-jdk8/2/3</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836131/"><strike>functional-tomcat90-mysql57-jdk8/2/4</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/673164/"><strike>functional-tomcat90-mysql57-jdk8/2/5</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764768/"><strike>functional-tomcat90-mysql57-jdk8/2/6</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/673163/"><strike>functional-tomcat90-mysql57-jdk8/2/7</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703246/"><strike>functional-tomcat90-mysql57-jdk8/2/8</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455978/"><strike>functional-tomcat90-mysql57-jdk8/2/9</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-accep [...]

2023-11-20 15:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/8706/">test-portal-acceptance-pullrequest(master)#8706</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8706/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>echo<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14401">liferay-echo#14401</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462162088">[master] ci:test:echo - rafaellajordao &gt; liferay-echo - PR#14401 - 2023-11-20[04:50:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/19322/">publish-testray-report#19322</a><br/></div></div>

2023-11-20 18:04 UTC, rafaellajordao commented
ci:test:echo

2023-11-20 18:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>echo</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/8331/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8331/jenkins-report.html">here</a>.</b></p>

2023-11-20 19:34 UTC, Tim-Cao requested changes
Hi @rafaellajordao, would you mind updating according to comments? Thanks

2023-11-20 19:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				locator1 = "ManagementBar#ORDER_ICON_GENERIC",
Use the previous element

2023-11-20 19:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +
Modify locator LIST_ENTRY_X to `xpath=(//*[@data-qa-id='row'][contains(@class,'list')])[${key_position}]`

2023-11-20 19:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				locator1 = "xpath=(//*[@data-qa-id='row'][contains(@class,'list')])[${key_position}]",
LeiconList#LIST_ENTRY_X

2023-11-20 19:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				locator1 = "ManagementBar#ORDER_ICON_GENERIC",
Use the previous element

2023-11-20 19:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +			Click.pauseClickAt(locator1 = "ManagementBar#FILTER_AND_ORDER");
Click(locator1 = "ManagementBar#FILTER_AND_ORDER");

2023-11-20 19:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/WebContent.testcase
> +			Click.clickNoMouseOver(locator1 = "ManagementBar#ORDER_ICON_GENERIC");
Click(locator1 = "ManagementBar#ORDER_ICON_GENERIC");

2023-11-20 19:34 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +				locator1 = "xpath=(//*[@data-qa-id='row'][contains(@class,'list')])[${key_position}]",
LeiconList#LIST_ENTRY_X

2023-11-20 21:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:echo - 679 out of 836 jobs passed in 3 hours 20 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/977b899d04df122a3f482009ee162404729384cb">977b899d04df122a3f482009ee162404729384cb</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/977b899d04df122a3f482009ee162404729384cb">977b899d04df122a3f482009ee162404729384cb</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462393689">EE Development Acceptance (master) - 175 - 2023-11-20[08:40:25]</a></p><details><summary><strong>ci:test:echo - 679 out of 836 jobs PASSED</strong></summary><div><h4>157 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/8331/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790461/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830905/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790444/"><strike>functional-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/744231/"><strike>functional-tomcat90-mysql57-jdk8/1/1</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/863085/"><strike>functional-tomcat90-mysql57-jdk8/1/2</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836558/"><strike>functional-tomcat90-mysql57-jdk8/1/3</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437605/"><strike>functional-tomcat90-mysql57-jdk8/1/4</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934652/"><strike>functional-tomcat90-mysql57-jdk8/1/5</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703697/"><strike>functional-tomcat90-mysql57-jdk8/1/6</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/744234/"><strike>functional-tomcat90-mysql57-jdk8/1/7</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830895/"><strike>functional-tomcat90-mysql57-jdk8/1/8</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/728939/"><strike>functional-tomcat90-mysql57-jdk8/1/9</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/673550/"><strike>functional-tomcat90-mysql57-jdk8/1/10</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703710/"><strike>functional-tomcat90-mysql57-jdk8/1/11</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437629/"><strike>functional-tomcat90-mysql57-jdk8/1/12</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947227/"><strike>functional-tomcat90-mysql57-jdk8/1/13</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456516/"><strike>functional-tomcat90-mysql57-jdk8/1/14</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/836575/"><strike>functional-tomcat90-mysql57-jdk8/1/15</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/728957/"><strike>functional-tomcat90-mysql57-jdk8/1/16</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/766574/"><strike>functional-tomcat90-mysql57-jdk8/1/17</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934671/"><strike>functional-tomcat90-mysql57-jdk8/1/18</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/863107/"><strike>functional-tomcat90-mysql57-jdk8/1/19</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456515/"><strike>functional-tomcat90-mysql57-jdk8/1/20</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/744302/"><strike>functional-tomcat90-mysql57-jdk8/1/21</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830906/"><strike>functional-tomcat90-mysql57-jdk8/1/22</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/818973/"><strike>functional-tomcat90-mysql57-jdk8/1/23</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/781666/"><strike>functional-tomcat90-mysql57-jdk8/1/24</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/781668/"><strike>functional-tomcat90-mysql57-jdk8/2/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703718/"><strike>functional-tomcat90-mysql57-jdk8/2/1</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/765073/"><strike>functional-tomcat90-mysql57-jdk8/2/2</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456522/"><strike>functional-tomcat90-mysql57-jdk8/2/3</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/790465/"><strike>functional-tomcat90-mysql57-jdk8/2/4</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830918/"><strike>functional-tomcat90-mysql57-jdk8/2/5</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/766581/"><strike>functional-tomcat90-mysql57-jdk8/2/6</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/744256/"><strike>functional-tomcat90-mysql57-jdk8/2/7</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/673556/"><strike>functional-tomcat90-mysql57-jdk8/2/8</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456511/"><strike>functional-tomcat90-mysql57-jdk8/2/9</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/863102/"><strike>functional-tomcat90-mysql57-jdk8/2/10</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437622/"><strike>functional-tomcat90-mysql57-jdk8/2/11</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/765063/"><strike>functional-tomcat90-mysql57-jdk8/2/12</stri [...]

2023-11-20 21:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/8331/">test-portal-acceptance-pullrequest(master)#8331</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8331/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>echo<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14401">liferay-echo#14401</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462437245">[master] ci:test:echo - rafaellajordao &gt; liferay-echo - PR#14401 - 2023-11-20[10:14:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/18278/">publish-testray-report#18278</a><br/></div></div>

2023-11-22 00:15 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/WebContentAccessibility.testcase
> +	test RevertSortDirectionOfSearchResultsViaKeyboard {
Migrate to WebContentAdminWithKeyboard

2023-11-22 01:06 UTC, Tim-Cao commented
@rafaellajordao, see changes https://github.com/liferay-echo/liferay-portal/pull/14442

2023-11-22 01:06 UTC, Tim-Cao commented
ci:close

2023-11-22 01:06 UTC, closed without merging