LPS-179001
liferay-echo/liferay-portal pull request #14404
Opened 2023-11-20 13:13 UTC by marcosvictor22

2023-11-20 13:13 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-20 13:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5044/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5044/jenkins-report.html">here</a>.</b></p>

2023-11-20 13:19 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/263958bba46acbeb6e4aa7d0b6281aacf0c70b59">263958bba46acbeb6e4aa7d0b6281aacf0c70b59</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marcosvictor22/liferay-portal/tree/LPS-179001">LPS-179001</a><br/>Branch GIT ID: <a href="https://github.com/marcosvictor22/liferay-portal/commit/cdc82a3da194df18caf78cdf2d33273e3fa76482">cdc82a3da194df18caf78cdf2d33273e3fa76482</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5044/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5044/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-builder/headless-builder-test/src/testFunctional/tests/[UI]AllowUsersToDefineAPIApplicationEndpoints/EditAPIApplicationEndpoint.testcase expected:&lt;...PI.createAPISchema(
     [java] [        apiApplicationERC = "My-app",
     [java]         mainObjectDefinitionERC = "L_API_APPLICATION",
     [java]         name = "firstSchema");
     [java] 
     [java]       SchemaAPI.createAPISchema(
     [java]         apiApplicationERC = "My-app",
     [java]         mainObjectDefinitionERC = "L_API_APPLICATION",
     [java]         name = "secondSchema");
     [java]     \}
     [java] 
     [java]     task ("And Given setting API Schema schema1 in Response Body Schema") \{
     [java]       APIBuilderUI.addAndPublishEndpointConfiguration(
     [java]         entity = "Endpoints",
     [java]         name = "testendpoint",
     [java]         schemaName = "firstSchema",
     [java]         title = "My-app");
     [java] 
     [java]       AssertElementPresent(
     [java]         key_optionName = "firstSchema",
     [java]         locator1 = "ObjectAdmin#LAYOUT_ADD_FIELD_OPTION");]
     [java]     \}
     [java] 
     [java]     task ("When ...&gt; but was:&lt;...PI.createAPISchema(
     [java] [                apiApplicationERC = "My-app",
     [java]                 mainObjectDefinitionERC = "L_API_APPLICATION",
     [java]                 name = "firstSchema");
     [java] 
     [java]             SchemaAPI.createAPISchema(
     [java]                 apiApplicationERC = "My-app",
     [java]                 mainObjectDefinitionERC = "L_API_APPLICATION",
     [java]                 name = "secondSchema");
     [java]     \}
     [java] 
     [java]     task ("And Given setting API Schema schema1 in Response Body Schema") \{
     [java]       APIBuilderUI.addAndPublishEndpointConfiguration(
     [java]         entity = "Endpoints",
     [java]         name = "testendpoint",
     [java]         schemaName = "firstSchema",
     [java]         title = "My-app");
     [java] 
     [java]       AssertElementPresent(
     [java]         key_optionName = "firstSchema",
     [java]         locator1 = "ObjectAdmin#LAYOUT_ADD_FIELD_OPTION");
     [java] ]
     [java]     \}
     [java] 
     [java]     task ("When ...&gt;
     [java] 2: Truncated message :</pre></details></html>

2023-11-20 13:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5044/">test-portal-source-format#5044</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5044/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14404">liferay-echo#14404</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462111789">[master] ci:test:sf - marcosvictor22 &gt; liferay-echo - PR#14404 - 2023-11-20[05:14:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/19319/">publish-testray-report#19319</a><br/></div></div>

2023-11-20 13:32 UTC, marcosvictor22 commented
ci:test:sf

2023-11-20 13:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/977b899d04df122a3f482009ee162404729384cb">977b899d04df122a3f482009ee162404729384cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marcosvictor22/liferay-portal/tree/LPS-179001">LPS-179001</a><br/>Branch GIT ID: <a href="https://github.com/marcosvictor22/liferay-portal/commit/22cfaf6d92c575779e6be786e66ebb6a30d29075">22cfaf6d92c575779e6be786e66ebb6a30d29075</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7743/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7743/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/contentpage/ContentPages.testcase expected:&lt;... is a test for LPS-1[10227 Categories Navigation portlet can be seen within the Section where it was placed and can be opened/configured."
     [java]   @priority = 5
     [java]   test ViewTheNavigationPortletintheContentPaneloftheCurrentExperiencePage \{
     [java]     property portal.acceptance = "true";
     [java] 
     [java]     task ("Given that the user has created a content page") \{
     [java]       JSONWebcontent.addWebContent(
     [java]         content = "Web Content Content",
     [java]         groupName = \$\{randomSiteName\},
     [java]         title = "Web Content Title 1");
     [java] 
     [java]       ContentPagesNavigator.openEditContentPage(
     [java]         pageName = "Test Page Name",
     [java]         siteName = \$\{randomSiteName\});
     [java]     \}
     [java] 
     [java]     task ("Given that the user has created a Publisher portlet") \{
     [java]       PageEditor.addWidget(portletName = "Asset Publisher");
     [java] 
     [java]       Button.clickPublish();
     [java]     \}
     [java] 
     [java]     task ("Then it creates new experience for this page") \{
     [java]       PageEditor.addExperience(
     [java]         experienceName = "New Experience",
     [java]         segmentName = "Anyone");
     [java]     \}
     [java]   \}
     [java] 
     [java]   @description = "This is a test for LPS-154530. View custom values matches in spacing on page editor."
     [java]   @priority = 4
     [java]   test ViewValuesMatchesInSpacingOnPageEditor \{
     [java]     task ("Given a page designer has a content page with default and custom style books") \{
     [java]       task ("Add a style book") \{
     [java]         StyleBooksAdmin.openStyleBooksAdmin(siteURLKey = \$\{siteURLKey\});
     [java] 
     [java]         StyleBooksAdmin.addStyleBooks(styleBookName = "Test Style Book Name");
     [java]       \}
     [java] 
     [java]       task ("Add unit values on Spacing") \{
     [java]         StyleBooks.selectForm(formName = "Spacing");
     [java] 
     [java]         StyleBooks.expandSection(sectionName = "Spacing");
     [java] 
     [java]         StyleBooks.configureUnit(
     [java]           fieldLabel = "Spacer 1",
     [java]           unit = "EM");
     [java] 
     [java]         var i = 0;
     [java] 
     [java]         for (var tokenValue : list "1,2,3") \{</pre></details></html>

2023-11-20 13:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7743/">test-portal-source-format#7743</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7743/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14404">liferay-echo#14404</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462115723">[master] ci:test:sf - marcosvictor22 &gt; liferay-echo - PR#14404 - 2023-11-20[05:33:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/28946/">publish-testray-report#28946</a><br/></div></div>

2023-11-20 19:56 UTC, Tim-Cao commented
ci:test:sf

2023-11-20 19:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3725/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3725/jenkins-report.html">here</a>.</b></p>

2023-11-20 20:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e7ac497675138d9cfcac95e49c5201903bc52f8f">e7ac497675138d9cfcac95e49c5201903bc52f8f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marcosvictor22/liferay-portal/tree/LPS-179001">LPS-179001</a><br/>Branch GIT ID: <a href="https://github.com/marcosvictor22/liferay-portal/commit/ca330ef59bcd30cdd31fbcf6cf4d12e1e05b0e6e">ca330ef59bcd30cdd31fbcf6cf4d12e1e05b0e6e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3725/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3725/jenkins-report.html">here</a>.</h5></details></html>

2023-11-20 20:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3725/">test-portal-source-format#3725</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3725/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14404">liferay-echo#14404</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462376787">[master] ci:test:sf - marcosvictor22 &gt; liferay-echo - PR#14404 - 2023-11-20[11:56:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/14413/">publish-testray-report#14413</a><br/></div></div>

2023-11-20 20:11 UTC, Tim-Cao requested changes
Hi @marcosvictor22, could you update according to comments? Thanks

2023-11-20 20:11 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/contentpage/ContentPages.testcase
> +		property portal.acceptance = "true";
no need

2023-11-20 20:11 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/contentpage/ContentPages.testcase
> +
Add Category Navigation portlet

2023-11-20 20:11 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/contentpage/ContentPages.testcase
> +			Button.clickPublish();
No need to publish

2023-11-20 20:11 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/contentpage/ContentPages.testcase
> +	}
Add steps
1. view Asset Publisher portlet and Category Navigation portlet.
2. Open the configuration modal of Category Navigation

2023-11-20 20:11 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/contentpage/ContentPages.testcase
> +	test ViewTheNavigationPortletintheContentPaneloftheCurrentExperiencePage {
Migrate to ContentPagesWithExperiencePersonalization.testcase then rename to ConfigureCategoryNavigationInNewExperience

2023-11-20 20:11 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/contentpage/ContentPages.testcase
> +	@priority = 5
@priority = 4

2023-11-24 09:32 UTC, Tim-Cao commented
@marcosvictor22, see changes https://github.com/liferay-echo/liferay-portal/pull/14496
One point, we should use automation ticket number in our commit message.

2023-11-24 09:32 UTC, Tim-Cao commented
ci:close

2023-11-24 09:32 UTC, closed without merging