LPS-202110 Substitute AUI code in sample.jspf
liferay-echo/liferay-portal pull request #14408
Opened 2023-11-20 15:09 UTC by BarbaraCabrera

## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-202110)

## Changes

Remove not needed AUI and replace code 

## Test Scenario 1

1. Control Menu > Commerce > Product Management > Products
2. Create a product by choosing Virtual as type
3. Edit the product > Go to Virtual and there is a section called sample

https://github.com/liferay-echo/liferay-portal/assets/93203423/59d2a788-2511-4c94-bff6-3481d8414427

2023-11-20 15:09 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-20 15:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7370/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7370/jenkins-report.html">here</a>.</b></p>

2023-11-20 15:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/977b899d04df122a3f482009ee162404729384cb">977b899d04df122a3f482009ee162404729384cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-202110">LPS-202110</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/88b14194fd00e7db4e41987de0af528346406db4">88b14194fd00e7db4e41987de0af528346406db4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7370/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7370/jenkins-report.html">here</a>.</h5></details></html>

2023-11-20 15:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7370/">test-portal-source-format#7370</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7370/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14408">liferay-echo#14408</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462162362">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#14408 - 2023-11-20[07:11:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/3738/">publish-testray-report#3738</a><br/></div></div>

2023-11-20 15:43 UTC, BarbaraCabrera commented
ci:test:sf

2023-11-20 15:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/4677/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4677/jenkins-report.html">here</a>.</b></p>

2023-11-20 15:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/977b899d04df122a3f482009ee162404729384cb">977b899d04df122a3f482009ee162404729384cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-202110">LPS-202110</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/0eee9bd9aee0f16da9bafce6b89b18397ccaf335">0eee9bd9aee0f16da9bafce6b89b18397ccaf335</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4677/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4677/jenkins-report.html">here</a>.</h5></details></html>

2023-11-20 15:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/6015/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6015/jenkins-report.html">here</a>.</b></p>

2023-11-20 15:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4677/">test-portal-source-format#4677</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4677/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14408">liferay-echo#14408</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462181105">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#14408 - 2023-11-20[07:43:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/17337/">publish-testray-report#17337</a><br/></div></div>

2023-11-20 15:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/977b899d04df122a3f482009ee162404729384cb">977b899d04df122a3f482009ee162404729384cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-202110">LPS-202110</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/dbc657a0560f1bc794ccf570dc47eaa915834535">dbc657a0560f1bc794ccf570dc47eaa915834535</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6015/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6015/jenkins-report.html">here</a>.</h5></details></html>

2023-11-20 15:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6015/">test-portal-source-format#6015</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6015/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14408">liferay-echo#14408</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462183306">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#14408 - 2023-11-20[07:49:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/22974/">publish-testray-report#22974</a><br/></div></div>

2023-11-21 13:41 UTC, p2kmgcl requested changes

2023-11-21 13:41 UTC, p2kmgcl commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +<aui:script sandbox="<%= true %>">
What does the sandbox parameter do? Do we need that?

2023-11-21 13:41 UTC, p2kmgcl commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +	selectSampleFileType();
We should move the function call after it's declaration. It is not needed in JS, but it's a good practice.

2023-11-21 13:41 UTC, p2kmgcl commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +	useSampleCheckbox.addEventListener('click', () => {
We can directly pass the selectSampleFileType function here without creating a new arrow function.

2023-11-21 13:41 UTC, p2kmgcl commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +		const sampleFiles = document.getElementById(
Shouldn't this be call `sampleFile`, without the s?

2023-11-21 13:41 UTC, p2kmgcl commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +		const sampleURL = document.getElementById('<portlet:namespace />sampleURL');
I would rename this to something like "sampleURLInput" or something similar that indicates that this is not actually an URL object.

2023-11-21 13:41 UTC, p2kmgcl commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +				: sampleURL.removeAttribute('disabled');
We should not use short if statements for function logic (not an assignment), it is harded to read and not much sorter.

Also, the disabled attribute is a boolean attribute, it should be good enough to set it to '' (`setAttribute('disabled', '')`) instead of forcing converting the "true" parameter to string, which we don't need.

2023-11-21 13:46 UTC, BarbaraCabrera commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +<aui:script sandbox="<%= true %>">
The sandbox it's because this jsp is loaded twice and that avoid the console error (in dev tools) of _"this variable has been declared before"_.
I don't know if there is any other way to avoid it 🤔

2023-11-21 13:48 UTC, BarbaraCabrera commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +		const sampleFiles = document.getElementById(
Yes, it's a misspelling 🤓

2023-11-21 13:50 UTC, BarbaraCabrera commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +		const sampleURL = document.getElementById('<portlet:namespace />sampleURL');
I used this name because it's the same one that is used in line 94

2023-11-21 13:50 UTC, BarbaraCabrera commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +		const sampleURL = document.getElementById('<portlet:namespace />sampleURL');
I used this name because we already use it in line 94 🤔

2023-11-21 14:20 UTC, p2kmgcl commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +		const sampleURL = document.getElementById('<portlet:namespace />sampleURL');
Then we should update line 94 too :sweat_smile:

2023-11-21 14:24 UTC, p2kmgcl commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +<aui:script sandbox="<%= true %>">
mmm I see, so the script tags are being put in the document with no encapsulation...

2023-11-21 14:25 UTC, p2kmgcl commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/sample.jspf
> +<aui:script sandbox="<%= true %>">
ok this is what sandbox parameter is doing: https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/aui/ScriptTag.java#L117-L130

Do you think we can mimic this behavior without using the sandbox property?

2023-11-22 15:51 UTC, BarbaraCabrera commented
ci:test:sf

2023-11-22 15:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/4841/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4841/jenkins-report.html">here</a>.</b></p>

2023-11-22 15:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38131bd1c68de68ae139a595824a7acdf2191b2c">38131bd1c68de68ae139a595824a7acdf2191b2c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-202110">LPS-202110</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/1e8c81a5fa0330c5a0dda15d720b3f84a5d9bc19">1e8c81a5fa0330c5a0dda15d720b3f84a5d9bc19</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/4841/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4841/jenkins-report.html">here</a>.</h5></details></html>

2023-11-23 08:45 UTC, p2kmgcl approved these changes

2023-11-23 11:39 UTC, andrea-ale-sbarra approved these changes
LGTM.
Thank you!

2023-11-23 12:20 UTC, BarbaraCabrera commented
ci:forward

2023-11-23 12:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-11-23 12:21 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2023-11-23 12:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/10831/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10831/jenkins-report.html">here</a>.</b></p>

2023-11-23 14:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 31 out of 31 jobs passed</h3><h3>:x: ci:test:relevant - 266 out of 279 jobs passed in 2 hours 10 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/188">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_10831</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/15a3d25cab51bc76fc8f8f57b7638797a88c1980">15a3d25cab51bc76fc8f8f57b7638797a88c1980</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/64225f6a078f09336d5580403dab175b68d3c9d9">64225f6a078f09336d5580403dab175b68d3c9d9</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463960681">EE Development Acceptance (master) - 186 - 2023-11-22[16:39:47]</a></p><details><summary><strong>ci:test:stable - 31 out of 31 jobs PASSED</strong></summary><details><summary><strong>31 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 266 out of 279 jobs PASSED</strong></summary><div><h4>13 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/10831/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/823158/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/733307/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307227/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771695/"><strike>functional-smoke-tomcat90-db2115-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/353030/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/823159/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314959/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/320240/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/316278/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/867439/">functional-smoke-tomcat90-postgresql153-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/794609/"><strike>functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/749398/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/299821/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307226/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332510/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314952/">functional-tomcat90-mysql57-chrome100-jdk8/0/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/677238/">functional-tomcat90-mysql57-chrome100-jdk8/0/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/733306/">functional-tomcat90-mysql57-chrome100-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/794612/">functional-tomcat90-mysql57-chrome100-jdk8/0/5</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314950/">functional-tomcat90-mysql57-chrome100-jdk8/0/6</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332509/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/7</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/677237/">functional-tomcat90-mysql57-chrome100-jdk8/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/823162/">functional-tomcat90-mysql57-chrome100-jdk8/0/9</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/823169/">functional-tomcat90-mysql57-chrome100-jdk8/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708764/">functional-tomcat90-mysql57-chrome100-jdk8/0/11</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771699/">functional-tomcat90-mysql57-chrome100-jdk8/0/12</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462333/">functional-tomcat90-mysql57-chrome100-jdk8/0/13</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/318881/">functional-tomcat90-mysql57-chrome100-jdk8/0/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708765/">functional-tomcat90-mysql57-chrome100-jdk8/0/15</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771701/">functional-tomcat90-mysql57-chrome100-jdk8/0/16</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/785956/">functional-tomcat90-mysql57-chrome100-jdk8/0/17</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771700/">functional-tomcat90-mysql57-chrome100-jdk8/0/18</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/330270/">functional-tomcat90-mysql57-chrome100-jdk8/0/19</a></ [...]

2023-11-23 14:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/10831/">test-portal-acceptance-pullrequest(master)#10831</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10831/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14408">liferay-echo#14408</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2464139050">[master] ci:test:relevant - BarbaraCabrera &gt; liferay-echo - PR#14408 - 2023-11-23[04:28:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/23348/">publish-testray-report#23348</a><br/></div></div>

2023-11-23 15:19 UTC, BarbaraCabrera commented
ci:forward:force

2023-11-23 15:19 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2023-11-23 15:20 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-32.liferay.com/job/forward-pullrequest/1431//consoleFull)

2023-11-23 15:20 UTC, closed without merging

2023-11-23 15:20 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/144293
[Console](https://test-1-32.liferay.com/job/forward-pullrequest/1431//consoleFull)