LPS-196141
liferay-echo/liferay-portal pull request #14415
Opened 2023-11-20 17:34 UTC by rafaellajordao

2023-11-20 17:34 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-20 17:34 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-20 17:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/6895/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6895/jenkins-report.html">here</a>.</b></p>

2023-11-20 17:41 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/977b899d04df122a3f482009ee162404729384cb">977b899d04df122a3f482009ee162404729384cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-196141">LPS-196141</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/5c5eb64e17fb7b134b4bc10f0d59b890813c5063">5c5eb64e17fb7b134b4bc10f0d59b890813c5063</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/6895/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6895/jenkins-report.html">here</a>.</h5></details></html>

2023-11-20 17:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-source-format/6895/">test-portal-source-format#6895</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6895/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14415">liferay-echo#14415</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462318299">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#14415 - 2023-11-20[09:35:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/3642/">publish-testray-report#3642</a><br/></div></div>

2023-11-20 19:54 UTC, Tim-Cao requested changes
Hi @rafaellajordao, could you update according to comments? Thanks

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +		property custom.properties = "lock.expiration.time.com.lliferay.portal.kernel.model.Layout=6000";
Deprecated property

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminAccessibility.testcase
> +		}
No need

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminAccessibility.testcase
> +	test ViewLockedPagesInstanceSettingsAccessibility {
Rename to ViewAccessibilityOfLockedPagesUnderInstanceSettings

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +	test EnableAllowAutomaticUnlockingProcessViaKeyboard {
Rename to EnableAllowAutomaticUnlockingProcessUnderInstanceSettingsViaKeyboard

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +	test ViewTimeWithoutAutosave {
Rename to ConfigureTimeWithoutAutosaveUnderInstanceSettings

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				locator1 = "ToggleSwitch#ANY_TOGGLE_SWITCH",
Use previous element

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				locator1 = "ToggleSwitch#ANY_TOGGLE_SWITCH",
Use previous element

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				value1 = "\TAB");
No need

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				locator1 = "Button#ANY",
Use previous element

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				value1 = 7);
Alert.viewSuccessMessage

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				locator1 = "Button#ANY",
Use previous element

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				locator1 = "Header#H1_TITLE");
ControlMenu.viewHeaderTitle

2023-11-20 19:54 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +				value1 = "");
No need

2023-11-21 14:52 UTC, Tim-Cao requested changes

2023-11-21 14:52 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +			Alert.viewSpecificRequiredField(fieldFieldLabel = "Time Without Autosave");
```
				AssertVisible(
					key_alertMessage = "The Time Without Autosave field is required.",
					locator1 = "Message#ERROR_ENTER_A_VALID_VALUE");
```

2023-11-21 14:52 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +				value1 = "");
```
				AssertVisible(
					key_alertMessage = "The Time Without Autosave field is required.",
					locator1 = "Message#ERROR_ENTER_A_VALID_VALUE");
```

2023-11-21 14:52 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +				value1 = "Please enter a value greater than or equal to 1.");
```
				AssertVisible(
					key_alertMessage = "Please enter a value greater than or equal to 1.",
					locator1 = "Message#ERROR_ENTER_A_VALID_VALUE");
```

2023-11-21 14:52 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/lockedpages/LockedPages.testcase
> +				value1 = "Please enter a value less than or equal to 99999.");
```
				AssertVisible(
					key_alertMessage = "Please enter a value less than or equal to 99999.",
					locator1 = "Message#ERROR_ENTER_A_VALID_VALUE");
```

2023-11-21 23:50 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				locator1 = "//label[contains(@class,'toggle-switch')]",
The previous element should be 
![image](https://github.com/liferay-echo/liferay-portal/assets/52661397/1070ed91-5638-4058-876d-a658eb1c4b76)

@rafaellajordao

2023-11-22 00:06 UTC, Tim-Cao commented
@rafaellajordao, see changes https://github.com/liferay-echo/liferay-portal/pull/14440

2023-11-22 00:06 UTC, Tim-Cao commented
ci:close

2023-11-22 00:06 UTC, closed without merging

2023-11-22 11:55 UTC, rafaellajordao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/LockedPagesAdminWithKeyboard.testcase
> +				locator1 = "//label[contains(@class,'toggle-switch')]",
Ohhh now I understand!
I was understanding that if I was using a //span I should change to using a //div, I had understood that this was the "previous element".
Thank you very much Tim, I promise that next time I will do it the right way! @Tim-Cao