LPS-199294
liferay-echo/liferay-portal pull request #14416
Opened 2023-11-20 18:00 UTC by alessandromalves

2023-11-20 18:00 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-20 18:00 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-20 18:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2175/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2175/jenkins-report.html">here</a>.</b></p>

2023-11-20 18:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/977b899d04df122a3f482009ee162404729384cb">977b899d04df122a3f482009ee162404729384cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LPS-199294">LPS-199294</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/ef89ae03ad8710975f1bf692341d254de0826a51">ef89ae03ad8710975f1bf692341d254de0826a51</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2175/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2175/jenkins-report.html">here</a>.</h5></details></html>

2023-11-20 20:23 UTC, alessandromalves commented
ci:test:sf

2023-11-20 20:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3728/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3728/jenkins-report.html">here</a>.</b></p>

2023-11-20 20:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e9ea030d719a24dc7becff3825a0ca4273cbacaf">e9ea030d719a24dc7becff3825a0ca4273cbacaf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LPS-199294">LPS-199294</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/be0bc73c74f11bdd04f633441ea50fdc1fca73b3">be0bc73c74f11bdd04f633441ea50fdc1fca73b3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3728/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3728/jenkins-report.html">here</a>.</h5></details></html>

2023-11-20 20:37 UTC, Tim-Cao requested changes
Hi @alessandromalves, could you update according to comments? Thanks

2023-11-20 20:37 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPageTemplatesForObject.testcase
> +		property custom.properties = "feature.flag.LPS-181663=true${line.separator}feature.flag.LPS-183727=true${line.separator}feature.flag.LPS-195205=true";
Same as above

2023-11-20 20:37 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPageTemplatesForObject.testcase
> +				objectName = "PurchaseOrder");
No need

2023-11-20 20:37 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPageTemplatesForObject.testcase
> +				locator1 = "CKEditor#BODY_TEXT");
No need

2023-11-20 20:37 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPageTemplatesForObject.testcase
> +				fieldLabel = "Title");
No need

2023-11-20 20:37 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPageTemplatesForObject.testcase
> +
Add step to assert redirect to the display page

2023-11-20 20:37 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPageTemplatesForObject.testcase
> +	test ViewMultiselectListFragmentDisplaySuccessWithEntryFieldEmpty {
ViewMultiselectListWithEntryFieldEmptyOnAssociatedDisplayPageTemplate

2023-11-20 20:37 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPageTemplatesForObject.testcase
> +	test ViewSelectFromListFragmentDisplaySuccessWithEntryFieldEmpty {
ViewSelectFromListWithEntryFieldEmptyOnAssociatedDisplayPageTemplate

2023-11-20 20:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3728/">test-portal-source-format#3728</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3728/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14416">liferay-echo#14416</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462402166">[master] ci:test:sf - alessandromalves &gt; liferay-echo - PR#14416 - 2023-11-20[12:23:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/14418/">publish-testray-report#14418</a><br/></div></div>

2023-11-22 19:20 UTC, alessandromalves commented
ci;reopen

2023-11-22 19:20 UTC, alessandromalves commented
ci:reopen

2023-11-22 19:27 UTC, alessandromalves commented
Hi @Tim-Cao, I needed to update `JSONObject.getObjectEntryId macro` to make it work when `entryValue` is empty. However, even with the change, it didn't work when the field is an select-from-list. Do you know how I can fix this? Thanks in advance!

2023-11-22 19:27 UTC, alessandromalves commented
ci:test:sf

2023-11-22 19:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/5045/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/5045/jenkins-report.html">here</a>.</b></p>

2023-11-22 19:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/091180b85b554b0233b4d5c6358d1513f5c5fc78">091180b85b554b0233b4d5c6358d1513f5c5fc78</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LPS-199294">LPS-199294</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/4bf5828a6fbfbb9594f90b446d0bf9b2de9eea05">4bf5828a6fbfbb9594f90b446d0bf9b2de9eea05</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/5045/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/5045/jenkins-report.html">here</a>.</h5></details></html>

2023-11-22 19:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/5045/">test-portal-source-format#5045</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/5045/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14416">liferay-echo#14416</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463683108">[master] ci:test:sf - alessandromalves &gt; liferay-echo - PR#14416 - 2023-11-22[11:28:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/4352/">publish-testray-report#4352</a><br/></div></div>

2023-11-23 02:39 UTC, Tim-Cao commented
@alessandromalves, see changes https://github.com/liferay-echo/liferay-portal/pull/14466

2023-11-23 02:39 UTC, Tim-Cao commented
ci:close

2023-11-23 02:40 UTC, closed without merging