LPS-173648 Automation for LPS-171989 JS Polution Vulnerability
liferay-echo/liferay-portal pull request #14474
Opened 2023-11-23 13:46 UTC by AkramYoussoufi

- [Automation Request](https://liferay.atlassian.net/browse/LPS-173648)
- [Ticket](https://liferay.atlassian.net/browse/LPS-171989)

2023-11-23 13:47 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-23 13:47 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-23 13:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/6106/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6106/jenkins-report.html">here</a>.</b></p>

2023-11-23 13:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/15a3d25cab51bc76fc8f8f57b7638797a88c1980">15a3d25cab51bc76fc8f8f57b7638797a88c1980</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AkramYoussoufi/liferay-portal/tree/LPS-173648">LPS-173648</a><br/>Branch GIT ID: <a href="https://github.com/AkramYoussoufi/liferay-portal/commit/d6f0f87fe874f12060c06b3e506224a57aa23e93">d6f0f87fe874f12060c06b3e506224a57aa23e93</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6106/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6106/jenkins-report.html">here</a>.</h5></details></html>

2023-11-23 13:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6106/">test-portal-source-format#6106</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6106/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14474">liferay-echo#14474</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2464110057">[master] ci:test:sf - AkramYoussoufi &gt; liferay-echo - PR#14474 - 2023-11-23[05:47:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/23347/">publish-testray-report#23347</a><br/></div></div>

2023-11-23 22:12 UTC, Tim-Cao requested changes
Hi @AkramYoussoufi, Good job! Would you mind updating according to comments? Thanks

2023-11-23 22:12 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/misc/iframe/IFrame.testcase
> +	@description = "This is a use case for LPS-171989"
Add simple description for test

2023-11-23 22:12 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/misc/iframe/IFrame.testcase
> +	@priority = 3
@priority =4 should same with bug ticket

2023-11-23 22:12 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/misc/iframe/IFrame.testcase
> +	test VerifyFramJSPolutionVulnerability {
Move to a new file IFrameWithXSS.testcase then rename to NavigateToSourceURLWithXSS

2023-11-23 22:12 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/misc/iframe/IFrame.testcase
> +			BlogsConfiguration.selectConfigurationIFrame();
IFrame.selectConfigurationFrame

2023-11-23 22:12 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/misc/iframe/IFrame.testcase
> +				value1 = "http://${portalURL}:8080/web/guest/home");
InputField.editText

2023-11-23 22:12 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/misc/iframe/IFrame.testcase
> +				siteName = "Test Site Name");
Iframe.closeFrame

2023-11-23 22:12 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/misc/iframe/IFrame.testcase
> +		var portalURL = Regex.removePortNumber(url = ${portalURL});
`var portalURL = PropsUtil.get("portal.url");`

2023-11-23 22:12 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/misc/iframe/IFrame.testcase
> +				value1 = "http://${portalURL}:8080/web/guest/home");
value1 = "https://www.liferay.com"

2023-11-23 22:12 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/misc/iframe/IFrame.testcase
> +			Open.openInTheNewTab(value1 = "http://${portalURL}:8080/web/test-site-name#constructor[prototype][comboBase]=data%3A%2Calert%281%29");
`Open.openInTheNewTab(value1 = "${portalURL}/web/test-site-name/test-page-name#constructor[prototype][comboBase]=data%3A%2Calert%281%29");`

2023-11-24 09:23 UTC, AkramYoussoufi commented
ci:test:sf

2023-11-24 09:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/5664/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5664/jenkins-report.html">here</a>.</b></p>

2023-11-24 09:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1206b917ad645129beaaebf7186bac2091a8648">c1206b917ad645129beaaebf7186bac2091a8648</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AkramYoussoufi/liferay-portal/tree/LPS-173648">LPS-173648</a><br/>Branch GIT ID: <a href="https://github.com/AkramYoussoufi/liferay-portal/commit/17fcc25ad8d930a1c7359a3ed2ecee9ed6d5e5fc">17fcc25ad8d930a1c7359a3ed2ecee9ed6d5e5fc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5664/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5664/jenkins-report.html">here</a>.</h5></details></html>

2023-11-24 09:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5664/">test-portal-source-format#5664</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5664/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14474">liferay-echo#14474</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2464687337">[master] ci:test:sf - AkramYoussoufi &gt; liferay-echo - PR#14474 - 2023-11-24[01:23:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/4389/">publish-testray-report#4389</a><br/></div></div>

2023-11-24 09:45 UTC, Tim-Cao commented
@AkramYoussoufi, see changes https://github.com/liferay-echo/liferay-portal/pull/14497

2023-11-24 09:45 UTC, Tim-Cao commented
ci:close

2023-11-24 09:45 UTC, closed without merging