LPS 198045
liferay-echo/liferay-portal pull request #14476
Opened 2023-11-23 14:46 UTC by Beatlray

- LPS-198045 add ViewBackButtonTooltipInInformationTemplateAndWidgetTemplate test
- LPS-198045 add ViewBackButtonTooltipInInformationTemplateAndWidgetTemplateViaKeyboard test

2023-11-23 14:46 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-11-23 21:38 UTC, Tim-Cao commented
ci:test:sf

2023-11-23 21:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/7288/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7288/jenkins-report.html">here</a>.</b></p>

2023-11-23 21:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/58b28fa099637e5ff974bc3d9161f94307fbdb3c">58b28fa099637e5ff974bc3d9161f94307fbdb3c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Beatlray/liferay-portal/tree/LPS-198045">LPS-198045</a><br/>Branch GIT ID: <a href="https://github.com/Beatlray/liferay-portal/commit/78b726a25d4243c87349145c417bce3ae062b28a">78b726a25d4243c87349145c417bce3ae062b28a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7288/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7288/jenkins-report.html">here</a>.</h5></details></html>

2023-11-23 21:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7288/">test-portal-source-format#7288</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7288/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14476">liferay-echo#14476</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2464475207">[master] ci:test:sf - Beatlray &gt; liferay-echo - PR#14476 - 2023-11-23[13:38:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/4542/">publish-testray-report#4542</a><br/></div></div>

2023-11-23 21:59 UTC, Tim-Cao requested changes
Hi @Beatlray, Good job! Would you mind updating according to comments? Thanks

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/InformationTemplatesAccessibility.testcase
> +				portlet = "Templates");
Use url navigation
`InformationTemplates.openInformationTemplatesAdmin(siteURLKey = "test-site-name");`

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/InformationTemplatesAccessibility.testcase
> +				value1 = "Go to Templates");
```
				AssertVisible(
					key_content = "Go to Templates",
					locator1 = "Tooltip#FLOATING_TOOLTIP_CONTENT");
```

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/InformationTemplatesAccessibility.testcase
> +		task ("When accesing the back button via keyboard navigation") {
When focus on the back button via keyboard

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/InformationTemplatesAccessibility.testcase
> +			Navigator.gotoNavTab(navTab = "Widget Templates");
Same as above
`ApplicationDisplayTemplates.openWidgetTemplatesAdmin(siteURLKey = "test-site-name");`

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/InformationTemplatesAccessibility.testcase
> +				locator1 = "DDMEditTemplate#SCRIPT_FIELD");
No need

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/InformationTemplatesAccessibility.testcase
> +				value1 = "Go to Templates");
Same as above

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/InformationTemplatesAccessibility.testcase
> +	test ViewBackButtonTooltipInInformationTemplateAndWidgetTemplateViaKeyboard {
Break into two cases one in InformationTemplatesWithKeyboard.testcase with `property testray.main.component.name = "Templates";` another in ApplicationDisplayTemplatesWithKeyboard.testcase
then rename cases to
ViewBackButtonTooltipInInformationTemplateEditorViaKeyboard and ViewBackButtonTooltipInWidgetTemplateEditorViaKeyboard

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/informationtemplate/InformationTemplates.testcase
> +	test ViewBackButtonTooltipInInformationTemplateAndWidgetTemplate {
Break into two cases, one in InformationTemplates.testcase, another in ApplicationDIsplayTemplates.testcase
ViewBackButtonTooltipInInformationTemplateEditor and ViewBackButtonTooltipInWidgetTemplateEditor

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/informationtemplate/InformationTemplates.testcase
> +				portlet = "Templates");
Same

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/informationtemplate/InformationTemplates.testcase
> +				value1 = "Go to Templates");
Same

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/informationtemplate/InformationTemplates.testcase
> +				portlet = "Templates");
Same

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/informationtemplate/InformationTemplates.testcase
> +				locator1 = "DDMEditTemplate#SCRIPT_FIELD");
Same

2023-11-23 21:59 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/informationtemplate/InformationTemplates.testcase
> +				value1 = "Go to Templates");
Same

2023-11-24 08:09 UTC, david-gutierrez-mesa requested changes

2023-11-24 08:09 UTC, david-gutierrez-mesa commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/accessiblity/InformationTemplatesAccessibility.testcase
> +	test ViewBackButtonTooltipInInformationTemplateAndWidgetTemplateViaKeyboard {
since this is only to check the back button label, can't we create a single test somewhere else (or create a new .testcase)? That way it's going to be faster since we don't need to execute a lot of tests but only one

2023-12-13 03:57 UTC, Tim-Cao commented
See https://github.com/liferay-echo/liferay-portal/pull/14697

2023-12-13 03:57 UTC, Tim-Cao commented
ci:close

2023-12-13 03:57 UTC, closed without merging