LPS-202929 Update the translation when the event from localized input is heard
liferay-echo/liferay-portal pull request #14650
Opened 2023-12-07 10:55 UTC by veroglez

This PR depends on https://github.com/liferay-echo/liferay-portal/pull/14573. Just to review from 416a2fa5b85d3c3efabe35b8bfa36b592c1cecb1

2023-12-07 10:55 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-12-07 10:55 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-12-07 10:57 UTC, veroglez commented
ci:test:sf

2023-12-07 10:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7873/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7873/jenkins-report.html">here</a>.</b></p>

2023-12-07 11:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee2717f38bb6f171e594caaa0bcc70a934330ded">ee2717f38bb6f171e594caaa0bcc70a934330ded</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/veroglez/liferay-portal/tree/LPS-202929">LPS-202929</a><br/>Branch GIT ID: <a href="https://github.com/veroglez/liferay-portal/commit/cc3df3097bd7270303f31b6749b024af9818ecc9">cc3df3097bd7270303f31b6749b024af9818ecc9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3981/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3981/jenkins-report.html">here</a>.</h5></details></html>

2023-12-07 11:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7873/">test-portal-source-format#7873</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7873/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14650">liferay-echo#14650</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2471746475">[master] ci:test:sf - veroglez &gt; liferay-echo - PR#14650 - 2023-12-07[02:57:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/29390/">publish-testray-report#29390</a><br/></div></div>

2023-12-13 14:20 UTC, p2kmgcl requested changes

2023-12-14 07:45 UTC, veroglez commented on modules/apps/layout/layout-js-components-web/src/main/resources/META-INF/resources/js/components/translation_selector/TranslationSelector.tsx
> +		{selectedItem, ...otherProps}: {selectedItem: Language},
I remove this component in this commit f56dcdaa809cf1ca824d59a95d9c51d3e666c64f, it's just that it was in a PR that had already passed :sweat_smile:

2023-12-14 07:50 UTC, veroglez commented on modules/apps/layout/layout-js-components-web/src/main/resources/META-INF/resources/js/components/translation_selector/TranslationSelector.tsx
> +	[key: string]: Record<Liferay.Language.Locale, string>;
Same here, the component is `TranslationSelector` :sweat:

2023-12-14 07:52 UTC, veroglez commented on modules/apps/layout/layout-js-components-web/src/main/resources/META-INF/resources/js/components/translation_selector/TranslationSelector.tsx
> +	const getSelectedLanguage = (id: React.Key) =>
Same here

2023-12-14 07:52 UTC, veroglez commented on modules/apps/layout/layout-js-components-web/src/main/resources/META-INF/resources/js/components/translation_selector/TranslationSelector.tsx
> +	const items = translations
Same here

2023-12-14 08:51 UTC, veroglez commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/translation_manager/TranslationManager.tsx
> +					)
Added!

2023-12-14 09:04 UTC, veroglez commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/translation_manager/TranslationManager.tsx
> +		Liferay.on('inputLocalized:updateTranslationStatus', () =>
that's true!

2023-12-14 09:22 UTC, veroglez commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/translation_manager/TranslationManager.tsx
> +			onSelectedLanguageIdChange={(id) => setSelectedLanguageId(id)}
yess! that's true!

2023-12-15 08:37 UTC, p2kmgcl commented on modules/apps/frontend-js/frontend-js-components-web/src/main/resources/META-INF/resources/translation_manager/TranslationAdminSelector.tsx
> +	horizontalDisplay?: boolean;
@veroglez :smiling_face_with_tear:

2023-12-15 08:38 UTC, p2kmgcl commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/css/main.scss
> +				width: 115px;
@veroglez :smiling_face_with_tear:

2023-12-15 09:09 UTC, veroglez commented on modules/apps/layout/layout-js-components-web/src/main/resources/META-INF/resources/js/components/translation_selector/StatusLabel.tsx
> +	else if (item.translations) {
This component is also removed

2023-12-18 13:09 UTC, veroglez commented
Sent here https://github.com/liferay-echo/liferay-portal/pull/14738

2023-12-18 13:09 UTC, closed without merging