LPS-198159
liferay-echo/liferay-portal pull request #14833
Opened 2023-12-27 13:51 UTC by rafaellajordao

2023-12-27 13:51 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2023-12-27 13:51 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-12-27 13:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/6943/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6943/jenkins-report.html">here</a>.</b></p>

2023-12-27 14:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3286a7e4ad96c33578cfdd3f17a8101cd8c9b5ec">3286a7e4ad96c33578cfdd3f17a8101cd8c9b5ec</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-198159">LPS-198159</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/a41dc39619a66c63d54e0144f83a773a9e3a931d">a41dc39619a66c63d54e0144f83a773a9e3a931d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/6943/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6943/jenkins-report.html">here</a>.</h5></details></html>

2023-12-27 14:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-source-format/6943/">test-portal-source-format#6943</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6943/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/14833">liferay-echo#14833</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2479835064">[master] ci:test:sf - rafaellajordao &gt; liferay-echo - PR#14833 - 2023-12-27[05:56:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2479835064<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/3692/">publish-testray-report#3692</a><br/></div></div>

2023-12-27 23:47 UTC, Tim-Cao requested changes
Hi @rafaellajordao, would you mind updating according to comments? Thanks

2023-12-27 23:47 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +				sourceFileName = "Document_1.txt");
No need

2023-12-27 23:47 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +				groupName = "Test Site Name");
No need

2023-12-27 23:47 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +
Add steps to add a display page template for Web Content Article and Basic Web Content then associate display page to web content

2023-12-27 23:47 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +	test ViewBackButtonTooltipInContentDashboard {
ViewBackButtonTooltipInAssociatedDisplayPageTemplate

2023-12-27 23:47 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboardWithKeyboard.testcase
> +	test ViewBackButtonTooltipInContentDashboardViaKeyboard {
ViewBackButtonTooltipInAssociatedDisplayPageTemplateViaKeyboard

2023-12-27 23:47 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboardWithKeyboard.testcase
> +				groupName = "Test Site Name");
Same with above

2023-12-27 23:47 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +		}
No need

2023-12-27 23:47 UTC, Tim-Cao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboard.testcase
> +	}
No need

2024-01-03 14:52 UTC, Tim-Cao commented
@rafaellajordao Good job! See changes https://github.com/liferay-echo/liferay-portal/pull/14891

2024-01-03 14:52 UTC, closed without merging