LPD-27001 Add a test for Slow Page Loading if Many Page Created from Page Template
liferay-echo/liferay-portal pull request #15723
Opened 2024-05-29 06:28 UTC by JavierMoral

https://liferay.atlassian.net/browse/LPD-27001

I tried to follow the same approach than #15717 not only testing the use case described in the original performance issue: https://liferay.atlassian.net/browse/LPS-199141 but also adding a timer that measures how long it takes to render one of the many pages created using the same page template.

2024-05-29 06:28 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-05-29 06:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/5429/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5429/jenkins-report.html">here</a>.</b></p>

2024-05-29 06:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a575fb5bd9f816dc787544770f0b496593ce981f">a575fb5bd9f816dc787544770f0b496593ce981f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JavierMoral/liferay-portal/tree/LPD-27001">LPD-27001</a><br/>Branch GIT ID: <a href="https://github.com/JavierMoral/liferay-portal/commit/eddabf4fa321bc7fba5b79de85ba01c6b62b88bc">eddabf4fa321bc7fba5b79de85ba01c6b62b88bc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5429/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5429/jenkins-report.html">here</a>.</h5></details></html>

2024-05-29 06:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5429/">test-portal-source-format#5429</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5429/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/15723">liferay-echo#15723</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2573131491">[master] ci:test:sf - JavierMoral &gt; liferay-echo - PR#15723 - 2024-05-28[23:36:44]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2573131491<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/5706/">publish-testray-report#5706</a><br/></div></div>

2024-05-29 09:37 UTC, lfbesada requested changes
@JavierMoral Good job :clap: I have added some comments basically about source formatting and a suggestion to improve the performance evaluation capability.

2024-05-29 09:37 UTC, lfbesada commented on modules/apps/layout/layout-test/src/testIntegration/java/com/liferay/layout/test/LayoutTypeContentTest.java
> +			);
We shouldn't chain the method invocation instead use a variable each time

2024-05-29 09:37 UTC, lfbesada commented on modules/apps/layout/layout-test/src/testIntegration/java/com/liferay/layout/test/LayoutTypeContentTest.java
> +				_getContent("test test some"));
Why do we need specific content in the article? I think you can use instead 
```
JournalTestUtil.addArticle(
			_group.getGroupId(), JournalFolderConstants.DEFAULT_PARENT_FOLDER_ID)
```

2024-05-29 09:37 UTC, lfbesada commented on modules/apps/layout/layout-test/src/testIntegration/java/com/liferay/layout/test/LayoutTypeContentTest.java
> +			Layout templateLayout = _layoutLocalService.fetchLayout(
I think this should be renamed to layout

2024-05-29 09:37 UTC, lfbesada commented on modules/apps/layout/layout-test/src/testIntegration/java/com/liferay/layout/test/LayoutTypeContentTest.java
> +					serviceContext);
Maybe here we could add an assert after that to ensure that the portlet has been installed in the layout

2024-05-29 09:37 UTC, lfbesada commented on modules/apps/layout/layout-test/src/testIntegration/java/com/liferay/layout/test/LayoutTypeContentTest.java
> +			Assert.assertEquals(templateContent, content);
Since the goal is to evaluate the worsening of performance when the number of pages that have used the template increases, I think this should be moved to the loop that creates the pages and evaluated at each iteration. That way we can check how much worse it gets in each iteration. What do you think?

2024-05-29 09:41 UTC, lfbesada commented on modules/apps/layout/layout-test/src/testIntegration/java/com/liferay/layout/test/LayoutTypeContentTest.java
> +	private static final int _CREATED_LAYOUTS = 5;
I think _NUMBER_LAYOUTS is a better name, what do you think?

2024-05-30 08:07 UTC, JavierMoral commented
Hi @lfbesada , thank you for your feedback :heart: I applied all your suggestions. Please tell what you think of these changes now. 
Best regards

2024-05-30 10:21 UTC, lfbesada approved these changes
@JavierMoral Great job! :star_struck:

2024-05-30 10:21 UTC, lfbesada commented
ci:forward

2024-05-30 10:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-05-30 10:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7745/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7745/jenkins-report.html">here</a>.</b></p>

2024-05-30 10:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/237d81e5f404028bc8707bba2abe66df65c60435">237d81e5f404028bc8707bba2abe66df65c60435</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JavierMoral/liferay-portal/tree/LPD-27001">LPD-27001</a><br/>Branch GIT ID: <a href="https://github.com/JavierMoral/liferay-portal/commit/64e5d3409a441b5529c33b94a19740940cda5bd5">64e5d3409a441b5529c33b94a19740940cda5bd5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7745/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7745/jenkins-report.html">here</a>.</h5></details></html>

2024-05-30 10:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7745/">test-portal-source-format#7745</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7745/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/15723">liferay-echo#15723</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2573641580">[master] ci:test:sf - JavierMoral &gt; liferay-echo - PR#15723 - 2024-05-30[03:22:12]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2573641580<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4111/">publish-testray-report#4111</a><br/></div></div>

2024-05-30 10:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/16943/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/16943/jenkins-report.html">here</a>.</b></p>

2024-05-30 11:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 4 out of 4 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 19 out of 21 jobs passed in 1 hour 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/237d81e5f404028bc8707bba2abe66df65c60435">237d81e5f404028bc8707bba2abe66df65c60435</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/924fac35446c40561c2a4de32f72a794a735e614">924fac35446c40561c2a4de32f72a794a735e614</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2573555207">EE Development Acceptance (master) - 566 - 2024-05-29[16:39:26]</a></p><details><summary><strong>ci:test:stable - 4 out of 4 jobs PASSED</strong></summary><details><summary><strong>4 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 18 out of 21 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/16943/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/895563/">modules-integration-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999464/">modules-integration-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/883806/"><strike>modules-integration-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/839737/"><strike>modules-integration-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1119573/">modules-integration-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965030/">modules-integration-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1119572/">modules-integration-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965029/">modules-integration-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902049/">modules-integration-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999462/">modules-integration-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/883807/">modules-integration-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013877/">modules-integration-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999463/">modules-integration-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929343/">modules-integration-mysql57-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902050/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965032/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013878/">modules-unit-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965031/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>unit-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1119571/">unit-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1119574/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>18 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/16943/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/883806//consoleText">modules-integration-mysql57-jdk8/0/2</a><pre>[stopwatch] [run.batch.test.action: 1.425 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:373: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:385: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:16679: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:7623: Task [sequential] failed after [2] attempts; giving up.
     [echo] Error messages:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:7662: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:7597: Unable to start docker container:
     [echo] docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: no cgroup mount found in mountinfo: unknown.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:7662: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:7597: Unable to start docker container:
     [echo] docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: no cgroup mount found in mountinfo: unknown.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:7662: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:7597: Unable to start docker container:
     [echo] docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: no cgroup mount found in mountinfo: unknown.
      [get] Getting: http://test-1-38/job/test-portal-acceptance-pullrequest-downstream(master)/883806//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240530042048174.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240530042048174.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1532046010.properties</pre><ol><li><div>com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ImportMVCResourceCommandTest.testImportFileWithDoNotImportStrategyAndWithExistingLayoutPageTemplateCollection - UNTESTED</div></li><li><div>com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ImportMVCResourceCommandTest.testImportFileWithDoNotImportStrategyAndWithExistingLayou [...]

2024-05-30 11:43 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/16943//consoleFull)

2024-05-30 11:44 UTC, closed without merging

2024-05-30 11:44 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/150844
[Console](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/16943//consoleFull)

2024-05-30 11:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/16943/">test-portal-acceptance-pullrequest(master)#16943</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/16943/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/15723">liferay-echo#15723</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2573657258">[master] ci:test:relevant - JavierMoral &gt; liferay-echo - PR#15723 - 2024-05-30[03:41:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2573657258<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/36508/">publish-testray-report#36508</a><br/></div></div>