LPD-34189
liferay-echo/liferay-portal pull request #16136
Opened 2024-08-21 12:26 UTC by JavierMoral

Fix https://liferay.atlassian.net/browse/LPD-34189

When the layout can't be found when importing the groupId and layoutId fields of the mapping are cleaned. I kept the privateLayout and layoutUuid fields to leave some clue about what layout was mapped that could be useful in some cases.

2024-08-21 12:26 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2024-08-21 12:26 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-08-22 18:08 UTC, lfbesada commented
ci:test:sf

2024-08-22 18:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6049/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6049/jenkins-report.html">here</a>.</b></p>

2024-08-22 18:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/efc9778e5000f5975408cd15094a65fb5765591f">efc9778e5000f5975408cd15094a65fb5765591f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JavierMoral/liferay-portal/tree/LPD-34189-master">LPD-34189-master</a><br/>Branch GIT ID: <a href="https://github.com/JavierMoral/liferay-portal/commit/74c29492cc9a19c5070670210d7b8ea4504fd2a8">74c29492cc9a19c5070670210d7b8ea4504fd2a8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6049/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6049/jenkins-report.html">here</a>.</h5></details></html>

2024-08-22 18:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6049/">test-portal-source-format#6049</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6049/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/16136">liferay-echo#16136</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/69333954">[master] ci:test:sf - JavierMoral &gt; liferay-echo - PR#16136 - 2024-08-22[11:10:45]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>69333954<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/22908/">publish-testray-report#22908</a><br/></div></div>

2024-08-23 06:18 UTC, lfbesada requested changes
Thank you very much for the fix, it works great! :clap: 
I've left here some suggestions regarding the tests.
Best regards.

2024-08-23 06:18 UTC, lfbesada commented on modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/internal/exportimport/content/processor/test/EditableValuesLayoutMappingExportImportContentProcessorTest.java
> +			JSONFactoryUtil.createJSONObject(
Maybe better to use JSONFactory injected component

2024-08-23 06:18 UTC, lfbesada commented on modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/internal/exportimport/content/processor/test/EditableValuesLayoutMappingExportImportContentProcessorTest.java
> +				_liveGroup.getGroupId());
I think the name should end with FragmentEntryLink

2024-08-23 06:18 UTC, lfbesada commented on modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/internal/exportimport/content/processor/test/EditableValuesLayoutMappingExportImportContentProcessorTest.java
> +			_mappedLayout.getLayoutId(), layoutJSONObject.getLong("layoutId"));
Maybe all this can be encapsulated in an _assertLayoutJSONObject method, what do you think?

2024-08-23 06:18 UTC, lfbesada commented on modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/internal/exportimport/content/processor/test/EditableValuesLayoutMappingExportImportContentProcessorTest.java
> +			_mappedLayout.getLayoutId(), layoutJSONObject.getLong("layoutId"));
Same as above

2024-08-23 06:18 UTC, lfbesada commented on modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/internal/exportimport/content/processor/test/EditableValuesLayoutMappingExportImportContentProcessorTest.java
> +			_mappedLayout.getLayoutId(), layoutJSONObject.getLong("layoutId"));
Same as before, if the method receives the expected values ​​it can be used here as well

2024-08-23 06:26 UTC, lfbesada commented on modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/internal/exportimport/content/processor/test/EditableValuesLayoutMappingExportImportContentProcessorTest.java
> +		throws Exception {
It is always called with the same parameters, I think you can directly use the fields of the class: _liveGroup and _stagingGroup

2024-08-23 06:26 UTC, lfbesada commented on modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/internal/exportimport/content/processor/test/EditableValuesLayoutMappingExportImportContentProcessorTest.java
> +			Layout layout, Layout mappedLayout)
It is always called with the same parameters, I think you can directly use the fields of the class: _draftLayout and _mappedLayout

2024-08-26 11:11 UTC, JavierMoral commented
Removed several AssertNotNulls from tests

2024-08-26 14:32 UTC, lfbesada commented
@JavierMoral Great work! it works perfectly :star_struck:   I just added SF commits to the tests, see: https://github.com/liferay-echo/liferay-portal/pull/16165

2024-08-26 14:32 UTC, closed without merging