LPD-34450
liferay-echo/liferay-portal pull request #16149
Opened 2024-08-23 07:22 UTC by JavierMoral

Just handle the export import of preferences. There will be a next pr including the upgrade process and the removal of the FF.

Had to add method _importSiteNavigationMenuReference to the processor because the staging framework needs a classPK to import a reference and considering that internal ids won't be stored in preferences I had to obtain the classPK from the xml.

2024-08-23 07:22 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2024-08-23 07:22 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-08-26 08:26 UTC, lfbesada requested changes
@JavierMoral Thanks! it works great! :clap: I have left some comments about the tests :kissing_heart:

2024-08-26 15:54 UTC, lfbesada requested changes
I am sorry not to see in the first review that we should take into account https://liferay.atlassian.net/browse/LPS-173790 😞

2024-08-26 15:54 UTC, lfbesada commented on modules/apps/site-navigation/site-navigation-test/src/testIntegration/java/com/liferay/site/navigation/menu/web/internal/exportimport/portlet/preferences/processor/test/SiteNavigationMenuExportImportPortletPreferencesProcessorTest.java
> +				_liveGroup.getGroupId());
Maybe we should also assert that the root menu item haa been imported. What do you think?

2024-08-26 15:54 UTC, lfbesada commented on modules/apps/site-navigation/site-navigation-test/src/testIntegration/java/com/liferay/site/navigation/menu/web/internal/exportimport/portlet/preferences/processor/test/SiteNavigationMenuExportImportPortletPreferencesProcessorTest.java
> +		PortletPreferences livePortletPreferences =
rename to portletPreferences

2024-08-26 15:54 UTC, lfbesada commented on modules/apps/site-navigation/site-navigation-test/src/testIntegration/java/com/liferay/site/navigation/menu/web/internal/exportimport/portlet/preferences/processor/test/SiteNavigationMenuExportImportPortletPreferencesProcessorTest.java
> +		PortletPreferences livePortletPreferences =
rename to portletPreferences

2024-08-26 15:54 UTC, lfbesada commented on modules/apps/site-navigation/site-navigation-test/src/testIntegration/java/com/liferay/site/navigation/menu/web/internal/exportimport/portlet/preferences/processor/test/SiteNavigationMenuExportImportPortletPreferencesProcessorTest.java
> +		Assert.assertNotNull(livePortletPreferences);
I think this would never be null even if the portlet had not been added to the page. Maybe we could do something like this instead:



		List<com.liferay.portal.kernel.model.PortletPreferences>
			portletPreferences =
			_portletPreferencesLocalService.getPortletPreferences(
				layout.getPlid(), portletId);

		Assert.assertEquals(portletPreferences.toString(), 1, portletPreferences.size());

2024-08-26 15:54 UTC, lfbesada commented on modules/apps/site-navigation/site-navigation-menu-web/src/main/java/com/liferay/site/navigation/menu/web/internal/exportimport/portlet/preferences/processor/SiteNavigationMenuExportImportPortletPreferencesProcessor.java
> +		return portletPreferences;
I am afraid we should take into account here the logic added by https://liferay.atlassian.net/browse/LPS-173790 What do you think?  I am sorry not to see it the first time :disappointed:

2024-08-27 11:23 UTC, JavierMoral commented on modules/apps/site-navigation/site-navigation-test/src/testIntegration/java/com/liferay/site/navigation/menu/web/internal/exportimport/portlet/preferences/processor/test/SiteNavigationMenuExportImportPortletPreferencesProcessorTest.java
> +		PortletPreferences livePortletPreferences =
Done in latest push

2024-08-27 11:24 UTC, JavierMoral commented on modules/apps/site-navigation/site-navigation-test/src/testIntegration/java/com/liferay/site/navigation/menu/web/internal/exportimport/portlet/preferences/processor/test/SiteNavigationMenuExportImportPortletPreferencesProcessorTest.java
> +		Assert.assertNotNull(livePortletPreferences);
Done in latest push

2024-08-27 11:24 UTC, JavierMoral commented on modules/apps/site-navigation/site-navigation-menu-web/src/main/java/com/liferay/site/navigation/menu/web/internal/exportimport/portlet/preferences/processor/SiteNavigationMenuExportImportPortletPreferencesProcessor.java
> +		return portletPreferences;
Added in commit [95176ef](https://github.com/liferay-echo/liferay-portal/pull/16149/commits/95176ef2e8c9b7fa2d11bd9c916027fd61833601)

2024-08-27 15:01 UTC, lfbesada commented
@JavierMoral It works great! I've just added SF and more integration tests, see: https://github.com/liferay-echo/liferay-portal/pull/16170

2024-08-27 15:01 UTC, closed without merging