LPD-33018 Add Table button to WYSIWYG Editor toolbar for fragments
liferay-echo/liferay-portal pull request #16163
Opened 2024-08-26 13:18 UTC by BarbaraCabrera

2024-08-26 13:18 UTC, liferay-echo commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2024-08-26 13:18 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-08-28 10:17 UTC, BarbaraCabrera commented
ci:test:sf

2024-08-28 10:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/6659/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6659/jenkins-report.html">here</a>.</b></p>

2024-08-28 10:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ad81eaeaa3f4ab9519585ee9f57dcbea28c55572">ad81eaeaa3f4ab9519585ee9f57dcbea28c55572</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPD-33018">LPD-33018</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/a97fbab5ec22ed80a446f07a853dff32b8cc28b7">a97fbab5ec22ed80a446f07a853dff32b8cc28b7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6659/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6659/jenkins-report.html">here</a>.</h5></details></html>

2024-08-28 10:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6659/">test-portal-source-format#6659</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6659/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/16163">liferay-echo#16163</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/73286402">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#16163 - 2024-08-28[03:17:48]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>73286402<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/26025/">publish-testray-report#26025</a><br/></div></div>

2024-09-03 14:41 UTC, lfbesada requested changes
Great job, Barbara! It's working perfectly!
I've resent the PR to convert the unit test into an integration test and added verifications for this and the rest of the module's editors.
I also took the opportunity to do some code cleanup on some older code. See: https://github.com/liferay-echo/liferay-portal/pull/16212

2024-09-03 14:41 UTC, closed without merging