LPS-123094 buildLang
liferay-echo/liferay-portal pull request #2830
Opened 2020-11-06 09:56 UTC by p2kmgcl

2020-11-06 09:56 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-11-06 09:58 UTC, p2kmgcl commented
ci:test:sf

2020-11-06 09:58 UTC, p2kmgcl commented
ci:test:relevant

2020-11-06 10:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/4575/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-source-format/builds/4575/jenkins-report.html">here</a>.</b></p>

2020-11-06 10:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 0 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e4a0669ac5684ab98be297e3bed7f8d99910fe3">2e4a0669ac5684ab98be297e3bed7f8d99910fe3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/p2kmgcl/liferay-portal/tree/migrate-template-editor-123094">migrate-template-editor-123094</a><br/>Branch GIT ID: <a href="https://github.com/p2kmgcl/liferay-portal/commit/454710ef0c73c64373623a62676d4bf448fdaf5d">454710ef0c73c64373623a62676d4bf448fdaf5d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/4575/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/4575/jenkins-report.html">here</a>.</h5></details></html>

2020-11-06 10:06 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/test-portal-source-format/4575/">test-portal-source-format#4575</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/4575/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-echo/liferay-portal/pull/2830">liferay-echo#2830</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/58311.aspx">master - p2kmgcl > liferay-echo - PR#2830 - 2020-11-06[01:59:47]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/publish-spira-report/8883/">publish-spira-report#8883</a><br />

2020-11-06 10:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/7437/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7437/jenkins-report.html">here</a>.</b></p>

2020-11-06 10:49 UTC, ealonso commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2020-11-06 13:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:x: ci:test:relevant - 21 out of 23 jobs passed in 3 hours 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e4a0669ac5684ab98be297e3bed7f8d99910fe3">2e4a0669ac5684ab98be297e3bed7f8d99910fe3</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/8d22a791300569a6c92e7b9152e6ae1c6bdc863a">8d22a791300569a6c92e7b9152e6ae1c6bdc863a</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426431/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/446138/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/407705/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/407704/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426433/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/407706/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455107/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426432/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/446137/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 21 out of 23 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/7437/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426435/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455111/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455108/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426431/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455106/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/446138/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/407705/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/453978/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455109/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/446136/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/453977/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/407704/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426434/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455110/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426433/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/446135/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/407706/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455107/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/477817/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426432/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426430/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/446137/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7437/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426435/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>10 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=15,label_exp=!master/426435//consoleText">AXIS_VARIABLE=15,label_ex [...]

2020-11-06 13:22 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/7437/">test-portal-acceptance-pullrequest(master)#7437</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7437/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-echo/liferay-portal/pull/2830">liferay-echo#2830</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1312.aspx">/Liferay DXP 7.3/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/58364.aspx">master - p2kmgcl > liferay-echo - PR#2830 - 2020-11-06[02:20:55]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/7684/">publish-spira-report#7684</a><br />

2020-11-10 13:47 UTC, victorg1991 requested changes
Looks really good overall :)

I've added a couple of nits for you to check and also I think that we should add some checks for the autocompletion depending on the mode (freemarker, xls, velocity)

2020-11-10 13:47 UTC, victorg1991 commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/ddm_template_editor/components/CodeMirrorEditor.js
> +			wordList = Object.keys(JSON.parse(autocompleteData).variables)
Could we convert `autocompleteData` from String to JSONObject in the backend?

2020-11-10 13:47 UTC, victorg1991 commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/ddm_template_editor/components/CodeMirrorEditor.js
> +						text: `${openVariable ? '${' : ''}${word}${
We should do different treatment here, in freemarker the variables are `${variable}` whereas in freemarker variables are `$variable`. Also, it seems that when using xls there isn't any autocomplete

2020-11-10 13:47 UTC, victorg1991 commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/ddm_template_editor/components/App.scss
> +	}
![handsheart](https://user-images.githubusercontent.com/11654230/98678939-9266ad80-235f-11eb-99a6-c65142efb4b4.png)

2020-11-10 13:47 UTC, victorg1991 commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/ddm_template_editor/hooks/useChannel.js
> +};
Looks super clean

2020-11-11 07:22 UTC, victorg1991 commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/edit_ddm_template_display.jsp
> +<div>
a `<div class="loading-animation">` maybe?

2020-11-11 10:15 UTC, pavel-savinov commented
Just started reviewing :)

2020-11-11 10:41 UTC, pavel-savinov commented
@p2kmgcl LGTM

2020-11-12 01:33 UTC, Tim-Cao commented
Just start reviewing

2020-11-12 01:39 UTC, Tim-Cao commented
Hi @p2kmgcl and @victorg1991,
There is a regression issue caused by your changes. Can not select structure in template.
*Step to reproduce:*
Product Menu > Web Content > Templates tab
Click the plus icon
Click the Select button of Structure field
Choose the Basic Web Content structure

*Expected Results:*
The Basic Web Content is shown in Structure field and the Content field is available in ddm template editor panel.

*Actual Results:*
The Structure field is empty and the Content field is unavailable in ddm template editor panel.
There is no browser error and server error thrown.

2020-11-12 10:53 UTC, p2kmgcl commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/edit_ddm_template_display.jsp
> +<div>
:+1:

2020-11-12 11:04 UTC, p2kmgcl commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/ddm_template_editor/components/App.js
> +
If we do so, the callback will be continuously added/removed while user is typing. I tried to just use a ref instead of a state&ref, but it's not possible: CodeMirrorEditor component has a useEffect hook that keeps the script prop with the CodeMirror internal state (see https://github.com/liferay-echo/liferay-portal/pull/2830/files#diff-997b6dcb1c9bbd67db2e7c6894c7dde73a7477d498e2b1d7add92b1e184d28b0R187-R191). If I use a ref instead of a state, that useEffect is not executed when the script changes, and we do need that synchronization if the script is changed with the file input.

2020-11-16 09:40 UTC, p2kmgcl commented
Ok, all changes have been applied to the PR, @Tim-Cao I am going to reproduce that :smile:

2020-11-16 10:46 UTC, p2kmgcl commented
@victorg1991 @Tim-Cao everything should be working now. I am going to run tests

2020-11-16 10:47 UTC, p2kmgcl commented
ci:test:relevant

2020-11-16 10:47 UTC, p2kmgcl commented
ci:test:sf

2020-11-16 10:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/4054/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-source-format/builds/4054/jenkins-report.html">here</a>.</b></p>

2020-11-16 10:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7535/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7535/jenkins-report.html">here</a>.</b></p>

2020-11-16 10:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c74cbb3487428c54ae2122c205af3c954e0e01a3">c74cbb3487428c54ae2122c205af3c954e0e01a3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/p2kmgcl/liferay-portal/tree/migrate-template-editor-123094">migrate-template-editor-123094</a><br/>Branch GIT ID: <a href="https://github.com/p2kmgcl/liferay-portal/commit/37ff60eca63246d41a468c04ad2c347f3f82e569">37ff60eca63246d41a468c04ad2c347f3f82e569</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/4054/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/4054/jenkins-report.html">here</a>.</h5><pre><code>  &lt;arg value="-PdependencyNotation=com.liferay.portal:com.liferay.portal.plugins.sdk:1.0.42" /&gt;
  &lt;arg value="--max-workers=4" /&gt;
  &lt;arg value="--no-daemon" /&gt;
  &lt;arg value="--profile" /&gt;
  &lt;arg value="--project-cache-dir=/opt/dev/projects/github/liferay-portal/.gradle" /&gt;
  &lt;arg value="--stacktrace" /&gt;
  &lt;arg value="-Dapp.server.parent.dir=/opt/dev/projects/github/liferay-portal/bundles" /&gt;
  &lt;arg value="-Dforced.cache.enabled=true" /&gt;
  &lt;arg value="-Dliferay.home=/opt/dev/projects/github/liferay-portal/bundles" /&gt;
  &lt;arg value="-Dorg.gradle.internal.http.connectionTimeout=120000" /&gt;
  &lt;arg value="-Dorg.gradle.internal.http.socketTimeout=120000" /&gt;
  &lt;arg value="-Dorg.gradle.jvmargs=-Dhttp.nonProxyHosts=&amp;quot;cloud*|files.liferay.org.es|it.liferay.com|localhost|mirrors-no-cache.lax.liferay.com|release*|test*&amp;quot; -server -verbose:gc -Xloggc:/tmp/ant-gc.log -Xms1024m -Xmx4096m -Xss2m -Xverify:none -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCCause -XX:+PrintGCDetails -XX:+UseParallelOldGC -XX:HeapDumpPath=/tmp/ant-oom-heap-dump.bin -XX:MaxNewSize=512m -XX:MaxMetaspaceSize=512m -XX:MaxTenuringThreshold=0 -XX:NewSize=256m -XX:MetaspaceSize=100m -XX:SurvivorRatio=65536 -XX:TargetSurvivorRatio=0" /&gt;
  &lt;arg line="printDependencyPath" /&gt;
  &lt;redirector errorproperty="error.property" outputproperty="output.property" /&gt;
&lt;/exec&gt;
     [echo] 
[stopwatch] [run.batch.test.action: 7.262 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build.xml:1123: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:1771: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:1004: Unable to execute Gradle task: printDependencyPath.
      [get] Getting: http://test-1-2/job/test-portal-source-format/4054//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20201116024837491.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20201116024837491.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2068898645.properties</code></pre></details></html>

2020-11-16 10:50 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-2.liferay.com/job/test-portal-source-format/4054/">test-portal-source-format#4054</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/4054/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-echo/liferay-portal/pull/2830">liferay-echo#2830</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/61215.aspx">master - p2kmgcl > liferay-echo - PR#2830 - 2020-11-16[02:47:34]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/13798/">publish-spira-report#13798</a><br />

2020-11-16 10:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c74cbb3487428c54ae2122c205af3c954e0e01a3">c74cbb3487428c54ae2122c205af3c954e0e01a3</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7535/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7535/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7535/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [echo] * What went wrong:
     [echo] Could not resolve all artifacts for configuration 'classpath'.
     [echo] &gt; Could not find com.github.jk1:gradle-license-report:1.8.
     [echo]   Searched in the following locations:
     [echo]     - file:/root/.m2/repository/com/github/jk1/gradle-license-report/1.8/gradle-license-report-1.8.pom
     [echo]     - https://repository-cdn.liferay.com/nexus/content/groups/public/com/github/jk1/gradle-license-report/1.8/gradle-license-report-1.8.pom
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo] &gt; Could not find com.gradle.publish:plugin-publish-plugin:0.11.0.
     [echo]   Searched in the following locations:
     [echo]     - file:/root/.m2/repository/com/gradle/publish/plugin-publish-plugin/0.11.0/plugin-publish-plugin-0.11.0.pom
     [echo]     - https://repository-cdn.liferay.com/nexus/content/groups/public/com/gradle/publish/plugin-publish-plugin/0.11.0/plugin-publish-plugin-0.11.0.pom
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo] &gt; Could not find gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:4.0.0.
     [echo]   Searched in the following locations:
     [echo]     - file:/root/.m2/repository/gradle/plugin/com/github/spotbugs/snom/spotbugs-gradle-plugin/4.0.0/spotbugs-gradle-plugin-4.0.0.pom
     [echo]     - https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/com/github/spotbugs/snom/spotbugs-gradle-plugin/4.0.0/spotbugs-gradle-plugin-4.0.0.pom
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo] &gt; Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.5.7.RELEASE.
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo]    &gt; Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.5.7.RELEASE.
     [echo]       &gt; Could not parse POM https://repository-cdn.liferay.com/nexus/content/groups/public/org/springframework/boot/spring-boot-gradle-plugin/1.5.7.RELEASE/spring-boot-gradle-plugin-1.5.7.RELEASE.pom
     [echo]          &gt; Could not find org.springframework.boot:spring-boot-tools:1.5.7.RELEASE.</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2020-11-17 07:03 UTC, p2kmgcl commented
ci:test:sf

2020-11-17 07:03 UTC, p2kmgcl commented
ci:test:relevant

2020-11-17 07:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/2281/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-portal-source-format/builds/2281/jenkins-report.html">here</a>.</b></p>

2020-11-17 07:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 seconds</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c74cbb3487428c54ae2122c205af3c954e0e01a3">c74cbb3487428c54ae2122c205af3c954e0e01a3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/p2kmgcl/liferay-portal/tree/migrate-template-editor-123094">migrate-template-editor-123094</a><br/>Branch GIT ID: <a href="https://github.com/p2kmgcl/liferay-portal/commit/37ff60eca63246d41a468c04ad2c347f3f82e569">37ff60eca63246d41a468c04ad2c347f3f82e569</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/2281/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/2281/jenkins-report.html">here</a>.</h5></details></html>

2020-11-17 07:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest(master)/7526/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7526/jenkins-report.html">here</a>.</b></p>

2020-11-17 07:22 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-15.liferay.com/job/test-portal-source-format/2281/">test-portal-source-format#2281</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/2281/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-echo/liferay-portal/pull/2830">liferay-echo#2830</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/61662.aspx">master - p2kmgcl > liferay-echo - PR#2830 - 2020-11-16[23:08:12]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/8426/">publish-spira-report#8426</a><br />

2020-11-17 08:06 UTC, p2kmgcl commented
ci:stop

2020-11-17 08:06 UTC, p2kmgcl commented
ci:test:relevant

2020-11-17 08:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7147/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7147/jenkins-report.html">here</a>.</b></p>

2020-11-17 08:07 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 48 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/44db1de072463c2b643ca9a4e7a08bd4c8ef5832">44db1de072463c2b643ca9a4e7a08bd4c8ef5832</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/8d22a791300569a6c92e7b9152e6ae1c6bdc863a">8d22a791300569a6c92e7b9152e6ae1c6bdc863a</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest(master)/7526/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7526/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest(master)/7526/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>Build was aborted</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2020-11-17 08:15 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest(master)/7526/">test-portal-acceptance-pullrequest(master)#7526</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7526/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-echo/liferay-portal/pull/2830">liferay-echo#2830</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1312.aspx">/Liferay DXP 7.3/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/61684.aspx">master - p2kmgcl > liferay-echo - PR#2830 - 2020-11-16[23:19:37]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/13993/">publish-spira-report#13993</a><br />

2020-11-17 11:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:x: ci:test:relevant - 20 out of 25 jobs passed in 3 hours 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/157241864d789de0467b23ad63b8a2a8f40a2985">157241864d789de0467b23ad63b8a2a8f40a2985</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/8d22a791300569a6c92e7b9152e6ae1c6bdc863a">8d22a791300569a6c92e7b9152e6ae1c6bdc863a</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417219/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444560/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396882/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396881/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/341918/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320967/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417223/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417221/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417224/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 20 out of 25 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7147/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417225/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315697/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/341919/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/457840/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>20 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396880/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396877/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417219/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/418167/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444560/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396882/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/469392/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396878/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417220/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396881/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417222/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396879/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/341918/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315696/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320967/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417223/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396883/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417221/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315695/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417224/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7147/jenkins-report.html">here</a>. [...]

2020-11-17 11:48 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7147/">test-portal-acceptance-pullrequest(master)#7147</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7147/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-echo/liferay-portal/pull/2830">liferay-echo#2830</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1312.aspx">/Liferay DXP 7.3/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/61775.aspx">master - p2kmgcl > liferay-echo - PR#2830 - 2020-11-17[00:07:10]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/14020/">publish-spira-report#14020</a><br />

2020-11-18 08:30 UTC, p2kmgcl commented
ci:test:relevant

2020-11-18 09:02 UTC, Tim-Cao commented
See https://github.com/liferay-echo/liferay-portal/pull/2924

2020-11-18 09:02 UTC, Tim-Cao commented
ci:close

2020-11-18 09:02 UTC, closed without merging

2020-11-18 13:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/7951/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7951/jenkins-report.html">here</a>.</b></p>

2020-11-18 19:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:x: ci:test:relevant - 21 out of 23 jobs passed in 5 hours 36 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a13ddd1546319ec52ea5228accd463f4c407694c">a13ddd1546319ec52ea5228accd463f4c407694c</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/8d22a791300569a6c92e7b9152e6ae1c6bdc863a">8d22a791300569a6c92e7b9152e6ae1c6bdc863a</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451272/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417372/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315832/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/454892/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451275/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315833/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451278/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451273/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451279/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 21 out of 23 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/7951/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451281/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417373/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451280/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451272/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417374/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417372/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315832/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451282/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/454889/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451276/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/454890/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/454892/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451277/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/454891/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451275/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451274/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315833/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451278/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/454893/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451273/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451271/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451279/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7951/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451281/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>47 Tests Passed.<br/>6 Tests Failed.</p></div><ol><li><div><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=14,label_exp=!master/451281//consoleText">AXIS_VARIABLE=14,l [...]

2020-11-18 19:41 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/7951/">test-portal-acceptance-pullrequest(master)#7951</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7951/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-echo/liferay-portal/pull/2830">liferay-echo#2830</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1312.aspx">/Liferay DXP 7.3/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/62407.aspx">master - p2kmgcl > liferay-echo - PR#2830 - 2020-11-18[05:42:14]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/8586/">publish-spira-report#8586</a><br />