LPS-133629 Select folder in Web Content add view from Asset Publisher
liferay-echo/liferay-portal pull request #4783
Opened 2021-06-04 12:42 UTC by lfbesada

2021-06-04 12:53 UTC, ealonso commented
ci:test:sf

2021-06-04 12:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/5590/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-source-format/builds/5590/jenkins-report.html">here</a>.</b></p>

2021-06-04 12:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8e2f0f9c21e9d3c616b38ea641da9bb2a6d08fe4">8e2f0f9c21e9d3c616b38ea641da9bb2a6d08fe4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lfbesada/liferay-portal/tree/LPS-133629">LPS-133629</a><br/>Branch GIT ID: <a href="https://github.com/lfbesada/liferay-portal/commit/7daa0844f09b1a4600df747eb2c788ba3d020a44">7daa0844f09b1a4600df747eb2c788ba3d020a44</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/5590/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/5590/jenkins-report.html">here</a>.</h5></details></html>

2021-06-04 13:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/5590/">test-portal-source-format#5590</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/5590/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/4783">liferay-echo#4783</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1537655434">[master] ci:test:sf - lfbesada &gt; liferay-echo - PR#4783 - 2021-06-04[05:53:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/1236/">publish-testray-report#1236</a><br/></div></div>

2021-06-07 06:26 UTC, p2kmgcl requested changes
Hey @lfbesada, I just suggested a small refactor that might simplify the solution :smile:

2021-06-07 06:26 UTC, p2kmgcl commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/SelectFolderButton.es.js
> +class SelectFolderButton extends PortletBase {
Thanks for this :smile:

2021-06-07 06:26 UTC, p2kmgcl commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/SelectFolderButton.es.js
> +						idString: hiddenFolderIdInput,
As this parameter is called `idString`... did you try to pass `this.ns('newFolderId')`? I think it should work too

2021-06-07 07:07 UTC, lfbesada commented on modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/SelectFolderButton.es.js
> +						idString: hiddenFolderIdInput,
Thanks! I have simplified js.

2021-06-07 07:08 UTC, lfbesada commented
ci:test:sf

2021-06-07 07:40 UTC, jkappler commented on modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/display/context/JournalEditArticleDisplayContext.java
> +		_folderName = _getFolderName();
Hi @lfbesada, I think we can join both methods here

2021-06-07 07:41 UTC, jkappler commented on modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/display/context/JournalEditArticleDisplayContext.java
> +		if (JournalFolderConstants.DEFAULT_PARENT_FOLDER_ID != getFolderId()) {
@lfbesada, normally we only call the method once, and use the variable afterwards

2021-06-07 07:42 UTC, jkappler commented on modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/display/context/JournalEditArticleDisplayContext.java
> +		_showSelectFolder =
Hi @lfbesada, in the assignment we normally use an if instead of the boolean expression

2021-06-07 07:43 UTC, jkappler commented
@lfbesada, thanks for the pull :D. Just some very small SFs

2021-06-07 08:53 UTC, lfbesada commented on modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/display/context/JournalEditArticleDisplayContext.java
> +		_folderName = _getFolderName();
Done, thanks!

2021-06-07 08:56 UTC, lfbesada commented on modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/display/context/JournalEditArticleDisplayContext.java
> +		if (JournalFolderConstants.DEFAULT_PARENT_FOLDER_ID != getFolderId()) {
Thanks, I joint the two methods

2021-06-07 08:57 UTC, lfbesada commented on modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/display/context/JournalEditArticleDisplayContext.java
> +		_showSelectFolder =
Done, thanks!

2021-06-07 09:03 UTC, lfbesada commented
ci:test:sf

2021-06-08 07:12 UTC, ealonso commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2021-06-08 08:50 UTC, ealonso commented
see: https://github.com/liferay-echo/liferay-portal/pull/4810

2021-06-08 08:50 UTC, closed without merging