LPS-139658
liferay-echo/liferay-portal pull request #5958
Opened 2021-09-23 16:51 UTC by ozysouza

2021-09-23 16:51 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-09-23 19:18 UTC, ozysouza commented
ci:test:sf

2021-09-23 19:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/441/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-source-format/builds/441/jenkins-report.html">here</a>.</b></p>

2021-09-23 19:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/35a9f6c294299b41880c44ceb933b24925a7d04a">35a9f6c294299b41880c44ceb933b24925a7d04a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ozysouza/liferay-portal/tree/LPS-139658-II">LPS-139658-II</a><br/>Branch GIT ID: <a href="https://github.com/ozysouza/liferay-portal/commit/7864496316732e3fd74fc12d1fcb9b47c07c6a43">7864496316732e3fd74fc12d1fcb9b47c07c6a43</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/441/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/441/jenkins-report.html">here</a>.</h5></details></html>

2021-09-23 19:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/441/">test-portal-source-format#441</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/441/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/5958">liferay-echo#5958</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1563672789">[master] ci:test:sf - ozysouza &gt; liferay-echo - PR#5958 - 2021-09-23[12:18:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/1457/">publish-testray-report#1457</a><br/></div></div>

2021-09-24 08:44 UTC, david-gutierrez-mesa requested changes
Please take a look to the my commnets

2021-09-24 08:44 UTC, david-gutierrez-mesa commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase
> +	@description = "LPS-72048 - Verify that Belongs To rule can be paired with Guest role"
Please use the standard way for description. example "This is a use case for LPS-XXXXXX. Test case description."

2021-09-24 08:44 UTC, david-gutierrez-mesa commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase
> +	@description = "This is a use case for LPS-81578."
Please add test case description

2021-09-24 08:44 UTC, david-gutierrez-mesa commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase
> +			fieldName = "Text");
Please use tasks to separate tests steps

2021-09-24 08:44 UTC, david-gutierrez-mesa commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/FormsTextField.testcase
> +	@description = "LPS-84111 - Verify that Text Field can be autosaved on form builder"
Please use the standard way for description. example "This is a use case for LPS-XXXXXX. Test case description."

2021-09-24 08:44 UTC, david-gutierrez-mesa commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase
> +		Alert.viewWarningSpecific(warningMessage = "You do not have the permission to view this form.");
Please use tasks to separate tests steps

2021-09-24 08:44 UTC, david-gutierrez-mesa commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/FormsTextField.testcase
> +			locator1 = "FormFields#FIELD_TARGET_LABEL");
Please use tasks to separate tests steps

2021-09-24 11:41 UTC, david-gutierrez-mesa commented
Just started reviewing :)

2021-09-24 11:43 UTC, closed without merging

2021-09-24 11:43 UTC, david-gutierrez-mesa commented
Rebased. See #195