Remove AUI from HTMLProcessor.js
liferay-echo/liferay-portal pull request #8059
Opened 2022-05-10 13:37 UTC by DiegoHu97

From modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/processors/HTMLProcessor.js

2022-05-10 13:37 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-05-11 10:20 UTC, victorg1991 commented
ci:test:sf

2022-05-11 10:22 UTC, victorg1991 commented on modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/processors/CodeMirrorEditor.js
> +	const ref = useRef();
This ref is unused, I think we can safely remove it

2022-05-11 10:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/3702/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3702/jenkins-report.html">here</a>.</b></p>

2022-05-11 10:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f89dc4e06a6bba4f5bbf8e25a8b71ec33de84c7e">f89dc4e06a6bba4f5bbf8e25a8b71ec33de84c7e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/DiegoHu97/liferay-portal/tree/LPS-124413">LPS-124413</a><br/>Branch GIT ID: <a href="https://github.com/DiegoHu97/liferay-portal/commit/b5a365838bdfd041682e8c4f19b13521d707599b">b5a365838bdfd041682e8c4f19b13521d707599b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/3702/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3702/jenkins-report.html">here</a>.</h5></details></html>

2022-05-11 10:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/3702/">test-portal-source-format#3702</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3702/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/8059">liferay-echo#8059</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1799472747">[master] ci:test:sf - DiegoHu97 &gt; liferay-echo - PR#8059 - 2022-05-11[03:21:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/2482/">publish-testray-report#2482</a><br/></div></div>

2022-05-11 10:42 UTC, victorg1991 requested changes
Hey @DiegoHu97 this looks gorgeous! It works like a charm!

I believe we can improve some code a bit and also the style of the modal should be change to  look like the old one. I have left some comments over the code, apart from those comments I think we should change the following things:

- Move the components created in this PR to the components folder (I think it is better to put them there and leave this folder only for processors)
- Now that we have a CSS file we can change the border color of the editor separator and set a light gray similar to what we had (but using a clay color variable)

![Screenshot 2022-05-11 at 12 11 13](https://user-images.githubusercontent.com/11654230/167831157-d9f1fc6d-65d9-469b-862a-7dd73441e0a4.png)

- I believe we should only remove the padding from the bottom, the buttons should have some padding as show above
- The buttons doesn't have space between them and they are smaller than the ones in this PR (there is a property small in the button that we can use) 

And that's all, after that everything will be fino filipino 👏  Let me know if you need more information or any help with this :) 

It seems like a lot of things to change, but it is for polishing the result. Right now, it works fine so really great work so far!

2022-05-11 10:42 UTC, victorg1991 commented on modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/processors/CodeMirrorEditor.js
> +	}, [initialContent]);
These two useEffect are not needed:

- The first one set the mode to html, but we are doing that in the line 65, so this shouldn't be needed, probably the mode set in the Line 65 should be `text/html` instead of `html`
- The second one is updating the value of the content, but we need to only set the initial value, so this is not needed

2022-05-11 10:42 UTC, victorg1991 commented on modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/processors/HTLMPreview.js
> +	return <div dangerouslySetInnerHTML={{__html: content}} />;
I thought at first that this component will be more complex, but since it is only a `<div` we can remove this component and use the <div directly (changing the call to this component for a simple div call)

2022-05-11 10:42 UTC, victorg1991 commented on modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/processors/HTMLEditorModal.js
> +	};
We tend to declare this constants outside the component, since there is no need to redeclare the variable in each render

2022-05-11 10:42 UTC, victorg1991 commented on modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/processors/HTMLEditorModal.js
> +						<ClayButton.Group spaced>
I believe this spaced attribute is not needed, in the original design the buttons are placed together

2022-05-11 10:42 UTC, victorg1991 commented on modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/processors/HTMLEditorModal.js
> +								'h-50 w-100': viewType === VIEW_TYPES.rows,
😻

2022-05-11 10:43 UTC, victorg1991 commented
ci:test:relevant

2022-05-11 12:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3863/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3863/jenkins-report.html">here</a>.</b></p>

2022-05-11 14:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3863/">test-portal-acceptance-pullrequest(master)#3863</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3863/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/8059">liferay-echo#8059</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1801796848">[master] ci:test:relevant - DiegoHu97 &gt; liferay-echo - PR#8059 - 2022-05-11[05:10:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/10963/">publish-testray-report#10963</a><br/></div></div>

2022-05-13 01:45 UTC, Tim-Cao commented
Sure!

2022-05-13 02:59 UTC, Tim-Cao commented
See https://github.com/liferay-echo/liferay-portal/pull/8092

2022-05-13 03:00 UTC, Tim-Cao commented
ci:close

2022-05-13 03:00 UTC, closed without merging