LPS-157681 Add friendlyURL to FreeMarker context of web content templates
liferay-echo/liferay-portal pull request #8909
Opened 2022-07-13 13:57 UTC by BarbaraCabrera

2022-07-13 13:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-13 13:57 UTC, BarbaraCabrera commented
ci:test:sf

2022-07-13 13:57 UTC, BarbaraCabrera commented
ci:test:relevant

2022-07-13 14:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d365f9baded97fa9119cb07f5e0342304bf6c298">d365f9baded97fa9119cb07f5e0342304bf6c298</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-157681">LPS-157681</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/d9eddd02be5687857724fc55a3e014b7d6cf8f4d">d9eddd02be5687857724fc55a3e014b7d6cf8f4d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/896/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/896/jenkins-report.html">here</a>.</h5></details></html>

2022-07-13 14:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/896/">test-portal-source-format#896</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/896/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/8909">liferay-echo#8909</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1905133419">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#8909 - 2022-07-13[06:57:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/3639/">publish-testray-report#3639</a><br/></div></div>

2022-07-13 15:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/4155/">test-portal-acceptance-pullrequest(master)#4155</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4155/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/8909">liferay-echo#8909</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1905190326">[master] ci:test:relevant - BarbaraCabrera &gt; liferay-echo - PR#8909 - 2022-07-13[06:57:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/11334/">publish-testray-report#11334</a><br/></div></div>

2022-07-14 06:30 UTC, lfbesada requested changes
Hi @BarbaraCabrera 
Good job! 👏 
I added a comment for a minor change.
Thanks!

2022-07-14 06:30 UTC, lfbesada commented on modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java
> +			LanguageUtil.getLanguageId(themeDisplay.getLocale()));
For consistency, you should use the same to get the languageId. Here you are using two different methods to get the same, LanguageUtil.getLanguageId and LocaleUtil.toLanguageId. The appropriate way is to use LocaleUtil.toLanguageId directly since LanguageUtil.getLanguageId ends up invoking it.

2022-07-14 09:43 UTC, ealonso commented on modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java
> +			LanguageUtil.getLanguageId(themeDisplay.getLocale()));
@BarbaraCabrera @lfbesada we have a method to get the languageId on themeDisplay, please see:

```
themeDisplay.getLanguageId()
```

2022-07-14 09:47 UTC, ealonso commented on modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java
> +			LanguageUtil.getLanguageId(themeDisplay.getLocale()));
Also it can be improved to something like:

```
String friendlyURL = friendlyURLMap.get(themeDisplay.getLanguageId());

if (Validator.isNull() {
    friendlyURL = friendlyURLMap.get(
	LocaleUtil.toLanguageId(LocaleUtil.getSiteDefault()));
}

return friendlyURL;
```

2022-07-14 10:08 UTC, lfbesada commented on modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java
> +			LanguageUtil.getLanguageId(themeDisplay.getLocale()));
We should ensure never return null. @ealonso What do you think about something like that?

```
String friendlyURL = friendlyURLMap.get(themeDisplay.getLanguageId());

if (Validator.isNull(friendlyURL)) {
    friendlyURL = friendlyURLMap.get(
	LocaleUtil.toLanguageId(LocaleUtil.getSiteDefault()));
}

if (Validator.isNull(friendlyURL)) {
    friendlyURL = StringPool.BLANK
}

return friendlyURL;
```

2022-07-14 11:02 UTC, BarbaraCabrera commented
ci:test:relevant

2022-07-14 11:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/2820/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2820/jenkins-report.html">here</a>.</b></p>

2022-07-14 11:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d365f9baded97fa9119cb07f5e0342304bf6c298">d365f9baded97fa9119cb07f5e0342304bf6c298</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-157681">LPS-157681</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/3613e852670b2ce74e8cc1f90f9efba892a3a66a">3613e852670b2ce74e8cc1f90f9efba892a3a66a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2820/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2820/jenkins-report.html">here</a>.</h5></details></html>

2022-07-14 11:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2820/">test-portal-source-format#2820</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2820/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/8909">liferay-echo#8909</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1906401454">[master] ci:test:sf - BarbaraCabrera &gt; liferay-echo - PR#8909 - 2022-07-14[04:03:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/10274/">publish-testray-report#10274</a><br/></div></div>

2022-07-14 12:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/4041/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4041/jenkins-report.html">here</a>.</b></p>

2022-07-14 16:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/2018/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2018/jenkins-report.html">here</a>.</b></p>

2022-07-14 19:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/2018/">test-portal-acceptance-pullrequest(master)#2018</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2018/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/8909">liferay-echo#8909</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1906774462">[master] ci:test:relevant - BarbaraCabrera &gt; liferay-echo - PR#8909 - 2022-07-14[09:05:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/5094/">publish-testray-report#5094</a><br/></div></div>

2022-07-15 07:18 UTC, lfbesada commented
ci:test:relevant

2022-07-15 07:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4786/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4786/jenkins-report.html">here</a>.</b></p>

2022-07-15 10:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 66 out of 70 jobs passed in 2 hours 22 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3549">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1327401_4786</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee51f1001b9ec5b51ff6dbd05d2ca969f002ef22">ee51f1001b9ec5b51ff6dbd05d2ca969f002ef22</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/578a65dca9586a7255be6a0e81f773e3e5e9d810">578a65dca9586a7255be6a0e81f773e3e5e9d810</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3548">Acceptance Upstream DXP (master) #3548</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53501/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106177/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/99995/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44936/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49654/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53996/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53016/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44796/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/112422/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119731/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116706/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53998/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49308/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/112421/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53499/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/52664/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/42683/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126226/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126240/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/115903/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106188/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/47633/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121880/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65100/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106183/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56083/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50892/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 66 out of 70 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4786/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/47625/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/112429/"><strike>modules-integration-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65109/"><strike>modules-integration-mysql57-jdk8/0/2</strike></a></li></ul></li></ul></div><details><summary><strong>66 Successful Jobs:</strong></summary><ul><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56085/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53999/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116705/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53501/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53017/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test [...]

2022-07-15 10:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4786/">test-portal-acceptance-pullrequest(master)#4786</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4786/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-echo/liferay-portal/pull/8909">liferay-echo#8909</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1907893871">[master] ci:test:relevant - BarbaraCabrera &gt; liferay-echo - PR#8909 - 2022-07-15[00:53:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/13131/">publish-testray-report#13131</a><br/></div></div>

2022-07-16 11:18 UTC, lfbesada commented
ci:reevaluate:1327401_4786

2022-07-16 11:19 UTC, liferay-continuous-integration commented
CI is reevaluating the build with build ID: `1327401_4786` against the latest valid upstream results.

2022-07-16 11:22 UTC, liferay-continuous-integration commented
<html><p>Previous <code>ci:test:relevant</code><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4786">build</a> was successfully <a href="https://test-1-25.liferay.com/job/test-portal-evaluate-pullrequest/91/">reevaluated</a> against more recent upstream results.</p><h3>:heavy_check_mark: ci:test:stable - 25 out of 25 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 67 out of 70 jobs passed in 2 hours 22 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee51f1001b9ec5b51ff6dbd05d2ca969f002ef22">ee51f1001b9ec5b51ff6dbd05d2ca969f002ef22</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee51f1001b9ec5b51ff6dbd05d2ca969f002ef22">ee51f1001b9ec5b51ff6dbd05d2ca969f002ef22</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3549">Acceptance Upstream DXP (master) #3549</a></p><details><summary><strong>ci:test:stable - 25 out of 25 jobs PASSED</strong></summary><details><summary><strong>25 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53501/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44936/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49654/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53996/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53016/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44796/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/112422/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119731/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116706/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53998/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49308/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/112421/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53499/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/52664/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/42683/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126226/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126240/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/115903/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106188/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/47633/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121880/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65100/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106183/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56083/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50892/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 66 out of 70 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4786/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/47625/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/112429/"><strike>modules-integration-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65109/"><strike>modules-integration-mysql57-jdk8/0/2</strike></a></li></ul></li></ul></div><details><summary><strong>66 Successful Jobs:</strong></summary><ul><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56085/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53999/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116705/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53501/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53017/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/103944/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/52666/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126234/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116712/">functional-to [...]

2022-07-16 12:20 UTC, lfbesada approved these changes
Good job! 👏

2022-07-16 12:20 UTC, lfbesada commented
ci:forward

2022-07-16 12:20 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-07-16 12:20 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-07-16 12:21 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/349//consoleFull)

2022-07-16 12:21 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/120473
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/349//consoleFull)

2022-07-16 12:21 UTC, closed without merging